import type { InterfaceLocaleCode } from "@/lib/international-context";

const copy = {
  fr: {
    heroLead: "Qu’est-ce qui",
    heroEmphasis: "freine votre entreprise",
    heroQuestionMark: "\u00a0?",
    heroDescription: "On vous aide à clarifier les priorités, à structurer une activité plus rentable et moins dépendante de vous.",
    situationLabel: "Décrivez la situation de votre entreprise",
    createPlan: "Créer mon plan d’action",
    creatingPlan: "Création du plan…",
    blankPlan: "Commencer avec un plan vierge",
    dictate: "Dicter ma situation",
    stopDictation: "Arrêter la dictée",
    savePlan: "Enregistrez votre plan",
    close: "Fermer",
    expired: "Votre demande a expiré. Décrivez à nouveau votre situation.",
    tooShort: "Décrivez votre situation en quelques phrases pour obtenir un plan utile.",
    alreadyGenerating: "Une génération est déjà en cours.",
    generationFailed: "Impossible de générer le plan pour le moment.",
    autoSaveFailed: "La sauvegarde automatique a échoué.",
    generationBar: {
      prompt: "Qu’est-ce qui freine votre entreprise ?",
      stopDictation: "Arrêter la dictée",
      dictate: "Dicter ma demande",
      generate: "Générer le plan",
      failed: "Le plan n’a pas pu être créé.",
    },
    generationScreen: {
      status: "Génération de votre plan d’action",
      questions: [
        "Si je m’absente un mois, mon entreprise continue-t-elle de fonctionner ?",
        "Quelles décisions dépendent encore systématiquement de moi ?",
        "Mon équipe sait-elle quoi faire sans attendre mes instructions ?",
        "Que pourrais-je supprimer, simplifier, déléguer ou automatiser ?",
        "Est-ce que la qualité reste constante lorsque je ne supervise pas directement ?",
      ],
    },
    generationState: {
      statusCheckFailed: "Impossible de vérifier la génération pour le moment.",
      restartFailed: "La génération n’a pas pu redémarrer.",
      inProgress: "Génération en cours",
      interrupted: "Génération interrompue",
      retrying: "Nouvelle tentative…",
      retry: "Réessayer",
      newPlan: "Nouveau plan",
    },
    selector: {
      choose: "Choisir un système",
      searchPlaceholder: "Rechercher un système…",
      searchLabel: "Rechercher un système métier",
      listLabel: "Systèmes métier",
      empty: "Aucun système trouvé.",
    },
    utility: {
      saving: "Sauvegarde…",
      retry: "Réessayer",
      menuLabel: "Actions du plan",
      newPlan: "Nouveau plan",
    },
    navbar: {
      home: "Retour à l’accueil",
      accountMenu: "Ouvrir le menu du compte",
      myPlans: "Mes plans",
      signIn: "Connexion",
    },
    systemShare: {
      titlePrefix: "Système",
      copiedLabel: "Lien du système copié",
      shareLabel: "Partager ce système",
      copiedTitle: "Lien copié",
    },
    result: {
      filters: {
        week: "Cette semaine",
        all: "Toutes les actions",
        overdue: "En retard",
        done: "Terminées",
      },
      filterLabel: "Filtrer les actions",
      statuses: {
        todo: "À faire",
        in_progress: "En cours",
        done: "Terminé",
      },
      moveTo: "Passer à",
      action: "Action",
      actionTitle: "Titre de l’action",
      close: "Fermer",
      dueDate: "Échéance",
      expectedResult: "Résultat attendu",
      tasks: "Tâches",
      markTaskDone: (index: number) => `Marquer la tâche ${index} comme terminée`,
      taskLabel: (index: number) => `Tâche ${index}`,
      deleteTask: "Supprimer la tâche",
      deleteTaskLabel: (index: number) => `Supprimer la tâche ${index}`,
      supportTitle: "Titre du support",
      copy: "Copier",
      supportContent: "Contenu du support",
      defaultSupportLabel: "Support personnel",
      addSupport: "Ajouter un support personnel",
      personalNotes: "Notes personnelles",
      notesPlaceholder: "Ajoutez un suivi, une décision ou un point à retenir…",
      deleteQuestion: "Supprimer cette action ?",
      cancel: "Annuler",
      delete: "Supprimer",
      deleteAction: "Supprimer l’action",
      planActions: "Actions du plan",
      showKanban: "Afficher en Kanban",
      showList: "Afficher en liste",
      noActions: "Aucune action",
      addAction: "Ajouter une action",
    },
    savedPlan: {
      planName: "Nom du plan",
      planActions: "Actions du plan",
      switchPlan: "Changer de plan",
      opening: "Ouverture…",
      generating: "Génération en cours",
      needsAttention: "À reprendre",
      updated: "Modifié le",
      source: "Voir la demande initiale",
      newPlan: "Nouveau plan",
      rename: "Renommer",
      deleting: "Suppression…",
      delete: "Supprimer",
      deleteConfirmation: "Supprimer ce plan ? Cette action est définitive dans l’application.",
      saving: "Enregistrement…",
      saved: "Modifications enregistrées",
      keepChanges: "Garder mes modifications",
      useLatest: "Utiliser la version récente",
      retry: "Réessayer",
      saveFailed: "Impossible d’enregistrer les modifications.",
      recentLoadFailed: "Impossible de charger la version récente du plan.",
      deleteFailed: "Impossible de supprimer ce plan.",
      planNotBlank: "Ce plan contient déjà des informations à conserver.",
      saveBeforeGenerate: "Enregistrez les dernières modifications avant de générer le plan.",
      sessionExpired: "Votre session a expiré. Reconnectez-vous pour enregistrer vos modifications.",
    },
    share: {
      title: "Mon plan d’action Demaa",
      thisWeek: "À faire cette semaine",
      copied: "Plan copié",
      sharePlan: "Partager le plan",
      share: "Partager",
    },
    system: {
      loadFailed: "Impossible de charger ce système métier.",
      sectionLabel: "Système",
      title: "Solutions pour votre entreprise",
      savedSystems: "Systèmes enregistrés",
      chooseTitle: "Choisissez votre système métier",
      chooseDescription: "Sélectionnez votre activité parmi les 115 systèmes pour afficher ses solutions.",
      loading: "Chargement du système métier…",
      retry: "Réessayer",
    },
    examples: [
      "Je dirige un cabinet comptable de 6 personnes. Les dossiers avancent, mais tout remonte encore vers moi et les échéances sont suivies dans plusieurs fichiers.",
      "Mon restaurant fonctionne bien le midi, mais la marge baisse. Les achats, les plannings et les pertes ne sont pas suivis de façon régulière.",
      "Je développe une entreprise de plomberie avec 4 techniciens. Je veux mieux organiser les interventions, les devis et les relances sans ajouter un outil compliqué.",
      "Je suis consultante indépendante. J’ai des missions, mais mon offre manque de clarté et je veux trouver des clients de manière plus régulière sans démarchage de masse.",
    ],
  },
  en: {
    heroLead: "What’s holding",
    heroEmphasis: "your business back",
    heroQuestionMark: "?",
    heroDescription: "Clarify your priorities and build a more profitable business that depends less on you.",
    situationLabel: "Describe what is happening in your business",
    createPlan: "Create my action plan",
    creatingPlan: "Creating your plan…",
    blankPlan: "Start with a blank plan",
    dictate: "Dictate my situation",
    stopDictation: "Stop dictation",
    savePlan: "Save your plan",
    close: "Close",
    expired: "Your request has expired. Please describe your situation again.",
    tooShort: "Describe your situation in a few sentences so the plan can be useful.",
    alreadyGenerating: "A plan is already being generated.",
    generationFailed: "Your plan could not be generated right now.",
    autoSaveFailed: "Automatic saving failed.",
    generationBar: {
      prompt: "What’s holding your business back?",
      stopDictation: "Stop dictation",
      dictate: "Dictate my request",
      generate: "Generate the plan",
      failed: "The plan could not be created.",
    },
    generationScreen: {
      status: "Generating your action plan",
      questions: [
        "If I stepped away for a month, would the business keep running?",
        "Which decisions still depend on me every time?",
        "Does my team know what to do without waiting for my instructions?",
        "What could I remove, simplify, delegate or automate?",
        "Does quality remain consistent when I am not directly supervising?",
      ],
    },
    generationState: {
      statusCheckFailed: "The generation status could not be checked.",
      restartFailed: "Generation could not restart.",
      inProgress: "Generation in progress",
      interrupted: "Generation interrupted",
      retrying: "Trying again…",
      retry: "Try again",
      newPlan: "New plan",
    },
    selector: {
      choose: "Choose a business type",
      searchPlaceholder: "Search business types…",
      searchLabel: "Search business types",
      listLabel: "Business types",
      empty: "No business type found.",
    },
    utility: {
      saving: "Saving…",
      retry: "Try again",
      menuLabel: "Plan actions",
      newPlan: "New plan",
    },
    navbar: {
      home: "Back to home",
      accountMenu: "Open account menu",
      myPlans: "My plans",
      signIn: "Sign in",
    },
    systemShare: {
      titlePrefix: "Business type",
      copiedLabel: "Business type link copied",
      shareLabel: "Share this business type",
      copiedTitle: "Link copied",
    },
    result: {
      filters: {
        week: "This week",
        all: "All actions",
        overdue: "Overdue",
        done: "Completed",
      },
      filterLabel: "Filter actions",
      statuses: {
        todo: "To do",
        in_progress: "In progress",
        done: "Completed",
      },
      moveTo: "Move to",
      action: "Action",
      actionTitle: "Action title",
      close: "Close",
      dueDate: "Due date",
      expectedResult: "Expected result",
      tasks: "Tasks",
      markTaskDone: (index: number) => `Mark task ${index} as completed`,
      taskLabel: (index: number) => `Task ${index}`,
      deleteTask: "Delete task",
      deleteTaskLabel: (index: number) => `Delete task ${index}`,
      supportTitle: "Support title",
      copy: "Copy",
      supportContent: "Support content",
      defaultSupportLabel: "Personal support",
      addSupport: "Add personal support",
      personalNotes: "Personal notes",
      notesPlaceholder: "Add a follow-up, decision or note…",
      deleteQuestion: "Delete this action?",
      cancel: "Cancel",
      delete: "Delete",
      deleteAction: "Delete action",
      planActions: "Plan actions",
      showKanban: "Show Kanban",
      showList: "Show list",
      noActions: "No actions",
      addAction: "Add an action",
    },
    savedPlan: {
      planName: "Plan name",
      planActions: "Plan actions",
      switchPlan: "Switch plan",
      opening: "Opening…",
      generating: "Generating",
      needsAttention: "Needs attention",
      updated: "Updated",
      source: "View original request",
      newPlan: "New plan",
      rename: "Rename",
      deleting: "Deleting…",
      delete: "Delete",
      deleteConfirmation: "Delete this plan? This action cannot be undone in the application.",
      saving: "Saving…",
      saved: "Changes saved",
      keepChanges: "Keep my changes",
      useLatest: "Use latest version",
      retry: "Try again",
      saveFailed: "Your changes could not be saved.",
      recentLoadFailed: "The latest version of the plan could not be loaded.",
      deleteFailed: "This plan could not be deleted.",
      planNotBlank: "This plan already contains information that must be kept.",
      saveBeforeGenerate: "Save the latest changes before generating the plan.",
      sessionExpired: "Your session has expired. Sign in again to save your changes.",
    },
    share: {
      title: "My Demaa action plan",
      thisWeek: "To do this week",
      copied: "Plan copied",
      sharePlan: "Share plan",
      share: "Share",
    },
    system: {
      loadFailed: "Unable to load this business type.",
      sectionLabel: "Business type",
      title: "Business solutions",
      savedSystems: "Saved business types",
      chooseTitle: "Choose your business type",
      chooseDescription: "Select your activity to see relevant tools and support.",
      loading: "Loading business solutions…",
      retry: "Try again",
    },
    examples: [
      "I run a six-person accounting firm. The work gets done, but every decision still comes back to me and deadlines are tracked across several files.",
      "My restaurant is busy at lunchtime, but margins are falling. Purchasing, staffing and waste are not tracked consistently.",
      "I run a plumbing business with four technicians. I want to organise jobs, quotes and follow-ups without adding a complicated tool.",
      "I am an independent consultant. I have client work, but my offer is unclear and I want a steadier way to find customers without mass outreach.",
    ],
  },
} as const;

export function getActionPlanUiCopy(localeCode: InterfaceLocaleCode) {
  return copy[localeCode];
}
