import type { InterfaceLocaleCode } from "@/lib/international-context";

const copy = {
  fr: {
    heroLead: "Qu’est-ce qui",
    heroEmphasis: "freine votre entreprise",
    heroQuestionMark: "\u00a0?",
    heroDescription: "On vous aide à clarifier les priorités, à structurer une activité plus rentable et moins dépendante de vous.",
    situationLabel: "Décrivez la situation de votre entreprise",
    createPlan: "Créer mon plan d’action",
    creatingPlan: "Création du plan…",
    blankPlan: "Commencer avec un plan vierge",
    dictate: "Dicter ma situation",
    stopDictation: "Arrêter la dictée",
    savePlan: "Enregistrez votre plan",
    close: "Fermer",
    expired: "Votre demande a expiré. Décrivez à nouveau votre situation.",
    tooShort: "Décrivez votre situation en quelques phrases pour obtenir un plan utile.",
    alreadyGenerating: "Une génération est déjà en cours.",
    generationFailed: "Impossible de générer le plan pour le moment.",
    autoSaveFailed: "La sauvegarde automatique a échoué.",
    savedPlan: {
      planName: "Nom du plan",
      planActions: "Actions du plan",
      switchPlan: "Changer de plan",
      opening: "Ouverture…",
      generating: "Génération en cours",
      needsAttention: "À reprendre",
      updated: "Modifié le",
      source: "Voir la demande initiale",
      newPlan: "Nouveau plan",
      rename: "Renommer",
      deleting: "Suppression…",
      delete: "Supprimer",
      deleteConfirmation: "Supprimer ce plan ? Cette action est définitive dans l’application.",
      saving: "Enregistrement…",
      saved: "Modifications enregistrées",
      keepChanges: "Garder mes modifications",
      useLatest: "Utiliser la version récente",
      retry: "Réessayer",
      saveFailed: "Impossible d’enregistrer les modifications.",
      recentLoadFailed: "Impossible de charger la version récente du plan.",
      deleteFailed: "Impossible de supprimer ce plan.",
      planNotBlank: "Ce plan contient déjà des informations à conserver.",
      saveBeforeGenerate: "Enregistrez les dernières modifications avant de générer le plan.",
      sessionExpired: "Votre session a expiré. Reconnectez-vous pour enregistrer vos modifications.",
    },
    share: {
      title: "Mon plan d’action Demaa",
      thisWeek: "À faire cette semaine",
      copied: "Plan copié",
      sharePlan: "Partager le plan",
      share: "Partager",
    },
    system: {
      loadFailed: "Impossible de charger ce système métier.",
      sectionLabel: "Système",
      title: "Solutions pour votre entreprise",
      savedSystems: "Systèmes enregistrés",
      chooseTitle: "Choisissez votre système métier",
      chooseDescription: "Sélectionnez votre activité parmi les 115 systèmes pour afficher ses solutions.",
      loading: "Chargement du système métier…",
      retry: "Réessayer",
    },
    examples: [
      "Je dirige un cabinet comptable de 6 personnes. Les dossiers avancent, mais tout remonte encore vers moi et les échéances sont suivies dans plusieurs fichiers.",
      "Mon restaurant fonctionne bien le midi, mais la marge baisse. Les achats, les plannings et les pertes ne sont pas suivis de façon régulière.",
      "Je développe une entreprise de plomberie avec 4 techniciens. Je veux mieux organiser les interventions, les devis et les relances sans ajouter un outil compliqué.",
      "Je suis consultante indépendante. J’ai des missions, mais mon offre manque de clarté et je veux trouver des clients de manière plus régulière sans démarchage de masse.",
    ],
  },
  en: {
    heroLead: "What’s holding",
    heroEmphasis: "your business back",
    heroQuestionMark: "?",
    heroDescription: "Clarify your priorities and build a more profitable business that depends less on you.",
    situationLabel: "Describe what is happening in your business",
    createPlan: "Create my action plan",
    creatingPlan: "Creating your plan…",
    blankPlan: "Start with a blank plan",
    dictate: "Dictate my situation",
    stopDictation: "Stop dictation",
    savePlan: "Save your plan",
    close: "Close",
    expired: "Your request has expired. Please describe your situation again.",
    tooShort: "Describe your situation in a few sentences so the plan can be useful.",
    alreadyGenerating: "A plan is already being generated.",
    generationFailed: "Your plan could not be generated right now.",
    autoSaveFailed: "Automatic saving failed.",
    savedPlan: {
      planName: "Plan name",
      planActions: "Plan actions",
      switchPlan: "Switch plan",
      opening: "Opening…",
      generating: "Generating",
      needsAttention: "Needs attention",
      updated: "Updated",
      source: "View original request",
      newPlan: "New plan",
      rename: "Rename",
      deleting: "Deleting…",
      delete: "Delete",
      deleteConfirmation: "Delete this plan? This action cannot be undone in the application.",
      saving: "Saving…",
      saved: "Changes saved",
      keepChanges: "Keep my changes",
      useLatest: "Use latest version",
      retry: "Try again",
      saveFailed: "Your changes could not be saved.",
      recentLoadFailed: "The latest version of the plan could not be loaded.",
      deleteFailed: "This plan could not be deleted.",
      planNotBlank: "This plan already contains information that must be kept.",
      saveBeforeGenerate: "Save the latest changes before generating the plan.",
      sessionExpired: "Your session has expired. Sign in again to save your changes.",
    },
    share: {
      title: "My Demaa action plan",
      thisWeek: "To do this week",
      copied: "Plan copied",
      sharePlan: "Share plan",
      share: "Share",
    },
    system: {
      loadFailed: "Unable to load this business type.",
      sectionLabel: "Business type",
      title: "Business solutions",
      savedSystems: "Saved business types",
      chooseTitle: "Choose your business type",
      chooseDescription: "Select your activity to see relevant tools and support.",
      loading: "Loading business solutions…",
      retry: "Try again",
    },
    examples: [
      "I run a six-person accounting firm. The work gets done, but every decision still comes back to me and deadlines are tracked across several files.",
      "My restaurant is busy at lunchtime, but margins are falling. Purchasing, staffing and waste are not tracked consistently.",
      "I run a plumbing business with four technicians. I want to organise jobs, quotes and follow-ups without adding a complicated tool.",
      "I am an independent consultant. I have client work, but my offer is unclear and I want a steadier way to find customers without mass outreach.",
    ],
  },
} as const;

export function getActionPlanUiCopy(localeCode: InterfaceLocaleCode) {
  return copy[localeCode];
}
