import {
  getDemaaAidBySlug,
  type DemaaAidItem,
} from "@/lib/aid-catalog";

const DEFAULT_AID_ORDER = [
  "acre",
  "arce",
  "aides-apprentissage",
  "transition-ecologique-entreprises",
] as const;

const AID_RECOMMENDATIONS_BY_SECTOR: Record<string, readonly string[]> = {
  "BTP & services techniques": [
    "mon-pass-crea",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "diagnostic-360-transition-ecologique",
    "adaptation-situation-travail-handicap",
  ],
  Restauration: [
    "mon-pass-crea",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "diagnostic-360-transition-ecologique",
    "plan-action-economies-energie",
    "reduction-emballages",
  ],
  "Santé, bien-être & esthétique": [
    "mon-pass-crea",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "diagnostic-360-transition-ecologique",
    "eclairage-led",
    "chauffe-eau-solaire",
  ],
  "Commerce & retail": [
    "mon-pass-crea",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "diagnostic-360-transition-ecologique",
    "plan-action-economies-energie",
    "reduction-emballages",
  ],
  "Services aux particuliers": [
    "mon-pass-crea",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "acquisition-voiture-propre",
    "adaptation-situation-travail-handicap",
    "transition-ecologique-entreprises",
  ],
  "Conseil & services aux entreprises": [
    "mon-pass-crea",
    "aides-apprentissage",
    "aide-accueil-integration-handicap",
    "aeth-travailleur-handicape",
    "acre",
    "arce",
    "transition-ecologique-entreprises",
  ],
  "Tech & Digital": [
    "jei",
    "jec",
    "jeu",
    "cir",
    "cii",
    "cifre",
    "jeii",
  ],
  Immobilier: [
    "diagnostic-360-transition-ecologique",
    "plan-action-economies-energie",
    "isolation-thermique",
    "panneaux-solaires",
    "acre",
    "arce",
    "transition-ecologique-entreprises",
    "aides-apprentissage",
  ],
  Patrimoine: [
    "diagnostic-360-transition-ecologique",
    "acre",
    "arce",
    "transition-ecologique-entreprises",
    "aides-apprentissage",
  ],
  "Mobilité & logistique": [
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "acquisition-voiture-propre",
    "diagnostic-360-transition-ecologique",
    "adaptation-situation-travail-handicap",
  ],
  "Industrie & production": [
    "jei",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "diagnostic-360-transition-ecologique",
    "adaptation-situation-travail-handicap",
    "cir",
    "cii",
  ],
  "Hébergement & tourisme": [
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "acquisition-voiture-propre",
    "diagnostic-360-transition-ecologique",
    "reduction-emballages",
    "chauffe-eau-solaire",
  ],
  "Éducation & formation": [
    "jeii",
    "jeu",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "acre",
    "arce",
    "transition-ecologique-entreprises",
  ],
  "Associations & événements": [
    "jeii",
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "transition-ecologique-entreprises",
    "acre",
    "arce",
  ],
  "Automobile & réparation": [
    "aides-apprentissage",
    "apprentissage-handicap",
    "aide-accueil-integration-handicap",
    "acquisition-voiture-propre",
    "aeth-travailleur-handicape",
    "transition-ecologique-entreprises",
  ],
};

const AID_RECOMMENDATIONS_BY_SYSTEM: Record<string, readonly string[]> = {
  batiment: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  restaurant: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "reduction-emballages"],
  boulangerie: ["diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages", "isolation-thermique", "eclairage-led", "panneaux-solaires"],
  traiteur: ["diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages", "chauffe-eau-solaire", "transition-ecologique-entreprises", "acre"],
  "institut-de-beaute": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "eclairage-led", "chauffe-eau-solaire"],
  "salon-de-coiffure": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "eclairage-led", "chauffe-eau-solaire"],
  "commerce-de-detail": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages"],
  "boutique-specialisee": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages"],
  librairie: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages"],
  "tabac-presse-point-relais": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages"],
  "investissement-immobilier": ["diagnostic-360-transition-ecologique", "isolation-thermique", "panneaux-solaires", "plan-action-economies-energie", "bilan-ges", "transition-ecologique-entreprises"],
  "investissement-financier": ["mon-pass-crea", "transition-ecologique-entreprises", "aides-apprentissage", "acre", "arce", "diagnostic-360-transition-ecologique"],
  "investissement-entreprise": ["mon-pass-crea", "transition-ecologique-entreprises", "aides-apprentissage", "acre", "arce", "diagnostic-360-transition-ecologique"],
  "gestionnaire-de-patrimoine": ["mon-pass-crea", "transition-ecologique-entreprises", "aides-apprentissage", "aide-accueil-integration-handicap", "acre", "arce"],
  "hotel-hebergement-independant": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "chauffe-eau-solaire", "reduction-emballages"],
  "conciergerie-airbnb": ["aides-apprentissage", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "diagnostic-360-transition-ecologique", "chauffe-eau-solaire", "reduction-emballages"],
  "agence-de-voyage": ["aides-apprentissage", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "diagnostic-360-transition-ecologique", "transition-ecologique-entreprises", "acre"],
  "production-industrie": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique", "aeth-travailleur-handicape"],
  "commerce-alimentaire": ["diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages", "aides-apprentissage", "transition-ecologique-entreprises", "acre"],
  "food-truck": ["diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages", "aides-apprentissage", "transition-ecologique-entreprises", "acre"],
  "fast-food": ["diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages", "aides-apprentissage", "transition-ecologique-entreprises", "acre"],
  "dark-kitchen": ["diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages", "aides-apprentissage", "transition-ecologique-entreprises", "acre"],
  "bar-cafe": ["diagnostic-360-transition-ecologique", "plan-action-economies-energie", "reduction-emballages", "aides-apprentissage", "transition-ecologique-entreprises", "acre"],
  "e-commerce": ["reduction-emballages", "diagnostic-360-transition-ecologique", "bilan-ges", "transition-ecologique-entreprises", "aides-apprentissage", "acre"],
  "services-a-la-personne": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape"],
  "aide-a-domicile-menage": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape"],
  pressing: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "transition-ecologique-entreprises"],
  "laverie-automatique": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "transition-ecologique-entreprises"],
  demenagement: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape"],
  "transport-de-marchandise": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape"],
  "transport-de-personnes": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape"],
  "livraison-dernier-kilometre": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape"],
  vtc: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape"],
  "garage-automobile": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape", "transition-ecologique-entreprises"],
  carrosserie: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "aeth-travailleur-handicape", "transition-ecologique-entreprises"],
  "cabinet-davocat": ["acre", "arce", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape"],
  "cabinet-comptable": ["mon-pass-crea", "aides-apprentissage", "transition-ecologique-entreprises", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "cir"],
  "cabinet-de-conseil": ["jei", "jec", "jeu", "cir", "cii", "cifre"],
  "agence-de-recrutement": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "mon-pass-crea"],
  "courtier-credit-assurance": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  evenementiel: ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "transition-ecologique-entreprises", "acre"],
  notaire: ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "acre"],
  fleuriste: ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "reduction-emballages", "transition-ecologique-entreprises"],
  "cabinet-assurance": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "acre"],
  "coach-professionnel": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "entreprise-de-securite": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  "daf-externalise": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "cir", "cii"],
  "office-manager-externalise": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "assistant-administratif-externalise": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "secretariat-externalise": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "gestionnaire-paie-independant": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "cabinet-rh-externalise": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "mon-pass-crea"],
  "centre-appels-support-client": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "mon-pass-crea"],
  "societe-recouvrement": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "centre-affaires-coworking": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "cabinet-qhse-conformite": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "cir", "cii"],
  "bureau-etudes": ["jei", "jeu", "cir", "cii", "cifre", "aides-apprentissage"],
  "cabinet-etudes": ["jei", "cir", "cii", "aides-apprentissage", "aide-accueil-integration-handicap", "cifre"],
  "studio-branding-design": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "agence-marketing": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "acre"],
  "agence-seo": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "acre"],
  "agence-acquisition-paid-ads": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "acre"],
  freelance: ["mon-pass-crea", "acre", "arce", "aides-apprentissage"],
  "consultant-independant": ["mon-pass-crea", "acre", "arce", "aides-apprentissage"],
  "agence-immobiliere": ["mon-pass-crea", "diagnostic-360-transition-ecologique", "isolation-thermique", "panneaux-solaires", "plan-action-economies-energie", "bilan-ges"],
  saas: ["jei", "jec", "jeu", "cir", "cii", "cifre"],
  "cybersecurite-pme": ["jei", "jec", "jeu", "cir", "cii", "cifre"],
  "consultant-data-bi": ["jei", "jec", "jeu", "cir", "cii", "cifre"],
  "agence-web": ["jei", "jec", "jeu", "cir", "cii", "cifre"],
  "creation-de-contenu": ["mon-pass-crea", "acre", "arce", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises"],
  media: ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "cir", "cii"],
  "photographe-videaste": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "transition-ecologique-entreprises", "acre"],
  "reparation-informatique-mobile": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "transition-ecologique-entreprises", "acre"],
  "infogerance-informatique": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "aeth-travailleur-handicape", "cir", "cii"],
  "integrateur-crm-erp": ["jei", "cir", "cii", "aides-apprentissage", "aide-accueil-integration-handicap", "cifre"],
  marketplace: ["jei", "jec", "cir", "cii", "cifre", "acre"],
  "investissement-locatif": ["diagnostic-360-transition-ecologique", "isolation-thermique", "panneaux-solaires", "plan-action-economies-energie", "bilan-ges", "transition-ecologique-entreprises"],
  "marchand-de-biens": ["diagnostic-360-transition-ecologique", "isolation-thermique", "panneaux-solaires", "plan-action-economies-energie", "bilan-ges", "transition-ecologique-entreprises"],
  "gestion-locative": ["mon-pass-crea", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "isolation-thermique", "bilan-ges", "aides-apprentissage"],
  syndic: ["mon-pass-crea", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "isolation-thermique", "bilan-ges", "aides-apprentissage"],
  "diagnostiqueur-immobilier": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "transition-ecologique-entreprises", "acre"],
  "chasseur-immobilier": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "cabinet-medical": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  "cabinet-paramedical": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  "infirmier-liberal": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "transition-ecologique-entreprises", "acre"],
  dentiste: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  pharmacie: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  veterinaire: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  osteopathe: ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  psychologue: ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre", "arce"],
  "salle-de-sport": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "eclairage-led", "chauffe-eau-solaire"],
  "coach-sportif": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "eclairage-led", "acre"],
  opticien: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "plan-action-economies-energie", "transition-ecologique-entreprises"],
  esthetique: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "eclairage-led", "chauffe-eau-solaire"],
  "auto-ecole": ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  cfa: ["aides-apprentissage", "jeu", "jeii", "apprentissage-handicap", "aide-accueil-integration-handicap", "transition-ecologique-entreprises"],
  creche: ["aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "transition-ecologique-entreprises", "aeth-travailleur-handicape"],
  "formation-en-ligne": ["jeii", "jeu", "aides-apprentissage", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre"],
  association: ["jeii", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "transition-ecologique-entreprises", "acre"],
  "organisme-de-formation": ["jeii", "jeu", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "transition-ecologique-entreprises"],
  "nettoyage-professionnel": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  "plomberie-chauffage": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  "electricite-generale": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  "renovation-interieur": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  "menuiserie-agencement": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  "maconnerie-gros-oeuvre": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  paysagiste: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "transition-ecologique-entreprises"],
  "architecte-maitre-oeuvre": ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "transition-ecologique-entreprises", "acre"],
  pisciniste: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "diagnostic-360-transition-ecologique", "transition-ecologique-entreprises"],
  couvreur: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  "peintre-en-batiment": ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  carreleur: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  climatisation: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  serrurier: ["mon-pass-crea", "aides-apprentissage", "apprentissage-handicap", "aide-accueil-integration-handicap", "adaptation-situation-travail-handicap", "diagnostic-360-transition-ecologique"],
  geometre: ["mon-pass-crea", "aides-apprentissage", "aide-accueil-integration-handicap", "acquisition-voiture-propre", "transition-ecologique-entreprises", "acre"],
};

export function getRecommendedAidsForSystem(systemSlug: string, sectorLabel?: string): DemaaAidItem[] {
  const aidSlugs = AID_RECOMMENDATIONS_BY_SYSTEM[systemSlug]
    ?? (sectorLabel ? AID_RECOMMENDATIONS_BY_SECTOR[sectorLabel] : undefined)
    ?? DEFAULT_AID_ORDER;

  return Array.from(new Set(aidSlugs))
    .map((slug) => getDemaaAidBySlug(slug))
    .filter((item): item is DemaaAidItem => Boolean(item))
    .slice(0, 6);
}

export function splitAidRecommendationsForDisplay(items: DemaaAidItem[]): {
  recommended: DemaaAidItem[];
  secondary: DemaaAidItem[];
} {
  const recommended = items
    .filter(
      (item, index, list) =>
        list.findIndex((candidate) => candidate.family === item.family) === index,
    )
    .slice(0, 3);
  const recommendedSlugs = new Set(recommended.map((item) => item.slug));

  return {
    recommended,
    secondary: items.filter((item) => !recommendedSlugs.has(item.slug)),
  };
}
