import type { BusinessModelBlock } from "@/lib/business-models";

export type BusinessBlockChecklist = {
  title: string;
  checklist: string[];
};

const TERM_ACTIONS: Array<[RegExp, string[]]> = [
  [/demande|prospect|client|admission|inscription|rendez-vous|réservation/i, [
    "Qualifier la demande entrante",
    "Vérifier besoin, urgence, lieu et contraintes",
    "Confirmer la prochaine étape avec le client",
  ]],
  [/devis|chiffrage|tarif|prix|estimation/i, [
    "Chiffrer le besoin avec les bons coûts",
    "Faire valider le devis ou l'accord client",
    "Relancer les dossiers ouverts",
  ]],
  [/chantier|travaux|intervention|terrain|pose|réparation|atelier/i, [
    "Planifier les interventions",
    "Suivre l'avancement réel",
    "Tracer photos, décisions et points bloquants",
  ]],
  [/planning|session|cours|tournée|trajet|leçon|agenda|créneau/i, [
    "Bloquer les dates et ressources nécessaires",
    "Confirmer les disponibilités",
    "Mettre à jour le planning en cas d'imprévu",
  ]],
  [/matériau|stock|fournisseur|pièce|produit|réassort|commande/i, [
    "Lister les besoins à commander",
    "Vérifier disponibilité, prix et délais",
    "Rattacher les achats au bon dossier",
  ]],
  [/qualité|conformité|réserve|réception|preuve|qualiopi|haccp|hygiène|sécurité|traçabilité|confidentialité/i, [
    "Vérifier les points obligatoires",
    "Traiter les écarts ou réserves",
    "Archiver les preuves utiles",
  ]],
  [/facturation|paiement|caisse|marge|rentabilité|honoraire|commission|budget|trésorerie|encaissement|loyer|opco/i, [
    "Suivre ce qui est signé, facturé et encaissé",
    "Comparer le prévu avec le réel",
    "Relancer les montants en attente",
  ]],
  [/équipe|intervenant|sous-traitant|prestataire|chauffeur|agent|moniteur|coach|praticien|bénévole|extra/i, [
    "Attribuer les responsabilités",
    "Partager consignes, accès et priorités",
    "Suivre charge, absences et remplacements",
  ]],
  [/dossier|pièce|document|mandat|contrat|convention|acte|bail/i, [
    "Collecter les pièces nécessaires",
    "Vérifier les informations manquantes",
    "Classer la version utile",
  ]],
  [/suivi|accompagnement|relation|satisfaction|avis|sav|incident|litige|retour/i, [
    "Suivre les points ouverts",
    "Informer le client au bon moment",
    "Clôturer avec une trace claire",
  ]],
  [/offre|carte|catalogue|gamme|programme|prestation|produit|positionnement|spécialité/i, [
    "Clarifier ce qui est vendu",
    "Mettre à jour prix, conditions et limites",
    "Identifier les offres à pousser ou arrêter",
  ]],
  [/visibilité|acquisition|fidélisation|conversion|vitrine|événement|communauté/i, [
    "Identifier les canaux qui apportent des demandes",
    "Suivre les contacts à relancer",
    "Mesurer les demandes transformées",
  ]],
];

const FALLBACK_ACTIONS = [
  "Décrire le point métier à clarifier",
  "Identifier la prochaine action utile",
  "Attribuer un responsable",
  "Suivre les points ouverts",
  "Garder une trace exploitable",
];

const CONTEXTUAL_ACTIONS: Array<[RegExp, string[]]> = [
  [/commandes & préparation/i, [
    "Suivre commandes payées, à préparer et à expédier",
    "Contrôler stock, picking, emballage et transporteur",
    "Repérer retards, erreurs ou commandes à risque",
    "Informer le client en cas de problème",
    "Mettre à jour statut, facture et suivi colis",
  ]],
  [/événements & visibilité|préparation embarquée|autorisations & hygiène/i, [
    "Planifier emplacements, événements et autorisations",
    "Préparer stock embarqué, matériel et mise en place",
    "Adapter carte et quantités selon météo ou affluence",
    "Contrôler hygiène, caisse et contraintes du site",
    "Mesurer CA par emplacement et pertes",
  ]],
  [/demandes & réservations|expérience client/i, [
    "Qualifier course, horaire, lieu de prise en charge et destination",
    "Confirmer prix, véhicule et contraintes passager",
    "Suivre ponctualité, attente et qualité de trajet",
    "Gérer modification, annulation ou incident",
    "Mesurer note client, récurrence et marge course",
  ]],
  [/produits & portefeuilles/i, [
    "Cartographier contrats, garanties et échéances client",
    "Identifier besoins de couverture ou doublons",
    "Comparer offres, exclusions et niveaux de prime",
    "Préparer arbitrages, avenants ou renouvellements",
    "Suivre portefeuille, sinistres et commissions",
  ]],
  [/suivi client|jours vendus & trésorerie/i, [
    "Suivre avancement mission, décisions et prochaines étapes",
    "Centraliser retours, validations et points bloquants",
    "Anticiper dépassement de périmètre ou charge non vendue",
    "Facturer jalons, jours vendus ou acompte prévu",
    "Mettre à jour pipeline, trésorerie et reste à produire",
  ]],
  [/demandes & étude terrain/i, [
    "Qualifier projet, terrain, accès et contraintes techniques",
    "Collecter photos, dimensions et attentes client",
    "Planifier étude ou visite sur place",
    "Identifier équipements, options et points de vigilance",
    "Préparer devis et planning chantier",
  ]],
  [/mise en service/i, [
    "Préparer contrôles, réglages et consignes client",
    "Tester fonctionnement, sécurité et équipements",
    "Corriger anomalies avant livraison finale",
    "Former le client à l'usage et l'entretien",
    "Archiver preuve, garantie et prochaine maintenance",
  ]],
  [/projets client & devis/i, [
    "Qualifier pièces, usages, budget et contraintes client",
    "Collecter photos, plans, mesures et choix attendus",
    "Planifier visite ou échange de cadrage",
    "Chiffrer lots, matériaux, délais et marge",
    "Envoyer devis puis relancer les décisions client",
  ]],
  [/achats & corps d’état/i, [
    "Lister lots, fournitures et corps d'état concernés",
    "Vérifier devis fournisseurs, délais et dépendances",
    "Commander au bon moment selon planning chantier",
    "Suivre livraisons, ruptures et arbitrages client",
    "Rattacher coûts au chantier et à la marge prévue",
  ]],
  [/prospects? & devis|prospects? & missions|prospects? & diagnostics|prospects? & rendez-vous/i, [
    "Qualifier besoin, contexte, budget et décideur",
    "Cadrer périmètre, objectifs et critères de succès",
    "Préparer devis, proposition ou diagnostic adapté",
    "Confirmer prochaines étapes et conditions",
    "Relancer les opportunités ouvertes",
  ]],
  [/carte & offres|menu & formules|offres & abonnements|offres & forfaits|offres & style|prestations & tarifs/i, [
    "Clarifier offres, tarifs et conditions de vente",
    "Mettre à jour formules, options ou abonnements",
    "Identifier ce qui se vend, se marge ou se remplit le mieux",
    "Préparer supports, carte ou argumentaire client",
    "Décider quoi pousser, simplifier ou arrêter",
  ]],
  [/acquisition & conversion|acquisition & rétention/i, [
    "Suivre sources de trafic, leads et conversions",
    "Identifier canaux, offres ou segments rentables",
    "Mesurer activation, panier, réachat ou rétention",
    "Relancer prospects, clients ou comptes à potentiel",
    "Tester messages, parcours et offres",
  ]],
  [/stock & logistique|commandes & logistique|stock & réassort|stocks & réassort|stocks & composants|stocks? frais & dlc/i, [
    "Contrôler niveaux de stock, ruptures et priorités",
    "Planifier réassort, préparation ou expédition",
    "Suivre livraisons, retours et écarts",
    "Repérer produits dormants, pertes ou DLC courtes",
    "Ajuster achats selon ventes et marge",
  ]],
  [/planning production|atelier & machines|qualité & rebuts|commandes clients & prévisions/i, [
    "Suivre commandes, capacités et priorités atelier",
    "Planifier production, postes et machines critiques",
    "Contrôler composants, rebuts et non-conformités",
    "Mesurer délais, taux de service et stock critique",
    "Ajuster charge, achats et marge série",
  ]],
  [/choix client & devis|métrés & chiffrage|plans & devis|calepinage & devis|devis & matériel|devis & équipements|diagnostic & devis|expertise & devis/i, [
    "Préciser besoin, mesures, options et contraintes techniques",
    "Chiffrer main-d'oeuvre, fournitures, délais et marge",
    "Valider choix client ou faisabilité avant engagement",
    "Envoyer devis clair avec limites et conditions",
    "Relancer puis préparer achat ou intervention signée",
  ]],
  [/fabrication & achats|préparation support|peinture & restitution|postproduction & livraison|rapports & livraison|réparation & restitution/i, [
    "Préparer éléments, matériel ou fichiers nécessaires",
    "Suivre production, contrôle et corrections",
    "Traiter retours, reprises ou ajustements",
    "Valider qualité avant restitution",
    "Archiver version finale, preuve ou garantie",
  ]],
  [/demande?s? & dossiers clients|entrée dossier client|demandes & missions|ordre de mission|mandats de recherche/i, [
    "Qualifier demande, objectif et contraintes du dossier",
    "Collecter pièces, accès et informations obligatoires",
    "Vérifier faisabilité, délais et points de vigilance",
    "Confirmer périmètre, prix et prochaine étape",
    "Créer le dossier avec les manquants visibles",
  ]],
  [/offre & montures|offre & spécialités|offres & compositions|sélection & positionnement|offres & destinations/i, [
    "Clarifier gamme, spécialités et attentes client",
    "Mettre à jour prix, options et disponibilités",
    "Identifier références ou offres prioritaires",
    "Préparer conseil, démonstration ou proposition",
    "Mesurer ventes, retours et satisfaction",
  ]],
  [/produit & client cible/i, [
    "Définir l'ICP et les segments prioritaires",
    "Clarifier le problème utilisateur à résoudre",
    "Identifier les cas d'usage qui déclenchent l'achat",
    "Comparer positionnement, pricing et alternatives",
    "Valider la promesse avec retours clients ou démos",
  ]],
  [/acquisition & activation/i, [
    "Suivre visiteurs, signups et comptes activés",
    "Identifier les canaux qui créent des utilisateurs qualifiés",
    "Mesurer activation, time-to-value et abandon onboarding",
    "Relancer les leads ou comptes bloqués",
    "Tester messages, offres et parcours de conversion",
  ]],
  [/feuille de route & production/i, [
    "Prioriser bugs, demandes clients et paris produit",
    "Découper les sujets en specs, tickets et releases",
    "Suivre avancement design, dev, QA et mise en production",
    "Valider les impacts avant release",
    "Communiquer les nouveautés aux clients concernés",
  ]],
  [/usage & rétention/i, [
    "Suivre activation, usage, rétention et churn",
    "Repérer comptes à risque ou fonctionnalités peu utilisées",
    "Analyser feedback, tickets et données produit",
    "Déclencher actions d'adoption ou d'expansion",
    "Documenter les apprentissages produit",
  ]],
  [/mrr & rentabilité client|revenus & métriques/i, [
    "Suivre MRR, ARR, churn et expansion",
    "Comparer CAC, panier moyen et marge par compte",
    "Repérer échecs de paiement et abonnements à risque",
    "Analyser rentabilité par plan ou segment client",
    "Mettre à jour prévisionnel et runway",
  ]],
  [/équipe & produit/i, [
    "Clarifier ownership produit, tech, support et sales",
    "Prioriser les sujets critiques de la semaine",
    "Suivre charge dev, support et dette technique",
    "Partager décisions, incidents et retours clients",
    "Aligner l'équipe sur roadmap et métriques clés",
  ]],
  [/offres? & lettres de mission|domaines & positionnement/i, [
    "Clarifier expertises, missions et clients servis",
    "Mettre à jour honoraires, forfaits ou modalités",
    "Cadrer ce qui entre ou sort de la mission",
    "Préparer modèles de lettre, convention ou mandat",
    "Identifier les dossiers à développer ou refuser",
  ]],
  [/entrée client & pièces|entrée client & convention/i, [
    "Qualifier le besoin, le contexte et le niveau d'urgence",
    "Collecter mandat, pièces et accès nécessaires",
    "Vérifier conflit, faisabilité ou obligations préalables",
    "Confirmer périmètre, honoraires et prochaine étape",
    "Créer le dossier avec les informations manquantes visibles",
  ]],
  [/production comptable/i, [
    "Collecter les pièces comptables attendues",
    "Pointer banques, achats, ventes et justificatifs",
    "Traiter anomalies, questions client et pièces manquantes",
    "Préparer révision, TVA ou situation",
    "Classer les éléments validés pour l'échéance",
  ]],
  [/paie & déclarations/i, [
    "Collecter variables de paie et absences",
    "Contrôler bulletins, DSN et échéances sociales",
    "Faire valider les éléments sensibles",
    "Envoyer bulletins et déclarations",
    "Archiver justificatifs et retours client",
  ]],
  [/procédure & audiences/i, [
    "Suivre échéances de procédure et audiences",
    "Préparer conclusions, pièces et bordereaux",
    "Contrôler délais imposés et actes à signifier",
    "Informer le client des étapes clés",
    "Archiver décisions, échanges et prochaines actions",
  ]],
  [/rédaction & production/i, [
    "Lister actes, courriers ou notes à produire",
    "Rassembler pièces, jurisprudence ou éléments utiles",
    "Faire relire les versions sensibles",
    "Envoyer au bon interlocuteur dans les délais",
    "Classer la version déposée ou transmise",
  ]],
  [/prospects & propositions|prospects & comptes clients/i, [
    "Qualifier besoin, budget, décideurs et échéance",
    "Vérifier contexte, objectifs et critères de choix",
    "Proposer le bon format d'accompagnement",
    "Envoyer proposition ou devis cadré",
    "Relancer les opportunités ouvertes",
  ]],
  [/briefs? & campagnes|création & validations/i, [
    "Clarifier objectif, cible, message et canal",
    "Préparer contenus, assets et calendrier de validation",
    "Suivre production, retours client et corrections",
    "Contrôler tracking, budget et dates de diffusion",
    "Archiver versions validées et résultats",
  ]],
  [/reporting & performance|audience & engagement/i, [
    "Suivre KPI, budget, leads ou audience",
    "Comparer résultats aux objectifs de campagne",
    "Identifier contenus, canaux ou audiences à ajuster",
    "Préparer synthèse claire pour le client ou l'équipe",
    "Décider les optimisations du prochain cycle",
  ]],
  [/ligne éditoriale|production contenu|production éditoriale/i, [
    "Définir angles, formats et calendrier éditorial",
    "Préparer scripts, visuels, sources ou interviews",
    "Suivre production, validation et publication",
    "Contrôler qualité, droits et cohérence de ton",
    "Analyser performance et idées à recycler",
  ]],
  [/planning & diffusion|diffusion & communauté/i, [
    "Planifier publications par canal et format",
    "Programmer contenus, newsletters ou épisodes",
    "Suivre commentaires, réponses et interactions utiles",
    "Mesurer portée, engagement et conversions",
    "Ajuster calendrier selon les meilleurs résultats",
  ]],
  [/offre & modèle commission/i, [
    "Clarifier catégories, commission et règles vendeurs",
    "Définir conditions d'entrée et qualité attendue",
    "Vérifier cohérence entre offre, prix et take rate",
    "Identifier segments vendeurs ou acheteurs prioritaires",
    "Documenter règles de litige, paiement et support",
  ]],
  [/vendeurs & acquisition/i, [
    "Identifier les vendeurs ou partenaires à onboarder",
    "Qualifier catalogue, volume et fiabilité",
    "Suivre onboarding, activation et premières ventes",
    "Relancer les comptes vendeurs à potentiel",
    "Mesurer contribution au volume d'affaires",
  ]],
  [/catalogue & transactions/i, [
    "Contrôler qualité des fiches, prix et disponibilités",
    "Suivre commandes, paiements et statuts",
    "Repérer anomalies de catalogue ou de transaction",
    "Traiter annulations, remboursements et litiges",
    "Améliorer les parcours qui bloquent la conversion",
  ]],
  [/litiges & confiance/i, [
    "Centraliser litiges acheteurs et vendeurs",
    "Qualifier impact, responsabilité et urgence",
    "Appliquer règles de remboursement ou médiation",
    "Informer les parties jusqu'à résolution",
    "Repérer les causes récurrentes à corriger",
  ]],
  [/catalogue & offres|commandes & logistique|sav & avis clients/i, [
    "Mettre à jour fiches produits, prix et disponibilités",
    "Suivre commandes, préparation et expédition",
    "Traiter retours, remboursements et tickets SAV",
    "Identifier ruptures, produits dormants ou marges faibles",
    "Mesurer conversion, panier moyen et satisfaction",
  ]],
  [/mandats & estimations|positionnement & mandats/i, [
    "Qualifier vendeur, bien, prix attendu et motivation",
    "Préparer estimation avec comparables et arguments",
    "Valider mandat, honoraires et pièces obligatoires",
    "Planifier diffusion, visites et relances",
    "Suivre biens sans action récente",
  ]],
  [/biens & diffusion/i, [
    "Préparer annonce, photos, diagnostics et prix",
    "Publier sur les bons portails et supports",
    "Suivre demandes acquéreurs et qualité des leads",
    "Mettre à jour statut, baisses de prix ou disponibilité",
    "Mesurer visites générées par chaque canal",
  ]],
  [/offres & compromis/i, [
    "Centraliser offres, contre-offres et conditions",
    "Vérifier financement, pièces et délais",
    "Coordonner vendeur, acquéreur et notaire",
    "Suivre compromis, conditions suspensives et signature",
    "Relancer les étapes bloquantes",
  ]],
  [/réservations & remplissage|visibilité & commandes|commandes & flux/i, [
    "Suivre réservations, commandes ou passages attendus",
    "Identifier créneaux creux, pics et canaux rentables",
    "Mettre à jour carte, horaires et disponibilités",
    "Relancer groupes, habitués ou demandes en attente",
    "Mesurer remplissage, panier moyen et no-show",
  ]],
  [/hygiène haccp|hygiène & standards|hygiène & conformité|hygiène & notes/i, [
    "Contrôler températures, DLC et nettoyage",
    "Vérifier traçabilité, allergènes et fiches HACCP",
    "Repérer écarts avant contrôle ou service",
    "Former l'équipe aux gestes obligatoires",
    "Archiver relevés et actions correctives",
  ]],
  [/caisse & marge|caisse & coût matière|commissions & marge|marge événement/i, [
    "Suivre chiffre d'affaires, encaissements et écarts",
    "Comparer coût matière, pertes et marge réelle",
    "Repérer remises, commissions ou invendus coûteux",
    "Rapprocher caisse, plateformes et factures",
    "Ajuster prix, portions ou achats",
  ]],
  [/offres & prestations|prestations & forfaits|offres & programmes/i, [
    "Clarifier prestations, durées et contre-indications",
    "Mettre à jour tarifs, forfaits et abonnements",
    "Identifier prestations rentables ou à retirer",
    "Préparer protocoles, produits et recommandations",
    "Suivre réachat, fidélité et satisfaction",
  ]],
  [/visibilité & réservations|réservations & fidélisation/i, [
    "Suivre demandes, rendez-vous confirmés et no-show",
    "Remplir les créneaux creux avec relances ciblées",
    "Identifier clientes fidèles, retours et réachats",
    "Mettre à jour offres, disponibilités et rappels",
    "Mesurer taux de remplissage et panier moyen",
  ]],
  [/hygiène & qualité/i, [
    "Contrôler protocoles, nettoyage et consommables",
    "Vérifier consentements ou précautions nécessaires",
    "Repérer incidents, réactions ou réclamations",
    "Planifier corrections et rappels équipe",
    "Conserver les preuves utiles",
  ]],
  [/caisse & rentabilité/i, [
    "Suivre CA par prestation, produit et praticienne",
    "Comparer taux de remplissage, no-show et marge",
    "Repérer impayés, remises et forfaits consommés",
    "Analyser revente produit et réachat",
    "Ajuster planning, prix ou offres",
  ]],
  [/facturation & pilotage|honoraires & rentabilité|honoraires & temps|marge & facturation|revenus & marge|honoraires & succès/i, [
    "Suivre honoraires, forfaits ou factures à émettre",
    "Comparer temps passé, budget et rentabilité",
    "Repérer retards de facturation ou impayés",
    "Relancer clients ou financeurs concernés",
    "Mettre à jour prévisionnel et reste à facturer",
  ]],
  [/équipe & dossiers|équipe & collaborateurs|équipe & consultants|équipe & affectations|équipe & freelances/i, [
    "Affecter dossiers, missions ou comptes clients",
    "Rendre visible charge, priorités et blocages",
    "Partager consignes, accès et échéances",
    "Suivre capacité interne et renforts nécessaires",
    "Clarifier validation et arbitrage en cas de conflit",
  ]],
  [/^équipe &|chauffeurs &|moniteurs &|prestataires &|bénévoles &|créateurs &|partenaires &|réseau &|remplacements &|clercs|conseillers|praticiens|libraires|coiffeurs|opticiens|techniciens/i, [
    "Clarifier rôles, planning et dossiers suivis",
    "Partager consignes, accès et priorités du moment",
    "Rendre visibles charge, disponibilités et blocages",
    "Anticiper renforts, remplacements ou compétences clés",
    "Suivre décisions, transmissions et points à arbitrer",
  ]],
  [/marge|rentabilité|facturation|honoraires|commissions|revenus|budget|budgets|paiements|caisse|loyers|encaissements|coût par livraison|coûts & marge|primes & commissions|énergie & rentabilité|émoluments & débours/i, [
    "Suivre montants engagés, facturés et encaissés",
    "Comparer coûts réels, marge et prévisionnel",
    "Repérer impayés, écarts ou dossiers non facturés",
    "Relancer clients, financeurs ou partenaires concernés",
    "Mettre à jour pilotage et décisions de prix",
  ]],
  [/qualité|conformité|confidentialité|agrément|normes|sécurité|traçabilité|règles|documents & conformité|cadre & conformité|bornage & conformité|cmr & conformité|conformité vtc|conformité courtage|conformité distribution|pharmacie & conformité/i, [
    "Lister obligations, preuves et points de contrôle",
    "Vérifier dossiers, autorisations ou documents sensibles",
    "Repérer écarts, risques ou pièces manquantes",
    "Planifier corrections et validations nécessaires",
    "Archiver les preuves au bon endroit",
  ]],
  [/stocks?|stock|fournisseurs|réassort|matières|matériaux|matériel|pièces|fleurs & arrivages|végétaux & fournitures|couleurs & fournitures|commandes fournisseurs|commandes éditeurs|stock & grossistes|stock & logistique|stocks boissons|stocks frais & dlc/i, [
    "Lister références, quantités et besoins prioritaires",
    "Contrôler niveaux, ruptures, délais et contraintes qualité",
    "Commander ou réserver au bon moment",
    "Suivre livraisons, écarts, retours ou pertes",
    "Rattacher les achats au dossier, rayon ou service concerné",
  ]],
  [/demandes? .*devis|demandes? chantier|urgences?, demandes & devis|dépannages?, demandes & devis|accueil & devis|rendez-vous & devis|visites & devis/i, [
    "Qualifier besoin, urgence et faisabilité",
    "Récupérer photos, mesures, plans ou informations clés",
    "Planifier visite, diagnostic ou échange de cadrage",
    "Chiffrer coûts, marge et conditions",
    "Envoyer puis relancer les devis ouverts",
  ]],
  [/suivi terrain|avancement travaux|chantier & finitions|pose & finitions|pose & réception|interventions terrain|préparation chantier|suivi chantier|travaux & planning/i, [
    "Préparer accès, matériel et consignes chantier",
    "Suivre avancement réel, photos et points bloquants",
    "Coordonner client, équipe et sous-traitants",
    "Traiter reprises, imprévus ou décisions en attente",
    "Mettre à jour planning et reste à facturer",
  ]],
  [/réception|réserves|reprises|finitions|qualité & sav|garantie & sav|garanties & sav|sav & entretien|sav & retours|restitution & sav/i, [
    "Contrôler résultat livré et points sensibles",
    "Lister réserves, reprises ou garanties ouvertes",
    "Planifier correction avec responsable et délai",
    "Informer client ou partie prenante de la suite",
    "Clôturer avec preuve, photo ou compte rendu",
  ]],
  [/tournées|trajets|livraisons|chargement|intervention & livraison|courses & planning|planning flotte|planning camions|planning trajets|véhicules & sécurité|véhicule & entretien/i, [
    "Planifier tournées, véhicules et conducteurs",
    "Vérifier documents, chargement et contraintes horaires",
    "Suivre retards, incidents et preuves de passage",
    "Limiter kilomètres à vide, attentes et coûts",
    "Mettre à jour client, plateforme ou donneur d'ordre",
  ]],
  [/patients?|rendez-vous & demandes|rendez-vous & relation patient|dossiers & bilans|bilans & dossiers|dossiers patients|consultations & suivi|séances & suivi|soins & transmissions|ordonnances & dossiers/i, [
    "Qualifier motif, urgence et informations de santé utiles",
    "Mettre à jour dossier, antécédents et consentements",
    "Préparer séance, consultation ou soin",
    "Noter décisions, actes et suivi à prévoir",
    "Conserver une trace confidentielle et accessible",
  ]],
  [/pharmacie|ordonnances & délivrance|stock & grossistes/i, [
    "Vérifier ordonnance, conseil et conformité de délivrance",
    "Contrôler stock, ruptures, périmés et substitutions",
    "Suivre commandes grossistes et produits sensibles",
    "Repérer ventes conseil ou besoins patients récurrents",
    "Archiver traçabilité et incidents qualité",
  ]],
  [/auto-école|planning leçons|examens & réussite|moniteurs & véhicules|inscriptions élèves/i, [
    "Qualifier objectif, niveau et contraintes élève",
    "Planifier leçons, moniteurs et véhicules",
    "Suivre heures réalisées, absences et progression",
    "Préparer dossier et créneau d'examen",
    "Mesurer réussite, délais et reste à facturer",
  ]],
  [/sessions & accompagnement|alternance & suivi apprentis|qualité & conformité|progression & certificats|contenus & modules/i, [
    "Planifier parcours, sessions ou modules",
    "Suivre présences, progression et évaluations",
    "Collecter émargements, preuves et livrables pédagogiques",
    "Traiter absences, abandons ou blocages apprenants",
    "Préparer certificats, bilans ou preuves qualité",
  ]],
  [/copropriétaires|copropriétés|budgets & appels de fonds|loyers & quittances|baux & états des lieux|location & locataires|travaux & incidents/i, [
    "Centraliser lots, occupants et demandes ouvertes",
    "Suivre échéances, appels, loyers ou quittances",
    "Coordonner interventions, sinistres et prestataires",
    "Relancer copropriétaires, locataires ou propriétaires",
    "Archiver décisions, documents et justificatifs",
  ]],
  [/sourcing & stratégie opérations|financement & acquisition|acquisition & financement|travaux & exploitation|travaux & ameublement|commercialisation|valorisation & rendement|rendement & valorisation/i, [
    "Qualifier opportunité, prix, risques et potentiel",
    "Mettre à jour financement, budget travaux et calendrier",
    "Suivre décisions, signatures et conditions suspensives",
    "Contrôler marge, rendement ou cash-flow réel",
    "Préparer revente, location ou reporting investisseur",
  ]],
  [/réservations & voyageurs|réservations & canaux|accueil & séjour|ménage & check-in|ménage & maintenance|avis & expérience|départs & incidents/i, [
    "Suivre réservations, arrivées et départs",
    "Préparer accès, ménage, linge et consignes voyageurs",
    "Traiter incidents, maintenance et demandes urgentes",
    "Contrôler avis, qualité séjour et réclamations",
    "Mettre à jour prix, disponibilités et commissions",
  ]],
  [/dépôt|pressing|tri & traitement|retraits & litiges|clients, dépôts & tickets/i, [
    "Enregistrer dépôt, étiquette et consignes textile",
    "Trier articles selon traitement et délai",
    "Suivre machines, incidents et retards",
    "Gérer retraits, litiges ou vêtements sensibles",
    "Rapprocher tickets, caisse et articles restants",
  ]],
  [/laverie|local & machines|machines & consommables|maintenance & pannes|propreté & incidents/i, [
    "Suivre disponibilité machines et consommables",
    "Repérer pannes, incidents ou anomalies de paiement",
    "Planifier nettoyage, maintenance et interventions",
    "Contrôler fréquentation, énergie et encaissements",
    "Prévenir prestataire ou client en cas de blocage",
  ]],
  [/association|adhérents & communauté|actions & événements|financements & budget|gouvernance & obligations|bénévoles & équipe/i, [
    "Suivre adhérents, bénévoles et publics concernés",
    "Planifier actions, événements et responsabilités",
    "Préparer subventions, dons et budget par projet",
    "Contrôler obligations statutaires et décisions",
    "Partager avancement avec bureau ou équipe",
  ]],
  [/familles & inscriptions|planning enfants|transmissions & santé|projet d’accueil|facturation familles|équipe & encadrement/i, [
    "Suivre demandes familles, places et dossiers enfants",
    "Planifier présences, absences et taux d'encadrement",
    "Collecter transmissions, santé et autorisations",
    "Prévenir familles en cas d'alerte ou changement",
    "Contrôler facturation, protocoles et obligations",
  ]],
  [/demandes voyageurs|offres & destinations|devis & réservations|fournisseurs & assurances|départs & incidents/i, [
    "Qualifier projet, budget, dates et contraintes voyageur",
    "Comparer disponibilités fournisseurs, marges et conditions",
    "Préparer devis, options, assurance et documents",
    "Suivre réservations, paiements et départs",
    "Gérer modifications, incidents et satisfaction retour",
  ]],
  [/activation & support|maintenance & support|clients & support/i, [
    "Centraliser tickets, incidents et demandes produit",
    "Qualifier impact utilisateur, urgence et compte concerné",
    "Prioriser bug, amélioration ou aide à l'usage",
    "Tenir le client informé jusqu'à résolution",
    "Transformer les demandes récurrentes en amélioration produit",
  ]],
  [/offres? & expertises|offre & positionnement|positionnement & offres|expertise & offres|formats & positionnement|marchés & spécialités/i, [
    "Clarifier spécialités, cibles et problèmes traités",
    "Mettre à jour formats, prix et conditions d'intervention",
    "Définir ce qui est inclus, exclu ou optionnel",
    "Préparer preuves, cas clients ou éléments de réassurance",
    "Identifier les offres à renforcer, simplifier ou arrêter",
  ]],
  [/missions & livrables|livrables & ateliers|livrables & restitution|cadrage & ateliers|cadrage mission|comités & décisions client|relation client/i, [
    "Cadrer objectifs, périmètre et décideurs",
    "Planifier ateliers, jalons et validations",
    "Produire livrables, recommandations ou supports attendus",
    "Suivre retours, décisions et arbitrages client",
    "Archiver version validée et prochaines actions",
  ]],
  [/clients & mandats|sourcing candidats|entretiens & shortlists|placements & garanties/i, [
    "Qualifier poste, critères, rémunération et urgence",
    "Sourcer candidats et suivre réponses",
    "Conduire entretiens, évaluations et shortlists",
    "Partager retours client et décision candidat",
    "Suivre placement, intégration et période de garantie",
  ]],
  [/contrats clients & sites|cahiers des charges|planning agents|passages & contrôles|réclamations client|marge contrat/i, [
    "Qualifier site, surfaces, horaires et niveau attendu",
    "Formaliser cahier des charges, accès et consignes",
    "Planifier agents, remplacements et contrôles terrain",
    "Suivre passages, réclamations et reprises",
    "Comparer heures prévues, heures réalisées et marge contrat",
  ]],
  [/clients & ordres de transport|chargement & livraison|cmr & conformité|incidents & retards|marge tournée/i, [
    "Enregistrer ordre de transport, chargement et contraintes",
    "Planifier camion, conducteur et créneau de livraison",
    "Vérifier CMR, preuves et obligations transport",
    "Suivre retards, incidents et litiges marchandise",
    "Contrôler kilomètres, carburant et marge tournée",
  ]],
  [/demandes clients & volumes|livraisons & preuves|incidents & retours|coût par livraison/i, [
    "Prévoir volumes, zones et créneaux de livraison",
    "Affecter chauffeurs, véhicules et tournées",
    "Suivre preuves de livraison et échecs de passage",
    "Traiter retours, retards ou incidents client",
    "Mesurer coût par livraison et productivité tournée",
  ]],
  [/demandes & réservations groupes|expérience passagers|rentabilité trajet|chauffeurs & services/i, [
    "Qualifier trajet, horaires, groupe et contraintes bagages",
    "Planifier véhicule, conducteur et feuille de route",
    "Vérifier sécurité, documents et points de prise en charge",
    "Suivre ponctualité, incidents et satisfaction passagers",
    "Calculer marge trajet, kilomètres et temps d'attente",
  ]],
  [/offres & menus|production événement|livraison & installation|qualité & retours client/i, [
    "Cadrer nombre d'invités, lieu, horaires et contraintes",
    "Valider menu, devis, acompte et options",
    "Planifier production, achats, équipe et livraison",
    "Coordonner installation, service et imprévus jour J",
    "Suivre retours client, marge et reste à facturer",
  ]],
  [/cartes & plateformes|commandes en ligne|production cuisine|livraison & incidents/i, [
    "Mettre à jour cartes, prix et disponibilités plateformes",
    "Suivre commandes, temps de préparation et annulations",
    "Organiser production cuisine pendant les pics",
    "Traiter notes, retards, remboursements et incidents livraison",
    "Comparer commissions, coût matière et marge nette",
  ]],
  [/gamme & recettes|production & fournées|production & planning|production cuisine|préparation & rush|préparation & livraison/i, [
    "Planifier recettes, fournées ou préparations par créneau",
    "Vérifier matières, quantités et capacités de production",
    "Suivre pertes, invendus et ruptures pendant le service",
    "Contrôler qualité, fraîcheur et respect des standards",
    "Ajuster planning selon ventes, météo ou événements",
  ]],
  [/assortiment & prix|vitrine & clients|vitrine & fidélisation|vitrine & fidélité|stock & réservations|retours & invendus|flux clients & relais|clients & animations/i, [
    "Définir assortiment, vitrine et temps forts commerciaux",
    "Suivre demandes, réservations et clients récurrents",
    "Contrôler stock, réassort, retours et invendus",
    "Animer magasin, conseil ou événements locaux",
    "Mesurer panier moyen, rotation et marge rayon",
  ]],
  [/carte & ambiance|carte & emplacements|service bar|stocks boissons|caisse & marge boissons|hygiène & licence/i, [
    "Mettre à jour carte, prix et offres du moment",
    "Préparer mise en place, stock bar et service",
    "Suivre fréquentation, pics et événements",
    "Contrôler pertes, écarts de caisse et marge boissons",
    "Vérifier licence, hygiène et obligations d'affichage",
  ]],
  [/abonnements & pilotage|acquisition & rétention|planning cours|salle & équipements|incidents & maintenance|équipe & coachs/i, [
    "Suivre abonnements, inscriptions et résiliations",
    "Remplir cours, créneaux et accompagnements coachs",
    "Contrôler équipements, incidents et maintenance",
    "Mesurer fréquentation, no-show et satisfaction adhérents",
    "Ajuster offres, planning et relances de rétention",
  ]],
  [/contrat|sinistres & suivi|offres & accords|primes & commissions|renouvellements|cabinet d’assurance/i, [
    "Qualifier besoin, garanties, risque et échéance",
    "Comparer offres, franchises et exclusions",
    "Suivre contrats, avenants et renouvellements",
    "Traiter sinistres, pièces et relances assureur",
    "Contrôler primes, commissions et dossiers incomplets",
  ]],
  [/demandes & qualification|banques & assureurs|offres & accords|conformité courtage|commissions & suivi/i, [
    "Qualifier projet, capacité et pièces emprunteur",
    "Préparer dossier banque ou assurance",
    "Suivre accords, refus, conditions et délais",
    "Comparer offres et expliquer les arbitrages",
    "Contrôler conformité, commission et relances",
  ]],
  [/programme & cadrage client|études & permis|suivi chantier|honoraires & budget/i, [
    "Cadrer programme, budget et contraintes client",
    "Suivre esquisse, permis, consultations et validations",
    "Coordonner entreprises, chantier et comptes rendus",
    "Repérer décisions client ou réserves bloquantes",
    "Contrôler honoraires, phases et budget travaux",
  ]],
  [/offre & montures|commandes & montage|conseil & vente|sav & ajustements|équipe & opticiens/i, [
    "Vérifier ordonnance, besoin visuel et prise en charge",
    "Conseiller montures, verres et options adaptées",
    "Suivre commande, montage et délai fournisseur",
    "Traiter ajustements, SAV et garanties",
    "Mesurer panier moyen, marge et clients récurrents",
  ]],
  [/offres & compositions|fleurs & arrivages|commandes & événements|qualité & fraîcheur/i, [
    "Prévoir arrivages, saisonnalité et pertes fleurs",
    "Préparer bouquets, commandes et événements",
    "Suivre stock fragile, fraîcheur et ruptures",
    "Adapter vitrine, prix et compositions du moment",
    "Contrôler marge, invendus et satisfaction client",
  ]],
  [/sélection & rayons|commandes éditeurs|retours & invendus|clients & animations|équipe & libraires/i, [
    "Construire sélection, nouveautés et coups de coeur",
    "Suivre commandes éditeurs, réservations et délais",
    "Gérer retours, invendus et stock dormant",
    "Planifier animations, rencontres ou vitrines",
    "Mesurer rotation, panier moyen et demandes clients",
  ]],
  [/programmes & séances|suivi objectifs|séances & planning|prospects & diagnostics|offres & méthode/i, [
    "Qualifier objectif, contexte et motivation client",
    "Définir programme, séances et indicateurs de progrès",
    "Suivre présence, engagement et actions entre séances",
    "Ajuster accompagnement selon retours et résultats",
    "Préparer bilan, renouvellement ou orientation",
  ]],
  [/cadre d’accompagnement|rendez-vous & demandes|dossiers & suivis|confidentialité & cadre|réseau & orientations/i, [
    "Clarifier demande, cadre et limites de l'accompagnement",
    "Planifier rendez-vous et continuité de suivi",
    "Noter éléments utiles dans un cadre confidentiel",
    "Repérer alertes, orientations ou relais nécessaires",
    "Suivre paiements, annulations et prochaine séance",
  ]],
  [/positionnement & accompagnement|rendez-vous & relation patient|cadre & confidentialité|réseau & relais/i, [
    "Clarifier motifs de consultation et cadre de prise en charge",
    "Préparer séance, antécédents et points de vigilance",
    "Suivre évolution, recommandations et prochain rendez-vous",
    "Conserver notes utiles dans un cadre confidentiel",
    "Orienter vers relais médical si nécessaire",
  ]],
  [/bilan & objectifs client|préconisations & dossiers|suivi patrimoine|honoraires & encours|conformité & profil risque/i, [
    "Collecter situation, objectifs et profil de risque",
    "Préparer bilan patrimonial et préconisations",
    "Vérifier conformité, pièces et devoir de conseil",
    "Suivre arbitrages, souscriptions et relances",
    "Mesurer encours, honoraires et satisfaction client",
  ]],
  [/cadastre & préparation|relevés terrain|plans & livrables|bornage & conformité|honoraires & délais/i, [
    "Préparer dossier cadastral, accès et contraintes terrain",
    "Réaliser relevés, mesures et contrôles nécessaires",
    "Produire plans, PV ou livrables attendus",
    "Suivre bornage, signatures et conformité",
    "Contrôler délais, honoraires et retours client",
  ]],
];

const SPECIFIC_ACTIONS: Array<[RegExp, string[]]> = [
  [/offre & pédagogie|offre & référentiels|offre de soins|offre de prise en charge|offres & outils web/i, [
    "Clarifier l'offre, les limites et les conditions",
    "Mettre à jour tarifs, formats ou spécialités",
    "Identifier les offres à développer ou arrêter",
    "Préparer les éléments à montrer au client",
    "Vérifier que l'offre reste alignée avec la demande",
  ]],
  [/rendez-vous & accueil|rendez-vous & orientation|patients & prescriptions/i, [
    "Qualifier la demande patient",
    "Vérifier motif, urgence et informations utiles",
    "Orienter vers le bon créneau ou praticien",
    "Confirmer rendez-vous et consignes",
    "Gérer absence, retard ou report",
  ]],
  [/dossiers patients|bilans & dossiers|dossiers animaux/i, [
    "Créer ou mettre à jour le dossier",
    "Collecter les informations utiles",
    "Vérifier consentements, prescriptions ou antécédents",
    "Classer les comptes rendus importants",
    "Garder une trace conforme et accessible",
  ]],
  [/consultations & suivi|séances & suivi|soins & transmissions/i, [
    "Préparer la consultation ou séance",
    "Noter actes, décisions et suite à donner",
    "Planifier le suivi si nécessaire",
    "Transmettre les informations utiles",
    "Clôturer les points ouverts",
  ]],
  [/bénéficiaires & contrats|clients & contrats/i, [
    "Qualifier besoin, domicile et contraintes",
    "Valider contrat, fréquence et consignes",
    "Collecter les informations utiles",
    "Confirmer démarrage et modalités",
    "Garder une trace claire des engagements",
  ]],
  [/plans d’intervention|consignes domicile/i, [
    "Décrire les tâches à réaliser",
    "Préciser horaires, accès et consignes",
    "Identifier points de vigilance ou fragilités",
    "Partager le plan avec l'intervenant",
    "Mettre à jour après retour terrain",
  ]],
  [/présences & transmissions|présences & qualité/i, [
    "Suivre présences et heures réalisées",
    "Collecter les transmissions importantes",
    "Repérer absence, retard ou incident",
    "Prévenir famille ou client si nécessaire",
    "Clôturer les alertes ouvertes",
  ]],
  [/opco & pilotage/i, [
    "Suivre prises en charge et montants attendus",
    "Vérifier factures, échéances et accords OPCO",
    "Repérer dossiers non facturés ou en attente",
    "Relancer financeurs ou entreprises",
    "Mettre à jour le reste à encaisser",
  ]],
  [/pièces & fournisseurs/i, [
    "Lister les pièces nécessaires",
    "Vérifier disponibilité, prix et délais",
    "Commander ou réserver les pièces",
    "Rattacher chaque achat au bon dossier",
    "Suivre retards, garanties et retours fournisseur",
  ]],
  [/production|fabrication|création|rédaction|campagnes|éditoriale|contenu|fournées/i, [
    "Planifier les tâches à produire",
    "Préparer brief, matières ou contenus nécessaires",
    "Suivre avancement, validations et retours",
    "Contrôler qualité avant livraison ou diffusion",
    "Archiver la version validée",
  ]],
  [/reporting|performance|usage|progression|réussite|engagement|audience/i, [
    "Suivre les indicateurs utiles",
    "Repérer écarts, retards ou signaux faibles",
    "Partager une synthèse claire",
    "Décider les actions correctives",
    "Conserver l'historique de suivi",
  ]],
  [/livrables|restitution|rapports|plans & livrables|postproduction|livraison/i, [
    "Lister les livrables attendus",
    "Vérifier contenu, format et niveau de finition",
    "Faire valider avant envoi final",
    "Livrer au bon canal",
    "Archiver fichiers et retours client",
  ]],
  [/sourcing|recherche & analyse|analyse société|sourcing biens|sourcing candidats|sourcing actifs/i, [
    "Définir les critères de recherche",
    "Qualifier les opportunités ou profils",
    "Comparer intérêt, risques et priorités",
    "Documenter les décisions",
    "Suivre les prochaines relances",
  ]],
  [/réseau|partenaires|prescripteurs|apporteurs|co-investisseurs|prestataires/i, [
    "Identifier les partenaires utiles",
    "Clarifier rôle, attentes et périmètre",
    "Suivre introductions, demandes et retours",
    "Relancer les partenaires actifs",
    "Mesurer ce que le réseau apporte vraiment",
  ]],
  [/pannes|machines|véhicule & entretien|matériel & lieux|local & machines/i, [
    "Lister équipements et points sensibles",
    "Planifier entretien ou vérifications",
    "Suivre pannes, incidents et indisponibilités",
    "Déclencher prestataire ou réparation",
    "Archiver coûts et interventions",
  ]],
  [/brief|cadrage mission|cahiers des charges|consignes de poste|brief acquéreur/i, [
    "Clarifier besoin, contexte et contraintes",
    "Lister informations ou accès manquants",
    "Valider périmètre, priorités et livrables",
    "Partager les consignes aux personnes concernées",
    "Tracer les changements décidés",
  ]],
  [/accueil & séjour|expérience passagers|accueil & conseil|conseil & vente|conseil & fidélité/i, [
    "Préparer l'accueil et les informations utiles",
    "Identifier attentes, questions ou irritants",
    "Apporter le conseil adapté",
    "Suivre satisfaction et retours",
    "Déclencher la suite commerciale ou opérationnelle",
  ]],
  [/ordonnances|actes|formalités|signatures|déclarations|attestations|fluides|permis/i, [
    "Vérifier les pièces ou obligations attendues",
    "Préparer les documents à produire",
    "Contrôler cohérence et échéances",
    "Faire signer ou transmettre au bon interlocuteur",
    "Archiver la preuve utile",
  ]],
  [/copropriétaires|propriétaires|locataires|baux|états des lieux|location|occupation/i, [
    "Centraliser les informations du dossier",
    "Suivre demandes, décisions et échéances",
    "Préparer documents ou échanges nécessaires",
    "Relancer les parties concernées",
    "Garder une trace exploitable",
  ]],
  [/entretiens & shortlists|placements & garanties/i, [
    "Préparer les profils ou candidats à évaluer",
    "Conduire entretiens et validations",
    "Partager shortlist ou décision client",
    "Suivre placement, intégration et garantie",
    "Relancer les dossiers en attente",
  ]],
  [/acheteurs & support|annonceurs & abonnés|acquéreurs & visites|commercialisation/i, [
    "Qualifier les demandes et attentes",
    "Préparer les informations à transmettre",
    "Organiser visites, échanges ou supports",
    "Suivre retours, objections et décisions",
    "Relancer les contacts à potentiel",
  ]],
  [/passages & contrôles|ménage & check-in|ménage & maintenance|service bar|mise en service|tri & traitement/i, [
    "Préparer le passage ou l'intervention",
    "Vérifier consignes, matériel et accès",
    "Réaliser le contrôle qualité",
    "Signaler incident ou reprise nécessaire",
    "Clôturer avec une trace claire",
  ]],
  [/analyse & financement|objectifs & profil risque|souscriptions & arbitrages|banques & assureurs/i, [
    "Collecter les informations financières utiles",
    "Analyser risques, objectifs et contraintes",
    "Comparer options ou scénarios",
    "Préparer la décision ou le dossier",
    "Suivre arbitrages, accords et échéances",
  ]],
  [/menu & formules|presse & tabac|colis & point relais|fleurs & arrivages|couleurs & fournitures|végétaux & fournitures|achats & corps d’état/i, [
    "Lister les références, fournitures ou besoins",
    "Vérifier disponibilité, prix et délais",
    "Préparer commandes ou mises en avant",
    "Suivre ruptures, pertes ou écarts",
    "Adapter selon saison, chantier ou demande",
  ]],
  [/plateforme & accès/i, [
    "Créer ou vérifier les accès",
    "Contrôler parcours, modules et droits",
    "Suivre problèmes de connexion ou support",
    "Mettre à jour contenus et paramètres",
    "Archiver demandes et corrections",
  ]],
  [/diagnostic appareil|diagnostics & relevés|urgences & diagnostics toiture|visites & analyse/i, [
    "Préparer les informations ou outils nécessaires",
    "Réaliser diagnostic, relevé ou analyse",
    "Documenter constats, photos et mesures",
    "Identifier suite à donner ou devis",
    "Partager le résultat au client",
  ]],
  [/consultation entreprises/i, [
    "Préparer le dossier de consultation",
    "Identifier entreprises ou lots concernés",
    "Suivre retours, devis et questions",
    "Comparer offres et risques",
    "Tracer la décision retenue",
  ]],
  [/offices & domaines|mission & projets|projet d’accueil/i, [
    "Clarifier mission, périmètre et priorités",
    "Définir publics, domaines ou projets suivis",
    "Mettre à jour règles, offres ou engagements",
    "Partager les éléments structurants à l'équipe",
    "Revoir régulièrement ce qui doit évoluer",
  ]],
  [/prise de vue & tournage/i, [
    "Préparer lieux, matériel et autorisations",
    "Confirmer planning et personnes présentes",
    "Suivre prises réalisées et plans manquants",
    "Sauvegarder fichiers au bon endroit",
    "Préparer la suite postproduction",
  ]],
  [/séances & continuité|transmissions & santé/i, [
    "Préparer la séance ou transmission",
    "Noter les informations importantes",
    "Suivre évolution, alerte ou point sensible",
    "Planifier la prochaine étape",
    "Conserver une trace confidentielle et utile",
  ]],
  [/assortiment & prix|sélection & rayons|sélection & cave|rayons & produits frais|activités & services/i, [
    "Définir les gammes et produits à mettre en avant",
    "Mettre à jour prix, marges et conditions",
    "Identifier les références à pousser ou arrêter",
    "Vérifier cohérence vitrine, rayons et stock",
    "Préparer les temps forts commerciaux",
  ]],
  [/vente & caisse|caisse & panier moyen|caisse & pertes|caisse & marge rayon|caisse & écarts/i, [
    "Suivre ventes, encaissements et écarts de caisse",
    "Contrôler panier moyen et produits vendus",
    "Repérer remises, pertes ou anomalies",
    "Rapprocher caisse, tickets et paiements",
    "Identifier les leviers de marge",
  ]],
  [/cadrage & maquettes/i, [
    "Recueillir objectifs, contenus et contraintes client",
    "Valider arborescence, parcours et maquettes",
    "Lister les contenus ou accès manquants",
    "Faire confirmer le périmètre avant production",
    "Tracer les demandes de changement",
  ]],
  [/développement & recette/i, [
    "Planifier les tâches de production",
    "Suivre intégration, contenus et fonctionnalités",
    "Tester les parcours importants",
    "Corriger les retours avant mise en ligne",
    "Obtenir la validation client",
  ]],
  [/maintenance & support|activation & support|clients & support/i, [
    "Centraliser demandes support et incidents",
    "Prioriser urgences, bugs et petites évolutions",
    "Informer le client de l'avancement",
    "Clôturer avec une trace claire",
    "Repérer les demandes récurrentes à industrialiser",
  ]],
  [/commercial & admissions|candidats & admissions|inscriptions élèves|acquisition & inscriptions/i, [
    "Qualifier la demande entrante",
    "Identifier profil, objectif et prérequis",
    "Vérifier financement ou prise en charge possible",
    "Envoyer programme, devis ou dossier d'inscription",
    "Relancer les dossiers chauds",
  ]],
  [/dossiers & financements|entreprises & contrats/i, [
    "Collecter les pièces nécessaires",
    "Vérifier OPCO, CPF ou financement entreprise",
    "Préparer convention, contrat ou dossier OPCO",
    "Suivre accords, refus et pièces manquantes",
    "Garder les preuves utiles",
  ]],
  [/sessions & accompagnement|alternance & suivi apprentis/i, [
    "Planifier dates, salles ou visios",
    "Confirmer formateurs, intervenants et apprenants",
    "Envoyer convocations et accès",
    "Suivre présence, émargements et progression",
    "Traiter absences, reports ou abandons",
  ]],
  [/demandes? chantier|demandes?, .*devis|urgences?, .*devis|dépannages?, .*devis|projets? client.*devis/i, [
    "Qualifier la demande client",
    "Vérifier urgence, adresse, accès et contraintes",
    "Récupérer photos, plans ou mesures utiles",
    "Planifier une visite si nécessaire",
    "Chiffrer main-d'œuvre, matériaux et marge",
    "Envoyer le devis",
    "Relancer les devis ouverts",
  ]],
  [/planning chantier|planning interventions|planning atelier|planning carrosserie|planning météo/i, [
    "Prioriser les dossiers ou interventions signés",
    "Bloquer les dates et ressources nécessaires",
    "Confirmer équipe, matériel et client",
    "Anticiper dépendances, météo ou accès",
    "Mettre à jour le planning en cas d'imprévu",
  ]],
  [/cabines? & planning|planning fauteuils|planning prestations/i, [
    "Organiser les créneaux par durée de prestation",
    "Affecter cabines, fauteuils ou praticiennes",
    "Confirmer les rendez-vous",
    "Limiter les trous dans le planning",
    "Gérer annulations et no-show",
  ]],
  [/produits? & matériel|produits? & stock/i, [
    "Suivre produits cabine, revente et consommables",
    "Vérifier seuils, ruptures et péremptions",
    "Commander au bon moment",
    "Contrôler les écarts entre usage et stock",
    "Identifier les produits à pousser",
  ]],
  [/cuisine & service/i, [
    "Préparer la mise en place avant le service",
    "Coordonner cuisine et salle",
    "Suivre temps d'attente et incidents",
    "Adapter les priorités pendant le rush",
    "Clôturer les retours importants après service",
  ]],
  [/stocks? & fournisseurs|matières? & réassort|matériaux? & fournisseurs|matériel & fournisseurs/i, [
    "Lister les besoins par activité ou chantier",
    "Vérifier disponibilité, prix et délais",
    "Commander au bon moment",
    "Suivre livraisons, ruptures et écarts",
    "Rattacher les achats au bon dossier",
  ]],
  [/courses? & planning|tournées? & zones|planning flotte|planning trajets/i, [
    "Planifier trajets, tournées ou zones",
    "Confirmer véhicules et conducteurs",
    "Limiter les temps morts et kilomètres inutiles",
    "Suivre retards, incidents et changements",
    "Mettre à jour le client ou le donneur d'ordre",
  ]],
  [/clients? & rendez-vous atelier|clients?, atelier & sinistres|demandes? & tickets réparation/i, [
    "Qualifier la demande ou le sinistre",
    "Créer le dossier atelier",
    "Établir diagnostic, devis ou accord",
    "Commander les pièces nécessaires",
    "Informer le client sur délai et restitution",
  ]],
];

const PRIORITY_ACTIONS: Array<[RegExp, string[]]> = [
  [/visibilit|acquisition|vitrine|diffusion|fréquentation|réservation|fidélisation|contenu|audience|communauté/i, [
    "Publier les offres ou prestations à montrer",
    "Mettre à jour Google, réseaux sociaux ou canaux utiles",
    "Collecter et afficher les avis clients",
    "Qualifier les demandes entrantes",
    "Transformer les demandes en rendez-vous ou commandes",
    "Relancer les clients à potentiel",
  ]],
  [/facturation|paiement|caisse|marge|rentabilité|honoraire|commission|budget|trésorerie|encaissement|loyer|opco|coût|revenu|abonnement|prime|émolument|frais|valorisation|rendement/i, [
    "Suivre ce qui est signé, facturé et encaissé",
    "Comparer le prévu avec le réel",
    "Repérer les montants non facturés",
    "Relancer les paiements en attente",
    "Mettre à jour la marge ou le reste à encaisser",
  ]],
  [/équipe|intervenant|sous-traitant|prestataire|chauffeur|agent|moniteur|coach|praticien|bénévole|extra|clerc|apporteur|renfort|remplacement|habilitations/i, [
    "Attribuer les responsabilités",
    "Confirmer disponibilités et compétences",
    "Partager consignes, accès et priorités",
    "Suivre charge, absences et remplacements",
    "Clarifier qui décide en cas de blocage",
  ]],
  [/qualité|conformité|réserve|réception|preuve|qualiopi|haccp|hygiène|sécurité|traçabilité|confidentialité|agrément|norme|licence|obligation/i, [
    "Vérifier les points obligatoires",
    "Identifier les écarts ou réserves",
    "Planifier les corrections",
    "Faire valider la conformité",
    "Archiver les preuves utiles",
  ]],
];

function uniqueItems(items: string[]) {
  return [...new Set(items.map((item) => item.trim()).filter(Boolean))];
}

export function buildChecklistForBusinessBlock(block: BusinessModelBlock): string[] {
  const contextual = CONTEXTUAL_ACTIONS.find(([pattern]) => pattern.test(block.title));

  if (contextual) {
    return contextual[1];
  }

  const specific = SPECIFIC_ACTIONS.find(([pattern]) => pattern.test(block.title));

  if (specific) {
    return specific[1];
  }

  const priority = PRIORITY_ACTIONS.find(([pattern]) => pattern.test(block.title));

  if (priority) {
    return priority[1];
  }

  const actions = TERM_ACTIONS.flatMap(([pattern, items]) => (
    pattern.test(block.title) ? items : []
  ));

  return uniqueItems(actions.length ? actions : FALLBACK_ACTIONS).slice(0, 7);
}

export function buildBusinessBlockChecklists(blocks: BusinessModelBlock[]): BusinessBlockChecklist[] {
  return blocks.map((block) => ({
    title: block.title,
    checklist: buildChecklistForBusinessBlock(block),
  }));
}
