export const RELATED_SYSTEM_SLUGS_BY_CONTENT_SLUG: Record<string, string[]> = {
  "obligations-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "gestionnaire-paie-independant",
    "commerce-de-detail",
    "restaurant",
  ],
  "previsionnel-financier": [
    "daf-externalise",
    "cabinet-comptable",
    "investissement-locatif",
    "marchand-de-biens",
    "saas",
    "restaurant",
  ],
  "systeme-operationnel-airtable": [
    "cabinet-de-conseil",
    "consultant-independant",
    "freelance",
    "agence-marketing",
    "agence-web",
    "daf-externalise",
  ],
  "obligations-tpe-template": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "gestionnaire-paie-independant",
    "commerce-de-detail",
    "restaurant",
  ],
  "suivi-previsionnel-financier-template": [
    "daf-externalise",
    "cabinet-comptable",
    "investissement-locatif",
    "marchand-de-biens",
    "saas",
    "restaurant",
  ],
  "systeme-operationnel-template": [
    "cabinet-de-conseil",
    "consultant-independant",
    "freelance",
    "agence-marketing",
    "agence-web",
    "daf-externalise",
  ],
  "facture-electronique": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "commerce-de-detail",
    "restaurant",
    "e-commerce",
  ],
  "urgent-important-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "consultant-independant",
    "commerce-de-detail",
    "agence-marketing",
  ],
  "suivi-devis-tpe": [
    "cabinet-comptable",
    "consultant-independant",
    "agence-marketing",
    "agence-web",
    "commerce-de-detail",
    "plomberie-chauffage",
  ],
  "hors-cadre-client-tpe": [
    "cabinet-comptable",
    "consultant-independant",
    "agence-marketing",
    "agence-web",
    "plomberie-chauffage",
    "assistant-administratif-externalise",
  ],
  "deleguer-premier-tpe": [
    "cabinet-comptable",
    "assistant-administratif-externalise",
    "daf-externalise",
    "consultant-independant",
    "agence-marketing",
    "agence-web",
  ],
  "facturer-vite-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "consultant-independant",
    "commerce-de-detail",
    "restaurant",
  ],
  "acompte-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "consultant-independant",
    "agence-marketing",
    "agence-web",
    "plomberie-chauffage",
  ],
  "devis-clair-tpe": [
    "cabinet-comptable",
    "consultant-independant",
    "agence-marketing",
    "agence-web",
    "plomberie-chauffage",
    "assistant-administratif-externalise",
  ],
  "prix-rentable-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "consultant-independant",
    "agence-marketing",
    "plomberie-chauffage",
  ],
  "relances-clients-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "commerce-de-detail",
    "restaurant",
    "e-commerce",
  ],
  "tresorerie-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "commerce-de-detail",
    "restaurant",
    "plomberie-chauffage",
  ],
};
