export const RELATED_SYSTEM_SLUGS_BY_CONTENT_SLUG: Record<string, string[]> = {
  "obligations-tpe": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "gestionnaire-paie-independant",
    "commerce-de-detail",
    "restaurant",
  ],
  "previsionnel-financier": [
    "daf-externalise",
    "cabinet-comptable",
    "investissement-locatif",
    "marchand-de-biens",
    "saas",
    "restaurant",
  ],
  "systeme-operationnel-airtable": [
    "cabinet-de-conseil",
    "consultant-independant",
    "freelance",
    "agence-marketing",
    "agence-web",
    "daf-externalise",
  ],
  "obligations-tpe-template": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "gestionnaire-paie-independant",
    "commerce-de-detail",
    "restaurant",
  ],
  "suivi-previsionnel-financier-template": [
    "daf-externalise",
    "cabinet-comptable",
    "investissement-locatif",
    "marchand-de-biens",
    "saas",
    "restaurant",
  ],
  "systeme-operationnel-template": [
    "cabinet-de-conseil",
    "consultant-independant",
    "freelance",
    "agence-marketing",
    "agence-web",
    "daf-externalise",
  ],
  "facture-electronique": [
    "cabinet-comptable",
    "daf-externalise",
    "assistant-administratif-externalise",
    "commerce-de-detail",
    "restaurant",
    "e-commerce",
  ],
};
