import "server-only";

import type {
  SolutionPlacement,
  SolutionResource,
} from "@/lib/solution-registry-contract";

const LEVIER_REVIEW = {
  evidence: [
    {
      evidenceId: "levier-product-validation-2026-08-03",
      sourceRef: "decision://systems/levier-2026-08-03",
      claim:
        "Levier est validé comme tableau de pilotage opérationnel universel des pages Systèmes.",
      evidenceType: "internal_test" as const,
      capturedAt: "2026-08-03T00:00:00.000Z",
    },
  ],
  reviewer: "Master Demaa",
  reviewedAt: "2026-08-03T00:00:00.000Z",
  expiresAt: "2027-08-03T00:00:00.000Z",
} as const;

export const LEVIER_SOLUTION_RESOURCE = {
  ...LEVIER_REVIEW,
  resourceSlug: "levier",
  resourceType: "tool",
  name: "Levier",
  description: "Tableau de pilotage opérationnel",
  interactionMode: "system_delivery",
  commercialRelationship: "owned",
  status: "published",
  resourceVersion: "levier.v1",
  publicationBlockers: [],
} as const satisfies SolutionResource;

export const LEVIER_PLACEMENT_SYSTEM_SLUGS = [
  "cabinet-comptable",
  "cabinet-davocat",
  "cabinet-de-conseil",
  "agence-marketing",
  "freelance",
  "agence-de-recrutement",
  "agence-web",
  "creation-de-contenu",
  "marketplace",
  "media",
  "saas",
  "batiment",
  "nettoyage-professionnel",
  "agence-immobiliere",
  "syndic",
  "gestion-locative",
  "marchand-de-biens",
  "investissement-locatif",
  "conciergerie-airbnb",
  "investissement-immobilier",
  "investissement-financier",
  "investissement-entreprise",
  "demenagement",
  "livraison-dernier-kilometre",
  "transport-de-marchandise",
  "transport-de-personnes",
  "restaurant",
  "fast-food",
  "traiteur",
  "dark-kitchen",
  "boulangerie",
  "commerce-de-detail",
  "e-commerce",
  "institut-de-beaute",
  "salon-de-coiffure",
  "esthetique",
  "services-a-la-personne",
  "organisme-de-formation",
  "cfa",
  "formation-en-ligne",
  "production-industrie",
  "plomberie-chauffage",
  "electricite-generale",
  "renovation-interieur",
  "menuiserie-agencement",
  "maconnerie-gros-oeuvre",
  "paysagiste",
  "garage-automobile",
  "carrosserie",
  "commerce-alimentaire",
  "boutique-specialisee",
  "tabac-presse-point-relais",
  "bar-cafe",
  "hotel-hebergement-independant",
  "cabinet-medical",
  "cabinet-paramedical",
  "infirmier-liberal",
  "aide-a-domicile-menage",
  "reparation-informatique-mobile",
  "architecte-maitre-oeuvre",
  "courtier-credit-assurance",
  "auto-ecole",
  "photographe-videaste",
  "evenementiel",
  "salle-de-sport",
  "dentiste",
  "pharmacie",
  "notaire",
  "veterinaire",
  "agence-de-voyage",
  "opticien",
  "pisciniste",
  "diagnostiqueur-immobilier",
  "fleuriste",
  "pressing",
  "food-truck",
  "consultant-independant",
  "cabinet-assurance",
  "vtc",
  "coach-professionnel",
  "coach-sportif",
  "laverie-automatique",
  "entreprise-de-securite",
  "association",
  "couvreur",
  "peintre-en-batiment",
  "carreleur",
  "climatisation",
  "serrurier",
  "librairie",
  "osteopathe",
  "psychologue",
  "creche",
  "gestionnaire-de-patrimoine",
  "chasseur-immobilier",
  "geometre",
  "daf-externalise",
  "office-manager-externalise",
  "assistant-administratif-externalise",
  "secretariat-externalise",
  "gestionnaire-paie-independant",
  "cabinet-rh-externalise",
  "centre-appels-support-client",
  "societe-recouvrement",
  "centre-affaires-coworking",
  "cabinet-qhse-conformite",
  "bureau-etudes",
  "cabinet-etudes",
  "infogerance-informatique",
  "cybersecurite-pme",
  "integrateur-crm-erp",
  "consultant-data-bi",
  "agence-seo",
  "agence-acquisition-paid-ads",
  "studio-branding-design",
] as const;

export const LEVIER_SOLUTION_PLACEMENTS: readonly SolutionPlacement[] =
  LEVIER_PLACEMENT_SYSTEM_SLUGS.map((systemSlug) => {
    const rank = 1;
    return {
      ...LEVIER_REVIEW,
      placementId: `${systemSlug}:levier:models:${rank}`,
      systemSlug,
      resourceSlug: "levier",
      rank,
      section: "models",
      usage:
        "Suivre l’activité, les finances, les actions et les responsabilités dans un tableau unique.",
      fitRationale:
        "Levier fournit le socle de pilotage commun nécessaire pour exécuter ce système opérationnel.",
      fitConstraints: [
        "Adapter les objectifs, responsables et rythmes de suivi à l’organisation.",
      ],
      editorialStatus: "selected",
      commercialRelationship: "owned",
      status: "published",
      placementVersion: "levier.v1",
      publicationBlockers: [],
    };
  });
