const OPERATIONAL_PROCESS_TITLES: Readonly<Record<string, string>> = {
  "Savoir où va l'entreprise": "Définir et piloter le cap de l’entreprise",
  "Décider au quotidien sans le dirigeant": "Répartir les décisions et les niveaux d’autorité",
  "Donner accès à l'essentiel": "Centraliser et sécuriser les accès essentiels",
  "Garder une visibilité sans reprendre la main": "Piloter l’activité lors d’un point mensuel",
  "Attirer et vendre un chantier": "Acquérir, qualifier et conclure un chantier",
  "Faire revenir les clients": "Fidéliser les clients et organiser les relances",
  "Traiter une réclamation ou un litige client": "Traiter une réclamation ou un litige client",
  "Suivre l'avancement d'un chantier": "Suivre l’avancement d’un chantier",
  "Démarrer et clôturer un chantier": "Démarrer et clôturer un chantier",
  "Tenir chaque corps de métier": "Standardiser les pratiques et contrôler la conformité",
  "Gérer un retard ou un imprévu": "Gérer un retard ou un imprévu",
  "Organiser les équipes, remplacer un absent": "Planifier les équipes et organiser les remplacements",
  "Intégrer un nouvel employé": "Préparer et piloter l’intégration d’un nouvel employé",
  "Suivre la rentabilité": "Tenir les dossiers et piloter la rentabilité de l’activité",
  "Payer à temps": "Planifier et régler les échéances",
  "Se faire payer": "Facturer, suivre et relancer les encaissements",
  "Sécurité et couverture assurance": "Contrôler la sécurité et les couvertures d’assurance",
  "Matériel et fournisseurs": "Gérer le matériel, les commandes et les fournisseurs",
  "Savoir où va l'activité": "Définir et piloter le cap de l’activité",
  "Décider sans bloquer les missions": "Arbitrer et valider les missions sans blocage",
  "Qualifier la mission et le périmètre": "Qualifier la mission et le périmètre",
  "Vendre une mission d'expertise": "Qualifier, proposer et conclure une mission d’expertise",
  "Traiter une réclamation client": "Traiter une réclamation client",
  "Préparer la mission terrain": "Préparer la mission terrain",
  "Réaliser relevés, plans ou constats": "Réaliser relevés, plans ou constats",
  "Produire rapport ou livrable final": "Produire rapport ou livrable final",
  "Organiser les missions et remplacements": "Organiser les missions et remplacements",
  "Suivre la marge et la facturation": "Suivre la marge et la facturation",
  "Tenir les pièces et assurances en règle": "Tenir les pièces et assurances en règle",
  "Décider sans bloquer l'atelier": "Arbitrer et valider l’atelier sans blocage",
  "Qualifier un besoin et établir un devis": "Qualifier un besoin et établir un devis",
  "Ouvrir, suivre et clôturer un ordre de fabrication ou d'intervention": "Ouvrir, suivre et clôturer un ordre de fabrication ou d’intervention",
  "Garantir la qualité de sortie": "Garantir la qualité de sortie",
  "Éviter la rupture de pièces ou matières": "Éviter la rupture de pièces ou matières",
  "Organiser les postes, remplacer un absent et transmettre les consignes": "Organiser les postes, remplacer un absent et transmettre les consignes",
  "Suivre la marge": "Calculer et piloter la marge de production",
  "Entretenir les équipements critiques": "Entretenir les équipements critiques",
  "Décider au quotidien sans tout centraliser": "Décider au quotidien sans tout centraliser",
  "Garder une visibilité d'exploitation": "Piloter l’exploitation lors d’un point régulier",
  "Prendre et qualifier une demande client": "Prendre et qualifier une demande client",
  "Planifier les tournées, trajets ou missions": "Planifier les tournées, trajets ou missions",
  "Suivre l'exécution et gérer les aléas": "Suivre l’exécution et gérer les aléas",
  "Clôturer une mission avec preuve": "Clôturer une mission avec preuve",
  "Remplacer un absent": "Planifier l’équipe, les absences et les remplacements",
  "Payer et encaisser à temps": "Payer et encaisser à temps",
  "Décider sans bloquer le terrain": "Arbitrer et valider le terrain sans blocage",
  "Prendre un nouveau contrat": "Prendre un nouveau contrat",
  "Planifier les interventions ou rondes": "Planifier les interventions ou rondes",
  "Contrôler la bonne exécution": "Contrôler la bonne exécution",
  "Suivre la rentabilité des contrats": "Suivre la rentabilité des contrats",
  "Décider sans bloquer les tournées": "Arbitrer et valider les tournées sans blocage",
  "Accueillir un nouveau bénéficiaire ou patient": "Accueillir un nouveau bénéficiaire ou patient",
  "Traiter une réclamation ou signalement": "Traiter une réclamation ou signalement",
  "Planifier interventions, tournées ou soins": "Planifier interventions, tournées ou soins",
  "Transmettre consignes et observations": "Transmettre consignes et observations",
  "Suivre matériel et incidents": "Suivre matériel et incidents",
  "Organiser remplacements et continuité": "Organiser remplacements et continuité",
  "Suivre facturation et encaissements": "Suivre facturation et encaissements",
  "Tenir droits, prescriptions et justificatifs en règle": "Tenir droits, prescriptions et justificatifs en règle",
  "Fidéliser les clients": "Fidéliser les clients et organiser le suivi régulier",
  "Enregistrer le dépôt client": "Enregistrer le dépôt client",
  "Traiter et contrôler les pièces": "Traiter et contrôler les pièces",
  "Restituer et tracer la livraison": "Restituer et tracer la livraison",
  "Organiser l'équipe et les remplacements": "Organiser l’équipe et les remplacements",
  "Suivre caisse, paniers et marge": "Suivre caisse, paniers et marge",
  "Sécuriser machines, produits et traçabilité": "Sécuriser machines, produits et traçabilité",
  "Attirer de nouveaux clients": "Organiser l’acquisition de nouveaux clients",
  "Vendre (mise en avant, argumentaire)": "Qualifier et conclure les ventes : mise en avant, argumentaire",
  "Traiter une réclamation ou un retour client": "Traiter une réclamation ou un retour client",
  "Ouvrir et fermer la boutique": "Ouvrir et fermer la boutique",
  "Tenir chaque poste": "Standardiser et contrôler chaque poste",
  "Soigner la présentation": "Soigner la présentation",
  "Ne jamais manquer de stock": "Contrôler les stocks et déclencher le réassort",
  "Faire l'inventaire": "Préparer, réaliser et fiabiliser les inventaires",
  "Suivre l'argent et les encaissements": "Piloter la trésorerie, la marge et les documents financiers",
  "Décider sans bloquer l'exploitation": "Arbitrer et valider l’exploitation sans blocage",
  "Informer et rassurer les clients": "Informer et rassurer les clients",
  "Traiter un incident ou une réclamation client": "Traiter un incident ou une réclamation client",
  "Surveiller machines et consommables": "Surveiller machines et consommables",
  "Gérer paiements, pannes et maintenance": "Gérer paiements, pannes et maintenance",
  "Maintenir propreté et sécurité": "Maintenir propreté et sécurité",
  "Organiser interventions et remplacements": "Organiser interventions et remplacements",
  "Suivre encaissements et rentabilité": "Suivre encaissements et rentabilité",
  "Tenir contrôles et affichages en règle": "Tenir contrôles et affichages en règle",
  "Qualifier un besoin ou une réservation": "Qualifier un besoin ou une réservation",
  "Vendre un contrat, service ou séjour": "Qualifier, proposer et conclure un contrat, service ou séjour",
  "Ouvrir et tenir un dossier client ou membre": "Ouvrir et tenir un dossier client ou membre",
  "Gérer réservations, courrier ou services": "Gérer réservations, courrier ou services",
  "Traiter incidents et renouvellements": "Traiter incidents et renouvellements",
  "Organiser l'accueil et les remplacements": "Organiser l’accueil et les remplacements",
  "Suivre encaissements et abonnements": "Suivre encaissements et abonnements",
  "Sécuriser contrats et obligations d'accueil": "Sécuriser contrats et obligations d’accueil",
  "Savoir où va l'agence": "Définir et piloter le cap de l’agence",
  "Décider sans bloquer la production": "Arbitrer et valider la production sans blocage",
  "Garder une visibilité sur la charge": "Piloter la charge lors d’un point mensuel",
  "Développer les prospects et briefs": "Développer les prospects et briefs",
  "Vendre une prestation créative ou digitale": "Qualifier, proposer et conclure une prestation créative ou digitale",
  "Traiter un retour ou une réclamation client": "Traiter un retour ou une réclamation client",
  "Cadrer un brief et un périmètre": "Cadrer un brief et un périmètre",
  "Produire les livrables": "Planifier, produire et contrôler les livrables",
  "Faire valider et livrer": "Organiser la validation client et la livraison",
  "Mesurer les performances ou retours": "Mesurer les performances ou retours",
  "Transmettre un projet en cas d'absence": "Transmettre un projet en cas d’absence",
  "Intégrer un nouveau collaborateur": "Préparer et piloter l’intégration d’un nouveau collaborateur",
  "Suivre la marge projet": "Suivre la marge projet",
  "Sécuriser droits, contrats et accès": "Sécuriser droits, contrats et accès",
  "Décider sans bloquer le quotidien": "Arbitrer et valider le quotidien sans blocage",
  "Garder une visibilité sur les demandes": "Piloter les demandes lors d’un point mensuel",
  "Qualifier la demande client": "Qualifier la demande client",
  "Vendre la bonne prestation de support": "Qualifier, proposer et conclure la bonne prestation de support",
  "Fidéliser les comptes": "Fidéliser les comptes",
  "Prendre et qualifier une demande": "Prendre et qualifier une demande",
  "Traiter le dossier, ticket ou recrutement": "Traiter le dossier, ticket ou recrutement",
  "Suivre les délais et relances": "Suivre les délais et relances",
  "Tracer les échanges et la résolution": "Tracer les échanges et la résolution",
  "Transmettre un dossier en cas d'absence": "Transmettre un dossier en cas d’absence",
  "Suivre la rentabilité des comptes": "Suivre la rentabilité des comptes",
  "Décider sans bloquer les transactions": "Arbitrer et valider les transactions sans blocage",
  "Développer le portefeuille et les mandats": "Développer le portefeuille et les mandats",
  "Qualifier un acquéreur ou un projet": "Qualifier un acquéreur ou un projet",
  "Constituer un dossier bien ou mandat": "Constituer un dossier bien ou mandat",
  "Organiser visites et retours": "Organiser visites et retours",
  "Suivre négociation et signature": "Suivre négociation et signature",
  "Organiser les agents et remplacements": "Organiser les agents et remplacements",
  "Suivre commissions et encaissements": "Suivre commissions et encaissements",
  "Tenir les dossiers et affichages en règle": "Tenir les dossiers et affichages en règle",
  "Décider sans bloquer les dossiers": "Arbitrer et valider les dossiers sans blocage",
  "Garder une visibilité sur le portefeuille": "Piloter le portefeuille lors d’un point mensuel",
  "Qualifier le besoin et le profil client": "Qualifier le besoin et le profil client",
  "Vendre une solution ou un contrat": "Qualifier, proposer et conclure une solution ou un contrat",
  "Constituer un dossier complet": "Constituer un dossier complet",
  "Coordonner partenaires, contrats ou placements": "Coordonner partenaires, contrats ou placements",
  "Suivre les échéances, commissions ou encours": "Suivre les échéances, commissions ou encours",
  "Traiter un incident, une alerte ou un sinistre": "Traiter un incident, une alerte ou un sinistre",
  "Organiser les portefeuilles et remplacements": "Organiser les portefeuilles et remplacements",
  "Suivre la rentabilité du portefeuille": "Suivre la rentabilité du portefeuille",
  "Sécuriser conformité réglementaire": "Sécuriser conformité réglementaire",
  "Savoir où va le cabinet": "Définir et piloter le cap du cabinet",
  "Développer les dossiers et recommandations": "Développer les dossiers et recommandations",
  "Vendre une mission ou un accompagnement": "Qualifier, proposer et conclure une mission ou un accompagnement",
  "Fidéliser les clients du cabinet": "Fidéliser les clients du cabinet",
  "Ouvrir et tenir un dossier client": "Ouvrir et tenir un dossier client",
  "Produire et contrôler les livrables": "Produire et contrôler les livrables",
  "Gérer les échéances et relances": "Gérer les échéances et relances",
  "Tracer les validations et décisions": "Tracer les validations et décisions",
  "Organiser les collaborateurs et remplacements": "Organiser les collaborateurs et remplacements",
  "Suivre la rentabilité des dossiers": "Suivre la rentabilité des dossiers",
  "Sécuriser confidentialité et obligations métier": "Sécuriser confidentialité et obligations métier",
  "Décider sans tout reprendre soi-même": "Décider sans tout reprendre soi-même",
  "Garder une visibilité sur les missions": "Piloter les missions lors d’un point mensuel",
  "Développer les opportunités": "Développer les opportunités",
  "Vendre une mission claire": "Qualifier, proposer et conclure une mission claire",
  "Cadrer une mission ou une étude": "Cadrer une mission ou une étude",
  "Collecter les informations utiles": "Collecter les informations utiles",
  "Produire l'analyse ou le livrable": "Produire l’analyse ou le livrable",
  "Restituer et suivre les décisions": "Restituer et suivre les décisions",
  "Transmettre une mission en cas d'absence": "Transmettre une mission en cas d’absence",
  "Suivre la marge des missions": "Suivre la marge des missions",
  "Sécuriser contrats et confidentialité": "Sécuriser contrats et confidentialité",
  "Développer les biens et voyageurs": "Développer les biens et voyageurs",
  "Traiter un avis ou une réclamation": "Traiter un avis ou une réclamation",
  "Gérer annonces, réservations et calendrier": "Gérer annonces, réservations et calendrier",
  "Organiser préparation, arrivées et départs": "Organiser préparation, arrivées et départs",
  "Traiter maintenance et incidents voyageurs": "Traiter maintenance et incidents voyageurs",
  "Organiser équipes terrain et remplacements": "Organiser équipes terrain et remplacements",
  "Suivre revenus, commissions et frais": "Suivre revenus, commissions et frais",
  "Tenir règlements, accès et justificatifs en règle": "Tenir règlements, accès et justificatifs en règle",
  "Développer les mandats de gestion": "Développer les mandats de gestion",
  "Traiter une réclamation propriétaire ou locataire": "Traiter une réclamation propriétaire ou locataire",
  "Entrer un bien et préparer la mise en location": "Entrer un bien et préparer la mise en location",
  "Suivre loyers, quittances et incidents": "Suivre loyers, quittances et incidents",
  "Gérer départs, travaux et relocation": "Gérer départs, travaux et relocation",
  "Organiser les gestionnaires et remplacements": "Organiser les gestionnaires et remplacements",
  "Suivre flux, honoraires et encaissements": "Suivre flux, honoraires et encaissements",
  "Tenir baux, états des lieux et obligations en règle": "Tenir baux, états des lieux et obligations en règle",
  "Garder une visibilité sur le parc ou les projets": "Piloter le parc ou les projets lors d’un point mensuel",
  "Qualifier le besoin technique": "Qualifier le besoin technique",
  "Vendre une prestation ou un abonnement": "Qualifier, proposer et conclure une prestation ou un abonnement",
  "Fidéliser les comptes clients": "Fidéliser les comptes clients",
  "Cadrer un parc, un projet ou une intervention": "Cadrer un parc, un projet ou une intervention",
  "Déployer, paramétrer ou intervenir": "Déployer, paramétrer ou intervenir",
  "Suivre incidents, maintenance et support": "Suivre incidents, maintenance et support",
  "Documenter et sécuriser les accès": "Documenter et sécuriser les accès",
  "Organiser l'équipe et les astreintes": "Organiser l’équipe et les astreintes",
  "Suivre la marge projet ou récurrente": "Suivre la marge projet ou récurrente",
  "Sécuriser contrats, données et continuité": "Sécuriser contrats, données et continuité",
  "Vendre (offre claire)": "Qualifier et conclure les ventes : offre claire",
  "Ouvrir et fermer le point de vente": "Ouvrir et fermer le point de vente",
  "Préparer les plats de façon identique": "Préparer les plats de façon identique",
  "Tenir chaque poste de travail": "Standardiser et contrôler chaque poste de travail",
  "Vérifier la qualité en continu": "Vérifier la qualité en continu",
  "Respecter l'hygiène alimentaire": "Respecter l’hygiène alimentaire",
  "Traiter une non-conformité hygiène": "Traiter une non-conformité hygiène",
  "Éviter l'arrêt par panne": "Planifier l’entretien et traiter les pannes",
  "Savoir où va l'association": "Définir et piloter le cap de l’association",
  "Répartir les rôles de gouvernance": "Définir et suivre les responsabilités de gouvernance",
  "Recruter et fidéliser membres, bénéficiaires ou partenaires": "Recruter et fidéliser membres, bénéficiaires ou partenaires",
  "Traiter une réclamation ou un signalement": "Traiter une réclamation ou un signalement",
  "Organiser une action, un événement ou un accompagnement": "Organiser une action, un événement ou un accompagnement",
  "Coordonner salariés et bénévoles": "Coordonner salariés et bénévoles",
  "Suivre budget, encaissements, subventions et trésorerie": "Suivre budget, encaissements, subventions et trésorerie",
  "Payer à temps et justifier les dépenses": "Planifier les paiements et justifier les dépenses",
  "Développer les inscriptions": "Développer les inscriptions",
  "Vendre une formule de conduite": "Qualifier, proposer et conclure une formule de conduite",
  "Traiter une réclamation élève": "Traiter une réclamation élève",
  "Gérer inscriptions et dossiers élèves": "Gérer inscriptions et dossiers élèves",
  "Planifier heures, moniteurs et véhicules": "Planifier heures, moniteurs et véhicules",
  "Suivre progression et examens": "Suivre progression et examens",
  "Suivre véhicules et incidents": "Suivre véhicules et incidents",
  "Organiser les moniteurs et remplacements": "Organiser les moniteurs et remplacements",
  "Suivre paiements, forfaits et heures": "Suivre paiements, forfaits et heures",
  "Suivre financements et relances": "Suivre financements et relances",
  "Tenir dossiers élèves et véhicules en règle": "Tenir dossiers élèves et véhicules en règle",
  "Décider sans bloquer les séances": "Arbitrer et valider les séances sans blocage",
  "Attirer de nouveaux adhérents ou clients": "Attirer de nouveaux adhérents ou clients",
  "Vendre un abonnement ou accompagnement": "Qualifier, proposer et conclure un abonnement ou accompagnement",
  "Planifier cours, séances ou programmes": "Planifier cours, séances ou programmes",
  "Suivre progression et assiduité": "Suivre progression et assiduité",
  "Entretenir équipements et locaux": "Entretenir équipements et locaux",
  "Organiser coachs et remplacements": "Organiser coachs et remplacements",
  "Suivre abonnements, paiements et marge": "Suivre abonnements, paiements et marge",
  "Tenir consignes, assurances et affichages en règle": "Tenir consignes, assurances et affichages en règle",
  "Attirer les clients": "Acquérir et convertir de nouveaux clients",
  "Vendre (offre de prestation claire)": "Qualifier et conclure les ventes : offre de prestation claire",
  "Gérer les rendez-vous, fidéliser": "Fidéliser les clients et collecter leurs avis",
  "Ouvrir et fermer l'établissement": "Ouvrir et fermer l’établissement",
  "Standardiser une prestation": "Standardiser une prestation",
  "Suivre l'argent": "Piloter les finances et tenir les documents administratifs",
  "Respecter l'hygiène": "Appliquer et contrôler les règles d’hygiène",
  "Être couvert et en règle": "Maintenir les assurances et obligations à jour",
  "Savoir où va le portefeuille": "Définir et piloter le cap du portefeuille",
  "Décider sans bloquer les arbitrages": "Arbitrer et valider les arbitrages sans blocage",
  "Sourcer des opportunités": "Sourcer des opportunités",
  "Traiter un litige ou une réclamation": "Traiter un litige ou une réclamation",
  "Analyser la rentabilité et le montage": "Analyser la rentabilité et le montage",
  "Suivre acquisition, travaux ou mise en location": "Suivre acquisition, travaux ou mise en location",
  "Piloter exploitation, revente ou arbitrage": "Piloter exploitation, revente ou arbitrage",
  "Organiser partenaires et remplacements": "Organiser partenaires et remplacements",
  "Suivre trésorerie, rendement et marge": "Suivre trésorerie, rendement et marge",
  "Tenir les pièces, actes et diagnostics en règle": "Tenir les pièces, actes et diagnostics en règle",
  "Sourcer opportunités et investisseurs": "Sourcer opportunités et investisseurs",
  "Traiter une réclamation investisseur ou partenaire": "Traiter une réclamation investisseur ou partenaire",
  "Analyser risque, allocation ou due diligence": "Analyser risque, allocation ou due diligence",
  "Suivre décisions d'investissement": "Suivre décisions d’investissement",
  "Piloter reporting et performance": "Piloter reporting et performance",
  "Organiser analyses et remplacements": "Organiser analyses et remplacements",
  "Suivre encours, frais et revenus": "Suivre encours, frais et revenus",
  "Sécuriser conformité et documentation": "Sécuriser conformité et documentation",
  "Décider sans bloquer les consultations": "Arbitrer et valider les consultations sans blocage",
  "Organiser prise de rendez-vous et accueil": "Organiser prise de rendez-vous et accueil",
  "Tenir dossier, consentements et documents": "Tenir dossier, consentements et documents",
  "Dérouler consultation, soin ou suivi": "Dérouler consultation, soin ou suivi",
  "Gérer matériel, stérilisation ou stock médical": "Gérer matériel, stérilisation ou stock médical",
  "Organiser praticiens et remplacements": "Organiser praticiens et remplacements",
  "Sécuriser confidentialité et obligations santé": "Sécuriser confidentialité et obligations santé",
  "Décider sans bloquer les événements": "Arbitrer et valider les événements sans blocage",
  "Qualifier le brief et le budget": "Qualifier le brief et le budget",
  "Vendre une prestation événementielle": "Qualifier, proposer et conclure une prestation événementielle",
  "Préparer planning, prestataires et logistique": "Préparer planning, prestataires et logistique",
  "Piloter le jour J et les imprévus": "Piloter le jour J et les imprévus",
  "Clôturer, faire le bilan et relancer": "Clôturer, faire le bilan et relancer",
  "Suivre marge, acomptes et règlements": "Suivre marge, acomptes et règlements",
  "Sécuriser contrats et assurances": "Sécuriser contrats et assurances",
  "Savoir où va le portefeuille copropriété": "Définir et piloter le cap du portefeuille de copropriétés",
  "Développer ou renouveler des mandats": "Développer ou renouveler des mandats",
  "Traiter une réclamation copropriétaire ou occupant": "Traiter une réclamation copropriétaire ou occupant",
  "Tenir la copropriété et ses lots": "Tenir la copropriété et ses lots",
  "Préparer assemblées générales et décisions": "Préparer assemblées générales et décisions",
  "Suivre appels de fonds, travaux et incidents": "Suivre appels de fonds, travaux et incidents",
  "Organiser gestionnaires et remplacements": "Organiser gestionnaires et remplacements",
  "Suivre flux, appels de fonds et impayés": "Suivre flux, appels de fonds et impayés",
  "Tenir procès-verbaux, contrats et obligations en règle": "Tenir procès-verbaux, contrats et obligations en règle",
  "Savoir où va la structure": "Définir et piloter le cap de la structure",
  "Décider sans bloquer l'accueil": "Arbitrer et valider l’accueil sans blocage",
  "Gérer préinscriptions et familles": "Gérer préinscriptions et familles",
  "Organiser accueil, présences et transmissions": "Organiser accueil, présences et transmissions",
  "Suivre repas, soins et sécurité": "Suivre repas, soins et sécurité",
  "Préparer activités et continuité": "Préparer activités et continuité",
  "Suivre contrats, facturation et aides": "Suivre contrats, facturation et aides",
  "Tenir agréments, protocoles et obligations en règle": "Tenir agréments, protocoles et obligations en règle",
  "Décider sans reprendre toutes les opérations": "Décider sans reprendre toutes les opérations",
  "Gérer les réservations et la relation client": "Gérer les réservations et la relation client",
  "Traiter un avis négatif ou une réclamation": "Traiter un avis négatif ou une réclamation",
  "Organiser arrivées, départs et ménage": "Organiser arrivées, départs et ménage",
  "Traiter un incident sur site": "Traiter un incident sur site",
  "Remplacer un absent et transmettre les consignes": "Remplacer un absent et transmettre les consignes",
  "Suivre le chiffre et les encaissements": "Suivre le chiffre et les encaissements",
  "Savoir où va la plateforme": "Définir et piloter le cap de la plateforme",
  "Décider sans bloquer la plateforme": "Arbitrer et valider la plateforme sans blocage",
  "Recruter vendeurs et acheteurs": "Recruter vendeurs et acheteurs",
  "Publier et contrôler les offres": "Publier et contrôler les offres",
  "Modérer la plateforme et les incidents": "Modérer la plateforme et les incidents",
  "Suivre commandes, retours et coordination vendeurs": "Suivre commandes, retours et coordination vendeurs",
  "Organiser support et modération": "Organiser support et modération",
  "Suivre commissions, paiements et performance": "Suivre commissions, paiements et performance",
  "Se faire payer et reverser": "Encaisser, rapprocher et reverser les paiements",
  "Décider sans bloquer l'exécution": "Arbitrer et valider l’exécution sans blocage",
  "Attirer du trafic qualifié": "Attirer du trafic qualifié",
  "Convertir les visiteurs": "Convertir les visiteurs",
  "Maintenir le catalogue et la boutique en ligne": "Maintenir le catalogue et la boutique en ligne",
  "Préparer commandes et expéditions": "Préparer commandes et expéditions",
  "Gérer retours, support et litiges": "Gérer retours, support et litiges",
  "Organiser support et exécution": "Organiser support et exécution",
  "Suivre ventes, panier et marge": "Suivre ventes, panier et marge",
  "Sécuriser les encaissements": "Sécuriser les encaissements",
  "Savoir où va l'organisme": "Définir et piloter le cap de l’organisme",
  "Vendre une formation": "Qualifier, proposer et conclure une formation",
  "Fidéliser apprenants et clients": "Fidéliser apprenants et clients",
  "Traiter une réclamation apprenant ou client": "Traiter une réclamation apprenant ou client",
  "Construire et mettre à jour une formation": "Construire et mettre à jour une formation",
  "Planifier sessions, formateurs et ressources": "Planifier sessions, formateurs et ressources",
  "Suivre présences, évaluations et attestations": "Suivre présences, évaluations et attestations",
  "Gérer dossiers clients et financeurs": "Gérer dossiers clients et financeurs",
  "Gérer les formateurs et intervenants": "Gérer les formateurs et intervenants",
  "Intégrer un nouveau collaborateur et remplacer un formateur absent": "Intégrer un nouveau collaborateur et remplacer un formateur absent",
  "Suivre l'activité et la marge": "Suivre l’activité et la marge",
  "Maintenir la conformité qualité": "Maintenir la conformité qualité",
  "Savoir où va le CFA": "Définir et piloter le cap du CFA",
  "Développer les entreprises partenaires (employeurs)": "Développer les entreprises partenaires (employeurs)",
  "Recruter des apprentis": "Recruter des apprentis",
  "Fidéliser employeurs et apprentis": "Fidéliser employeurs et apprentis",
  "Traiter une réclamation apprenti ou employeur": "Traiter une réclamation apprenti ou employeur",
  "Construire un contenu de formation": "Construire un contenu de formation",
  "Dérouler une session/année de formation": "Dérouler une session/année de formation",
  "Planifier cours, salles et intervenants": "Planifier cours, salles et intervenants",
  "Suivre l'alternance employeur-apprenti": "Suivre l’alternance employeur-apprenti",
  "Se faire payer (sécuriser les financements)": "Sécuriser les financements et suivre les encaissements",
  "Rester certifié": "Maintenir les certifications et preuves de conformité",
  "Publier et suivre les résultats (obligation légale)": "Publier et suivre les résultats (obligation légale)",
  "Respecter les obligations spécifiques": "Respecter les obligations spécifiques",
  "Attirer de nouveaux apprenants": "Attirer de nouveaux apprenants",
  "Vendre un parcours en ligne": "Qualifier, proposer et conclure un parcours en ligne",
  "Traiter une demande ou une réclamation apprenant": "Traiter une demande ou une réclamation apprenant",
  "Créer et publier un contenu pédagogique": "Créer et publier un contenu pédagogique",
  "Gérer la plateforme et les accès": "Gérer la plateforme et les accès",
  "Suivre progression, évaluations et certificats": "Suivre progression, évaluations et certificats",
  "Mettre à jour les contenus": "Contrôler et mettre à jour les contenus de formation",
  "Coordonner formateurs, support et production": "Coordonner formateurs, support et production",
  "Suivre revenus, abonnements et marge": "Suivre revenus, abonnements et marge",
  "Gérer remboursements et litiges": "Gérer remboursements et litiges",
  "Maintenir qualité et conformité": "Maintenir qualité et conformité",
  "Savoir où va l'officine": "Définir et piloter le cap de l’officine",
  "Décider sans bloquer le comptoir": "Arbitrer et valider le comptoir sans blocage",
  "Accueillir et orienter les clients": "Accueillir et orienter les clients",
  "Servir ordonnances et demandes comptoir": "Servir ordonnances et demandes comptoir",
  "Suivre stock, commandes et ruptures": "Suivre stock, commandes et ruptures",
  "Piloter missions santé et traçabilité": "Piloter missions santé et traçabilité",
  "Suivre encaissements et tiers payant": "Suivre encaissements et tiers payant",
  "Tenir l'officine et les obligations en règle": "Tenir l’officine et les obligations en règle"
};

export function getOperationalProcessTitle(sourceTitle: string): string {
  return OPERATIONAL_PROCESS_TITLES[sourceTitle] ?? sourceTitle;
}
