const EM2A_FIRM_NAME = "EM2A Expertise";
const EM2A_PROFILE_URL =
  "https://demaa.fr/annuaire-experts-comptables/cabinets/em2a-expertise";

export const plumbingDemoCompany = {
  name: "Plomberie Horizon",
  fictional: true,
  firstForecastMonth: "2026-08-01",
  activityUnit: "Chantiers",
  objectives: [
    {
      targetDate: "2026-12-01",
      monthlyRevenue: 45_000,
      operatingMargin: 0.18,
    },
    {
      targetDate: "2027-07-01",
      monthlyRevenue: 52_000,
      operatingMargin: 0.2,
    },
  ],
} as const;

export const plumbingDemoPeople = {
  director: "Amina Benali",
  administration: "Sarah Martin",
  siteManager: "Lucas Bernard",
  planning: "Inès Robert",
  technician: "Mehdi Traoré",
} as const;

export const plumbingDemoActionPlanning = [
  {
    owner: plumbingDemoPeople.director,
    priority: "P1",
    start: "2026-06-02",
    due: "2026-06-20",
    status: "Terminée",
    note: "Dépannage, chauffe-eau et rénovation ciblés sur un rayon de 25 km.",
  },
  {
    owner: plumbingDemoPeople.director,
    priority: "P1",
    start: "2026-06-09",
    due: "2026-06-30",
    status: "Terminée",
    note: "Seuil d’achat autonome fixé à 150 € ; urgences gaz toujours escaladées.",
  },
  {
    owner: plumbingDemoPeople.director,
    priority: "P1",
    start: "2026-07-01",
    due: "2026-08-15",
    status: "En cours",
    note: "Lucas remplace la dirigeante pour les arbitrages chantier.",
  },
  {
    owner: plumbingDemoPeople.administration,
    priority: "P1",
    start: "2026-06-16",
    due: "2026-07-10",
    status: "Terminée",
    note: "Dossiers clients, devis et factures centralisés.",
  },
  {
    owner: plumbingDemoPeople.administration,
    priority: "P2",
    start: "2026-07-15",
    due: "2026-08-31",
    status: "En cours",
    note: "Accès de secours à tester avec la dirigeante.",
  },
  {
    owner: plumbingDemoPeople.administration,
    priority: "P1",
    start: "2026-05-20",
    due: "2026-06-15",
    status: "Terminée",
    note: "Fiche complétée avec services, zones, horaires et 24 photos.",
  },
  {
    owner: plumbingDemoPeople.director,
    priority: "P2",
    start: "2026-07-06",
    due: "2026-09-15",
    status: "En cours",
    note: "Pages prioritaires : urgence, chauffe-eau et rénovation salle de bain.",
  },
  {
    owner: plumbingDemoPeople.director,
    priority: "P2",
    start: "2026-09-01",
    due: "2026-10-15",
    status: "À faire",
    note: "Budget test prévu : 900 € sur quatre semaines.",
  },
  {
    owner: plumbingDemoPeople.siteManager,
    priority: "P1",
    start: "2026-07-01",
    due: "2026-08-31",
    status: "En cours",
    note: "Première checklist : remplacement de chauffe-eau.",
  },
  {
    owner: plumbingDemoPeople.siteManager,
    priority: "P1",
    start: "2026-08-01",
    due: "2026-09-30",
    status: "À faire",
    note: "Ajouter les contrôles et photos obligatoires à chaque checklist.",
  },
  {
    owner: plumbingDemoPeople.planning,
    priority: "P2",
    start: "2026-07-20",
    due: "2026-08-20",
    status: "En cours",
    note: "Deux sous-traitants et une agence d’intérim à qualifier.",
  },
  {
    owner: plumbingDemoPeople.administration,
    priority: "P1",
    start: "2026-08-01",
    due: "2026-08-31",
    status: "À planifier",
    note: "Inclure TVA, salaires, assurances, véhicules et fournisseurs.",
  },
  {
    owner: plumbingDemoPeople.planning,
    priority: "P2",
    start: "2026-08-10",
    due: "2026-09-15",
    status: "En cours",
    note: "Alerte pilote sur raccords, joints, vannes et flexibles.",
  },
  {
    owner: plumbingDemoPeople.siteManager,
    priority: "P2",
    start: "2026-09-01",
    due: "2026-10-15",
    status: "À faire",
    note: "Inventaire prévu par véhicule avec signature du technicien.",
  },
] as const;

export const plumbingDemoTeamAssignments = [
  {
    role: "Dirigeant",
    person: plumbingDemoPeople.director,
    situation: "En poste",
    note: "Société fictive - fondatrice et dirigeante.",
  },
  {
    role: "Administration et facturation",
    person: plumbingDemoPeople.administration,
    situation: "En poste",
    note: "Rôle cumulé avec la relation client.",
  },
  {
    role: "Commercial et relation client",
    person: plumbingDemoPeople.administration,
    situation: "En poste",
    note: "Rôle cumulé avec l’administration.",
  },
  {
    role: "Responsable de chantier",
    person: plumbingDemoPeople.siteManager,
    situation: "En poste",
    note: "Référent pour les arbitrages terrain.",
  },
  {
    role: "Référent technique",
    person: plumbingDemoPeople.siteManager,
    situation: "En poste",
    note: "Rôle cumulé avec la responsabilité chantier.",
  },
  {
    role: "Planification des équipes",
    person: plumbingDemoPeople.planning,
    situation: "En poste",
    note: "Planification, achats courants et remplacements.",
  },
  {
    role: "Référent sécurité",
    person: plumbingDemoPeople.siteManager,
    situation: "En poste",
    note: "Revue mensuelle avec la dirigeante.",
  },
  {
    role: "Achats et stock",
    person: plumbingDemoPeople.planning,
    situation: "En poste",
    note: "Rôle cumulé avec la planification.",
  },
  {
    role: "Technicien plombier-chauffagiste",
    person: plumbingDemoPeople.technician,
    situation: "En poste",
    note: "Technicien autonome sur dépannage et chauffe-eau.",
  },
] as const;

export const plumbingDemoRevenue = {
  historyAndForecast: [
    32_800, 35_100, 36_600, 38_200, 39_500, 41_000, 42_500, 43_800,
    45_500, 47_200, 36_000, 39_000, 41_500, 44_000, 46_000,
  ],
  projection: [
    42_000, 43_500, 45_000, 47_000, 49_000, 50_500, 52_000, 54_000,
    55_500, 57_000, 58_500, 60_000,
  ],
} as const;

export const plumbingDemoActivityVolume = {
  historyAndForecast: [
    42, 44, 46, 48, 50, 51, 53, 54, 56, 58, 45, 49, 52, 55, 57,
  ],
  projection: [52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 71, 72],
} as const;

export const plumbingDemoMarketingCalendar = [
  [
    "2026-08-03",
    "Visibilité locale",
    "Publier trois photos avant/après sur Google Business Profile",
    "Google Business Profile",
    plumbingDemoPeople.administration,
    "En cours",
    "Une publication chaque semaine pendant un mois.",
  ],
  [
    "2026-08-17",
    "Conversion",
    "Activer les relances de devis à J+2 et J+7",
    "Email et téléphone",
    plumbingDemoPeople.administration,
    "À faire",
    "Commencer par les devis supérieurs à 1 500 €.",
  ],
  [
    "2026-09-01",
    "Acquisition",
    "Tester une campagne locale chauffe-eau",
    "Google Ads",
    plumbingDemoPeople.director,
    "À faire",
    "Budget test de 900 €.",
  ],
  [
    "2026-09-15",
    "Fidélisation",
    "Envoyer le SMS de demande d’avis après chaque intervention",
    "SMS",
    plumbingDemoPeople.administration,
    "À faire",
    "Lien direct vers la fiche Google.",
  ],
  [
    "2026-10-01",
    "Fidélisation",
    "Lancer les rappels d’entretien chaudière",
    "Email et SMS",
    plumbingDemoPeople.administration,
    "Planifié",
    "Cibler les clients dont l’entretien date de 10 à 12 mois.",
  ],
  [
    "2026-10-19",
    "Partenariats",
    "Contacter cinq syndics et agences immobilières locales",
    "Téléphone et email",
    plumbingDemoPeople.director,
    "Planifié",
    "Proposer un contact prioritaire pour les urgences.",
  ],
] as const;

export const plumbingDemoEcosystem = [
  [
    "Outil métier",
    "Devis, planning et facturation",
    "Obat",
    "Obat",
    "Choisi",
    "Voir tarif actuel",
    "2026-08-31",
    "https://demaa.fr/annuaire-outils/obat",
    "Logiciel central retenu pour les devis, factures, acomptes et situations de travaux.",
  ],
  [
    "Professionnel",
    "Comptabilité et TVA",
    EM2A_FIRM_NAME,
    EM2A_FIRM_NAME,
    "Déjà utilisé",
    "Sur devis",
    "2026-12-31",
    EM2A_PROFILE_URL,
    "Point mensuel prévu le 10.",
  ],
  [
    "Fournisseur",
    "Pièces courantes et livraisons chantier",
    "CEDEO",
    "CEDEO",
    "Choisi",
    "Selon commandes",
    "2026-09-30",
    "https://demaa.fr/annuaire-fournisseurs/cedeo-pro",
    "Comparer prix, délai et erreurs de livraison.",
  ],
  [
    "Fournisseur",
    "Outillage, consommables, visserie et EPI",
    "Würth",
    "Würth",
    "Déjà utilisé",
    "Selon commandes",
    "2026-09-30",
    "https://demaa.fr/annuaire-fournisseurs/wurth",
    "Liste d’articles récurrents à négocier avec les conditions professionnelles.",
  ],
  [
    "Fournisseur",
    "Location ponctuelle de matériel de chantier",
    "Kiloutou",
    "Kiloutou",
    "À étudier",
    "Selon location",
    "2026-10-15",
    "https://demaa.fr/annuaire-fournisseurs/kiloutou",
    "Louer lorsque le matériel n’a pas d’usage suffisamment récurrent pour être acheté.",
  ],
  [
    "Banque / assurance / financement",
    "Décennale et responsabilité civile",
    "Orus",
    "Orus",
    "À comparer",
    "Sur devis",
    "2026-11-15",
    "https://demaa.fr/annuaire-fournisseurs/orus",
    "Attestation à renouveler avant échéance.",
  ],
] as const;
