export type ProNetworkCategory =
  | "Officiel"
  | "Réseau"
  | "Prescripteur"
  | "Événement";

export type DemaaProNetwork = {
  slug: string;
  name: string;
  category: ProNetworkCategory;
  shortDescription: string;
  description: string;
  bestFor: string;
  tags: string[];
  icon: string;
  usefulFor: string[];
  href: string;
  cta: string;
};

export const demaaProNetworks = [
  {
    slug: "ordre-experts-comptables",
    name: "Ordre des experts-comptables",
    category: "Officiel",
    shortDescription: "L’instance de référence pour la profession comptable.",
    description:
      "Instance officielle utile pour la crédibilité du cabinet, la lecture du cadre métier et l’accès à l’écosystème de la profession.",
    bestFor: "Les cabinets comptables qui veulent renforcer leur positionnement et leur visibilité institutionnelle.",
    tags: ["Officiel", "Crédibilité", "Profession"],
    icon: "Scale",
    usefulFor: ["Crédibilité", "Profession", "Veille"],
    href: "https://www.experts-comptables.org/",
    cta: "Voir le site officiel",
  },
  {
    slug: "croec-regional",
    name: "CROEC régional",
    category: "Officiel",
    shortDescription: "Le relais régional de l’Ordre des experts-comptables.",
    description:
      "Point d’appui régional pour les cabinets qui veulent se connecter à la profession, suivre l’actualité locale et renforcer leur présence sur leur territoire.",
    bestFor: "Les cabinets qui développent leur réseau local et veulent mieux s’ancrer dans leur région.",
    tags: ["Officiel", "Réseau local", "Profession"],
    icon: "Building2",
    usefulFor: ["Local", "Crédibilité", "Réseau"],
    href: "https://www.experts-comptables.fr/l-institution/notre-presence-en-region",
    cta: "Trouver son conseil régional",
  },
  {
    slug: "capeb",
    name: "CAPEB",
    category: "Réseau",
    shortDescription: "Confédération utile aux artisans du bâtiment.",
    description:
      "Réseau métier important pour les artisans du bâtiment : accompagnement, représentation, informations secteur et ancrage local.",
    bestFor: "Les entreprises artisanales du bâtiment qui veulent gagner en crédibilité et rester connectées à leur métier.",
    tags: ["Fédération", "Réseau métier", "Crédibilité"],
    icon: "Hammer",
    usefulFor: ["Bâtiment", "Veille", "Crédibilité"],
    href: "https://www.capeb.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "ffb",
    name: "FFB",
    category: "Réseau",
    shortDescription: "Organisation de référence pour les entreprises du bâtiment.",
    description:
      "Fédération structurante pour suivre le secteur, gagner en crédibilité et accéder à un réseau professionnel plus large dans le BTP.",
    bestFor: "Les entreprises du bâtiment qui veulent se structurer et rester visibles dans leur écosystème métier.",
    tags: ["Fédération", "Veille", "Crédibilité"],
    icon: "Building2",
    usefulFor: ["BTP", "Veille", "Réseau"],
    href: "https://www.ffbatiment.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "cci-locale",
    name: "CCI locale",
    category: "Réseau",
    shortDescription: "Le réseau local le plus simple pour rencontrer d’autres dirigeants.",
    description:
      "La chambre de commerce et d’industrie reste un point d’entrée clair pour rencontrer des dirigeants, suivre des événements et gagner en visibilité locale.",
    bestFor: "Les dirigeants qui veulent développer leur ancrage local et créer des opportunités business sur leur territoire.",
    tags: ["Réseau local", "Business", "Événement"],
    icon: "Globe2",
    usefulFor: ["Local", "Business", "Événements"],
    href: "https://www.cci.fr/",
    cta: "Trouver sa CCI",
  },
  {
    slug: "cma",
    name: "Chambre de métiers et de l’artisanat",
    category: "Officiel",
    shortDescription: "Le repère institutionnel clé pour beaucoup d’activités artisanales.",
    description:
      "La CMA aide les artisans à se repérer dans leur environnement métier et local, avec un rôle utile sur la crédibilité et l’écosystème terrain.",
    bestFor: "Les artisans qui veulent un ancrage institutionnel et local plus fort.",
    tags: ["Officiel", "Artisanat", "Local"],
    icon: "Building2",
    usefulFor: ["Artisanat", "Crédibilité", "Local"],
    href: "https://www.artisanat.fr/",
    cta: "Voir la CMA",
  },
  {
    slug: "architectes-locaux",
    name: "Ordre des architectes",
    category: "Prescripteur",
    shortDescription: "L’instance nationale qui rassemble et représente les architectes.",
    description:
      "Le Conseil national de l’Ordre des architectes donne accès au cadre professionnel et à l’écosystème des architectes en France.",
    bestFor: "Les architectes et entreprises du bâtiment qui veulent identifier le réseau professionnel de référence.",
    tags: ["Prescripteur", "Partenariat", "Business"],
    icon: "Target",
    usefulFor: ["Apport d’affaires", "Partenariat", "BTP"],
    href: "https://www.architectes.org/",
    cta: "Voir l’écosystème",
  },
  {
    slug: "maitres-oeuvre",
    name: "UNSFA",
    category: "Prescripteur",
    shortDescription: "L’Union nationale des syndicats français d’architectes.",
    description:
      "Réseau professionnel et territorial des syndicats d’architectes, avec événements, ressources et représentation de la profession.",
    bestFor: "Les architectes et partenaires du bâtiment qui veulent se rapprocher d’un réseau professionnel structuré.",
    tags: ["Prescripteur", "Business", "Partenariat"],
    icon: "Boxes",
    usefulFor: ["Chantier", "Partenariat", "Business"],
    href: "https://www.unsfa.fr/",
    cta: "Explorer ce réseau",
  },
  {
    slug: "agences-immobilieres-locales",
    name: "Annuaire FNAIM",
    category: "Prescripteur",
    shortDescription: "L’annuaire officiel des agences et spécialistes adhérents à la FNAIM.",
    description:
      "Le moteur FNAIM permet d’identifier des professionnels de l’immobilier par territoire et par spécialité.",
    bestFor: "Les entreprises travaux et bâtiment qui veulent créer des apports d’affaires récurrents localement.",
    tags: ["Prescripteur", "Local", "Business"],
    icon: "Building2",
    usefulFor: ["Local", "Apport d’affaires", "Immobilier"],
    href: "https://www.fnaim.fr/4372-trouver-une-agence-immobiliere-fnaim.htm",
    cta: "Ouvrir l’annuaire",
  },
  {
    slug: "fnaim",
    name: "FNAIM",
    category: "Réseau",
    shortDescription: "Le réseau de référence le plus visible de l’immobilier.",
    description:
      "Organisation structurante pour les professionnels de l’immobilier, utile pour la crédibilité, la veille sectorielle et le réseau métier.",
    bestFor: "Les agences immobilières et acteurs de l’immobilier qui veulent renforcer leur présence métier.",
    tags: ["Réseau métier", "Immobilier", "Crédibilité"],
    icon: "Building2",
    usefulFor: ["Immobilier", "Veille", "Crédibilité"],
    href: "https://www.fnaim.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "unis",
    name: "UNIS",
    category: "Réseau",
    shortDescription: "Un réseau clé pour les professionnels de l’immobilier et de la gestion.",
    description:
      "L’UNIS donne un cadre réseau utile pour les métiers de l’immobilier, de l’administration de biens et du syndic.",
    bestFor: "Les pros de l’immobilier qui veulent renforcer leur ancrage métier et leur veille.",
    tags: ["Réseau métier", "Immobilier", "Veille"],
    icon: "Globe2",
    usefulFor: ["Immobilier", "Réseau", "Veille"],
    href: "https://www.unis-immo.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "notaires",
    name: "Notaires de France",
    category: "Prescripteur",
    shortDescription: "Des partenaires-clés dans beaucoup d’opérations immobilières et patrimoniales.",
    description:
      "Les notaires peuvent devenir des relais stratégiques sur les transactions, dossiers patrimoniaux ou moments de structuration.",
    bestFor: "Les métiers immobiliers, patrimoniaux et cabinets qui travaillent autour de la transmission et des transactions.",
    tags: ["Prescripteur", "Partenariat", "Crédibilité"],
    icon: "Scale",
    usefulFor: ["Immobilier", "Patrimoine", "Partenariat"],
    href: "https://www.notaires.fr/",
    cta: "Voir l’écosystème",
  },
  {
    slug: "avocats-affaires",
    name: "Conseil national des barreaux",
    category: "Prescripteur",
    shortDescription: "L’institution représentative de la profession d’avocat en France.",
    description:
      "Le CNB centralise les ressources, annuaires, événements et informations officielles utiles à la profession d’avocat.",
    bestFor: "Les cabinets d’avocats et partenaires qui recherchent le point d’entrée institutionnel de la profession.",
    tags: ["Prescripteur", "Business", "Partenariat"],
    icon: "Scale",
    usefulFor: ["Structuration", "Recommandation", "Partenariat"],
    href: "https://www.cnb.avocat.fr/",
    cta: "Voir l’écosystème",
  },
  {
    slug: "banques-professionnelles",
    name: "Bpifrance",
    category: "Prescripteur",
    shortDescription: "L’acteur public de référence pour le financement et l’accompagnement des entreprises.",
    description:
      "Bpifrance accompagne la création, le financement, l’innovation, l’export et le développement des entreprises françaises.",
    bestFor: "Les dirigeants et accompagnateurs qui veulent accéder à l’écosystème public du financement d’entreprise.",
    tags: ["Prescripteur", "Partenariat", "Business"],
    icon: "CreditCard",
    usefulFor: ["Financement", "Business", "Partenariat"],
    href: "https://www.bpifrance.fr/",
    cta: "Voir l’écosystème",
  },
  {
    slug: "bni",
    name: "BNI",
    category: "Réseau",
    shortDescription: "Un réseau business structuré autour de la recommandation.",
    description:
      "BNI peut être un levier simple pour créer des recommandations régulières, à condition que le métier et la posture s’y prêtent.",
    bestFor: "Les indépendants, artisans et prestataires qui veulent un cadre direct d’apport d’affaires.",
    tags: ["Réseau local", "Business", "Relations"],
    icon: "Share2",
    usefulFor: ["Apport d’affaires", "Réseau", "Local"],
    href: "https://bnifrance.fr/fr/rejoindre-bni",
    cta: "Voir le réseau",
  },
  {
    slug: "umih",
    name: "UMIH",
    category: "Réseau",
    shortDescription: "Le réseau de référence du secteur CHR.",
    description:
      "L’UMIH est un repère métier utile pour la restauration, l’hôtellerie et les activités CHR qui veulent rester connectées à leur environnement.",
    bestFor: "Les restaurants, cafés et activités d’hospitalité qui veulent renforcer leur réseau métier.",
    tags: ["Réseau métier", "CHR", "Veille"],
    icon: "Utensils",
    usefulFor: ["Restauration", "Veille", "Crédibilité"],
    href: "https://www.umih.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "ghr",
    name: "GHR",
    category: "Réseau",
    shortDescription: "Un réseau métier supplémentaire pour les professionnels du CHR.",
    description:
      "Le GHR peut servir de point d’ancrage métier, de veille et de réseau pour les activités de restauration et d’hospitalité.",
    bestFor: "Les dirigeants CHR qui veulent multiplier leurs points d’entrée réseau métier.",
    tags: ["Réseau métier", "CHR", "Veille"],
    icon: "Utensils",
    usefulFor: ["Restauration", "Réseau", "Veille"],
    href: "https://www.ghr.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "salons-habitat-btp",
    name: "Foire de Paris — Maison & Habitat",
    category: "Événement",
    shortDescription: "L’univers Maison & Habitat de la Foire de Paris.",
    description:
      "Un événement concret pour rencontrer des visiteurs, observer le marché de l’habitat et présenter une offre liée aux travaux ou à l’aménagement.",
    bestFor: "Les activités bâtiment qui veulent travailler leur visibilité et leur prospection dans le réel.",
    tags: ["Événement", "Visibilité", "Prospection"],
    icon: "Sparkles",
    usefulFor: ["Visibilité", "Prospection", "Bâtiment"],
    href: "https://www.foiredeparis.fr/fr-FR/decouvrir-foire-de-paris/maison-habitat",
    cta: "Voir l’événement",
  },
  {
    slug: "qualibat",
    name: "Qualibat",
    category: "Officiel",
    shortDescription: "Un repère utile de qualification pour le bâtiment.",
    description:
      "Qualibat renforce la crédibilité d’une entreprise du bâtiment et sert de signal de confiance dans de nombreux contextes commerciaux.",
    bestFor: "Les entreprises BTP qui veulent mieux rassurer et monter en crédibilité sur les chantiers.",
    tags: ["Officiel", "Qualification", "Crédibilité"],
    icon: "Shield",
    usefulFor: ["Crédibilité", "BTP", "Confiance"],
    href: "https://www.qualibat.com/",
    cta: "Voir l’organisme",
  },
  {
    slug: "france-renov",
    name: "France Rénov’",
    category: "Officiel",
    shortDescription: "Un écosystème important pour les pros de la rénovation.",
    description:
      "France Rénov’ et son environnement sont utiles aux entreprises positionnées sur la rénovation énergétique et les chantiers liés à la performance énergétique.",
    bestFor: "Les entreprises travaux qui veulent mieux se positionner sur les sujets rénovation et aides.",
    tags: ["Officiel", "Rénovation", "Veille"],
    icon: "Zap",
    usefulFor: ["Rénovation", "Veille", "Confiance"],
    href: "https://france-renov.gouv.fr/",
    cta: "Voir l’écosystème",
  },
  {
    slug: "medef-local",
    name: "MEDEF territorial",
    category: "Réseau",
    shortDescription: "Un réseau de dirigeants utile pour les activités B2B structurées.",
    description:
      "Le MEDEF territorial peut servir de réseau d’influence, de visibilité et de connexion avec d’autres dirigeants sur un territoire.",
    bestFor: "Les dirigeants B2B qui veulent un réseau business plus institutionnel et plus large.",
    tags: ["Réseau local", "Dirigeants", "Business"],
    icon: "Share2",
    usefulFor: ["Dirigeants", "Business", "Local"],
    href: "https://www.medef.com/",
    cta: "Voir le réseau",
  },
  {
    slug: "cpme-locale",
    name: "CPME locale",
    category: "Réseau",
    shortDescription: "Un réseau PME utile pour la visibilité locale et les connexions business.",
    description:
      "La CPME locale peut être un point d’entrée simple pour rejoindre un réseau de dirigeants et renforcer son ancrage entrepreneurial.",
    bestFor: "Les dirigeants de PME et TPE qui veulent développer leur réseau local.",
    tags: ["Réseau local", "PME", "Business"],
    icon: "Share2",
    usefulFor: ["Local", "Business", "Dirigeants"],
    href: "https://www.cpme.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "french-tech",
    name: "French Tech",
    category: "Réseau",
    shortDescription: "Le réseau le plus visible pour beaucoup d’activités tech et numériques.",
    description:
      "La French Tech peut apporter visibilité, écosystème, événements et connexions utiles aux activités numériques en croissance.",
    bestFor: "Les entreprises tech, SaaS, marketplaces et activités digitales qui veulent rester connectées à l’écosystème.",
    tags: ["Tech", "Écosystème", "Visibilité"],
    icon: "Laptop",
    usefulFor: ["Tech", "Réseau", "Visibilité"],
    href: "https://lafrenchtech.gouv.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "numeum",
    name: "Numeum",
    category: "Réseau",
    shortDescription: "Un réseau de référence pour les entreprises du numérique.",
    description:
      "Numeum donne un point d’ancrage sectoriel utile pour les sociétés du numérique, du conseil IT et des services digitaux.",
    bestFor: "Les entreprises numériques qui veulent un réseau métier plus structuré.",
    tags: ["Réseau métier", "Numérique", "Veille"],
    icon: "Laptop",
    usefulFor: ["Numérique", "Veille", "Réseau"],
    href: "https://numeum.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "france-digitale",
    name: "France Digitale",
    category: "Réseau",
    shortDescription: "Un réseau très utile pour les startups et sociétés tech en croissance.",
    description:
      "France Digitale sert de point de connexion avec l’écosystème startup, innovation, investisseurs et événements du secteur.",
    bestFor: "Les SaaS, marketplaces et activités tech avec ambition de croissance ou de financement.",
    tags: ["Startup", "Tech", "Croissance"],
    icon: "Workflow",
    usefulFor: ["Croissance", "Tech", "Financement"],
    href: "https://francedigitale.org/",
    cta: "Voir le réseau",
  },
  {
    slug: "ordre-medecins",
    name: "Ordre des médecins",
    category: "Officiel",
    shortDescription: "L’instance de référence pour les cabinets médicaux.",
    description:
      "L’Ordre des médecins joue un rôle central de cadre, de crédibilité et d’écosystème pour les praticiens.",
    bestFor: "Les cabinets médicaux qui veulent rester alignés avec leur cadre métier et leur environnement professionnel.",
    tags: ["Officiel", "Santé", "Crédibilité"],
    icon: "HeartPulse",
    usefulFor: ["Santé", "Crédibilité", "Profession"],
    href: "https://www.conseil-national.medecin.fr/",
    cta: "Voir l’instance",
  },
  {
    slug: "urps",
    name: "URPS",
    category: "Réseau",
    shortDescription: "Un point d’ancrage régional utile pour plusieurs professions de santé.",
    description:
      "Les URPS structurent une partie du réseau régional de santé et peuvent être utiles pour la visibilité et les liens terrain.",
    bestFor: "Les professionnels de santé libéraux qui veulent mieux s’ancrer dans leur territoire.",
    tags: ["Santé", "Local", "Profession"],
    icon: "HeartPulse",
    usefulFor: ["Santé", "Local", "Réseau"],
    href: "https://www.urps.org/",
    cta: "Voir l’écosystème",
  },
  {
    slug: "ordre-infirmiers",
    name: "Ordre des infirmiers",
    category: "Officiel",
    shortDescription: "Le repère professionnel clé pour les infirmiers libéraux.",
    description:
      "L’Ordre des infirmiers constitue un repère utile de cadre métier, de crédibilité et de professionnalisation.",
    bestFor: "Les infirmiers libéraux qui veulent un ancrage métier clair et visible.",
    tags: ["Officiel", "Santé", "Profession"],
    icon: "HeartPulse",
    usefulFor: ["Santé", "Profession", "Crédibilité"],
    href: "https://www.ordre-infirmiers.fr/",
    cta: "Voir l’instance",
  },
  {
    slug: "ordre-pharmaciens",
    name: "Ordre des pharmaciens",
    category: "Officiel",
    shortDescription: "L’instance de référence pour les officines et pharmaciens.",
    description:
      "L’Ordre des pharmaciens est un point d’appui institutionnel utile pour le cadre métier et la crédibilité de l’activité.",
    bestFor: "Les pharmacies qui veulent rester connectées à leur environnement professionnel et réglementaire.",
    tags: ["Officiel", "Santé", "Profession"],
    icon: "HeartPulse",
    usefulFor: ["Santé", "Crédibilité", "Profession"],
    href: "https://www.ordre.pharmacien.fr/",
    cta: "Voir l’instance",
  },
  {
    slug: "ordre-dentistes",
    name: "Ordre des chirurgiens-dentistes",
    category: "Officiel",
    shortDescription: "L’instance métier structurante pour les cabinets dentaires.",
    description:
      "L’Ordre des chirurgiens-dentistes constitue un repère central pour le cadre métier et la visibilité institutionnelle.",
    bestFor: "Les cabinets dentaires qui veulent renforcer leur crédibilité et leur ancrage professionnel.",
    tags: ["Officiel", "Santé", "Crédibilité"],
    icon: "HeartPulse",
    usefulFor: ["Santé", "Profession", "Confiance"],
    href: "https://www.ordre-chirurgiens-dentistes.fr/",
    cta: "Voir l’instance",
  },
  {
    slug: "ordre-veterinaires",
    name: "Ordre des vétérinaires",
    category: "Officiel",
    shortDescription: "Le cadre métier de référence pour les vétérinaires.",
    description:
      "L’Ordre des vétérinaires reste le repère clé pour le cadre métier, la crédibilité et l’environnement professionnel.",
    bestFor: "Les cliniques et cabinets vétérinaires qui veulent renforcer leur ancrage professionnel.",
    tags: ["Officiel", "Santé", "Profession"],
    icon: "HeartPulse",
    usefulFor: ["Santé", "Crédibilité", "Profession"],
    href: "https://www.veterinaire.fr/",
    cta: "Voir l’instance",
  },
  {
    slug: "acteurs-competence",
    name: "Les Acteurs de la Compétence",
    category: "Réseau",
    shortDescription: "Un réseau métier structurant pour la formation professionnelle.",
    description:
      "Ce réseau est utile pour les organismes de formation et acteurs du secteur qui veulent rester connectés aux enjeux métier et à leur environnement.",
    bestFor: "Les organismes de formation et activités éducatives qui veulent un réseau métier identifié.",
    tags: ["Formation", "Réseau métier", "Veille"],
    icon: "FileSearch",
    usefulFor: ["Formation", "Veille", "Réseau"],
    href: "https://www.lesacteursdelacompetence.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "edtech-france",
    name: "EdTech France",
    category: "Réseau",
    shortDescription: "Un réseau utile pour les activités formation et tech éducative.",
    description:
      "EdTech France sert de point de connexion entre innovation, pédagogie et écosystème numérique de la formation.",
    bestFor: "Les activités e-learning, formation en ligne et outils pédagogiques qui veulent gagner en visibilité.",
    tags: ["Formation", "Tech", "Visibilité"],
    icon: "Laptop",
    usefulFor: ["Formation", "Tech", "Réseau"],
    href: "https://edtechfrance.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "offices-tourisme",
    name: "ADN Tourisme",
    category: "Réseau",
    shortDescription: "La fédération nationale des organismes institutionnels du tourisme.",
    description:
      "ADN Tourisme fédère les offices de tourisme et les organismes départementaux et régionaux du tourisme.",
    bestFor: "Les activités d’hébergement, de voyage et de tourisme qui veulent comprendre et rejoindre l’écosystème territorial.",
    tags: ["Tourisme", "Local", "Visibilité"],
    icon: "Globe2",
    usefulFor: ["Tourisme", "Visibilité", "Local"],
    href: "https://www.adn-tourisme.fr/qui-sommes-nous/missions/",
    cta: "Voir la fédération",
  },
  {
    slug: "atout-france",
    name: "Atout France",
    category: "Officiel",
    shortDescription: "Le grand repère institutionnel du secteur tourisme.",
    description:
      "Atout France aide à comprendre l’environnement du tourisme et donne un cadre utile de visibilité et de veille sectorielle.",
    bestFor: "Les activités tourisme et hébergement qui veulent se connecter à l’écosystème sectoriel.",
    tags: ["Tourisme", "Officiel", "Veille"],
    icon: "Globe2",
    usefulFor: ["Tourisme", "Veille", "Crédibilité"],
    href: "https://www.atout-france.fr/",
    cta: "Voir l’organisme",
  },
  {
    slug: "cncgp",
    name: "CNCGP",
    category: "Réseau",
    shortDescription: "Un réseau de référence pour les conseillers en gestion de patrimoine.",
    description:
      "La CNCGP est un repère métier utile pour la crédibilité, le réseau et la veille dans l’univers patrimonial.",
    bestFor: "Les gestionnaires de patrimoine et activités liées au conseil patrimonial.",
    tags: ["Patrimoine", "Réseau métier", "Crédibilité"],
    icon: "Calculator",
    usefulFor: ["Patrimoine", "Crédibilité", "Veille"],
    href: "https://www.cncgp.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "anacofi",
    name: "ANACOFI",
    category: "Réseau",
    shortDescription: "Un autre réseau structurant pour les métiers du conseil patrimonial.",
    description:
      "L’ANACOFI constitue un environnement utile de réseau et de veille pour plusieurs professions du conseil financier et patrimonial.",
    bestFor: "Les activités patrimoine, investissement et conseil financier qui veulent un réseau métier plus structuré.",
    tags: ["Patrimoine", "Finance", "Veille"],
    icon: "Calculator",
    usefulFor: ["Patrimoine", "Réseau", "Veille"],
    href: "https://www.anacofi.asso.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "fntr",
    name: "FNTR",
    category: "Réseau",
    shortDescription: "Le réseau métier de référence du transport routier.",
    description:
      "La FNTR aide les entreprises du transport à rester connectées à leur environnement métier, réglementaire et business.",
    bestFor: "Les activités transport et logistique qui veulent un ancrage métier fort.",
    tags: ["Transport", "Réseau métier", "Veille"],
    icon: "Car",
    usefulFor: ["Transport", "Veille", "Réseau"],
    href: "https://www.fntr.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "otre",
    name: "OTRE",
    category: "Réseau",
    shortDescription: "Un réseau structurant pour transporteurs et logistique.",
    description:
      "L’OTRE peut jouer un rôle utile de veille, de représentation et de réseau pour les entreprises du transport et des mobilités.",
    bestFor: "Les entreprises transport, dernier kilomètre et logistique terrain.",
    tags: ["Transport", "Logistique", "Veille"],
    icon: "Car",
    usefulFor: ["Transport", "Logistique", "Réseau"],
    href: "https://www.otre.org/",
    cta: "Voir le réseau",
  },
  {
    slug: "mobilians",
    name: "Mobilians",
    category: "Réseau",
    shortDescription: "Le grand réseau métier de l’automobile et des services de mobilité.",
    description:
      "Mobilians est un point d’appui utile pour les garages, carrosseries et activités liées à la mobilité.",
    bestFor: "Les activités automobile, réparation et mobilité qui veulent un réseau métier reconnu.",
    tags: ["Automobile", "Réseau métier", "Veille"],
    icon: "Car",
    usefulFor: ["Automobile", "Veille", "Crédibilité"],
    href: "https://www.mobilians.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "reseaux-assureurs-auto",
    name: "France Assureurs",
    category: "Réseau",
    shortDescription: "La fédération professionnelle de l’assurance en France.",
    description:
      "France Assureurs représente le secteur de l’assurance et publie des informations utiles sur ses métiers et ses évolutions.",
    bestFor: "Les professionnels qui veulent suivre l’écosystème de l’assurance et ses interactions avec l’automobile.",
    tags: ["Prescripteur", "Automobile", "Business"],
    icon: "Shield",
    usefulFor: ["Apport d’affaires", "Automobile", "Partenariat"],
    href: "https://www.franceassureurs.fr/",
    cta: "Voir l’écosystème",
  },
  {
    slug: "mouvement-associatif",
    name: "Le Mouvement associatif",
    category: "Réseau",
    shortDescription: "Le réseau de référence du monde associatif.",
    description:
      "Le Mouvement associatif apporte un cadre, de la veille et un environnement réseau utile aux structures associatives.",
    bestFor: "Les associations qui veulent rester connectées à leur écosystème et renforcer leur crédibilité.",
    tags: ["Association", "Réseau métier", "Veille"],
    icon: "Share2",
    usefulFor: ["Association", "Veille", "Réseau"],
    href: "https://lemouvementassociatif.org/",
    cta: "Voir le réseau",
  },
  {
    slug: "france-benevolat",
    name: "France Bénévolat",
    category: "Réseau",
    shortDescription: "Un réseau utile pour les associations qui cherchent à mobiliser des bénévoles.",
    description:
      "France Bénévolat peut être un levier utile pour les associations qui veulent structurer ou renforcer leur mobilisation bénévole.",
    bestFor: "Les associations qui dépendent du bénévolat et des relais locaux.",
    tags: ["Association", "Bénévolat", "Local"],
    icon: "UserRoundCheck",
    usefulFor: ["Bénévolat", "Association", "Local"],
    href: "https://www.francebenevolat.org/",
    cta: "Voir le réseau",
  },
  {
    slug: "ess-france",
    name: "ESS France",
    category: "Réseau",
    shortDescription: "Le réseau structurant de l’économie sociale et solidaire.",
    description:
      "ESS France apporte un ancrage réseau pertinent pour les structures qui s’inscrivent dans l’économie sociale et solidaire.",
    bestFor: "Les associations et structures à impact qui veulent un réseau plus institutionnel.",
    tags: ["ESS", "Association", "Réseau"],
    icon: "Share2",
    usefulFor: ["ESS", "Association", "Crédibilité"],
    href: "https://www.ess-france.org/",
    cta: "Voir le réseau",
  },
  {
    slug: "union-commercants-locaux",
    name: "CCI France — Commerce",
    category: "Réseau",
    shortDescription: "Le réseau national des CCI pour accompagner les commerces de proximité.",
    description:
      "Les CCI accompagnent les commerçants sur la création, le développement, la transformation numérique et l’ancrage territorial.",
    bestFor: "Les commerces physiques qui gagnent à être visibles sur leur zone de chalandise.",
    tags: ["Commerce", "Local", "Visibilité"],
    icon: "Building2",
    usefulFor: ["Commerce", "Local", "Visibilité"],
    href: "https://www.cci.fr/",
    cta: "Trouver des relais locaux",
  },
  {
    slug: "salons-commerce-restauration",
    name: "Sirha Lyon",
    category: "Événement",
    shortDescription: "Le salon professionnel de référence pour la restauration et l’hospitalité.",
    description:
      "Sirha Lyon réunit les acteurs de la restauration, de l’hôtellerie et de l’alimentation autour des innovations, fournisseurs et tendances métier.",
    bestFor: "Les activités CHR et métiers de bouche qui veulent rencontrer leur écosystème professionnel.",
    tags: ["Événement", "Veille", "Business"],
    icon: "Sparkles",
    usefulFor: ["Visibilité", "Veille", "Business"],
    href: "https://www.sirha-lyon.com/fr",
    cta: "Voir l’événement",
  },
  {
    slug: "fesp",
    name: "FESP",
    category: "Réseau",
    shortDescription: "Un réseau structurant pour les services à la personne.",
    description:
      "La FESP peut servir de cadre réseau utile pour les activités de services à la personne et d’aide à domicile.",
    bestFor: "Les structures de services à la personne qui veulent un environnement métier plus solide.",
    tags: ["Services à la personne", "Réseau métier", "Veille"],
    icon: "UserRoundCheck",
    usefulFor: ["Services", "Veille", "Crédibilité"],
    href: "https://www.fesp.fr/",
    cta: "Voir le réseau",
  },
  {
    slug: "french-fab",
    name: "La French Fab",
    category: "Réseau",
    shortDescription: "Un repère réseau utile pour l’industrie et la production.",
    description:
      "La French Fab aide à donner de la visibilité à l’industrie et peut servir de porte d’entrée réseau sur cet univers.",
    bestFor: "Les activités production et industrie qui veulent renforcer leur présence et leur réseau.",
    tags: ["Industrie", "Visibilité", "Réseau"],
    icon: "Workflow",
    usefulFor: ["Industrie", "Réseau", "Visibilité"],
    href: "https://www.lafrenchfab.fr/",
    cta: "Voir le réseau",
  },
] satisfies DemaaProNetwork[];

export const proNetworkCategories = [
  "Officiel",
  "Réseau",
  "Prescripteur",
  "Événement",
] satisfies ProNetworkCategory[];

export type DemaaProNetworkSlug = (typeof demaaProNetworks)[number]["slug"];

const proNetworkBySlug = Object.fromEntries(
  demaaProNetworks.map((network) => [network.slug, network]),
) as Partial<Record<DemaaProNetworkSlug, DemaaProNetwork>>;

export function getDemaaProNetworks(): DemaaProNetwork[] {
  return [...demaaProNetworks];
}

export function getDemaaProNetworkBySlug(slug: string): DemaaProNetwork | null {
  return proNetworkBySlug[slug as DemaaProNetworkSlug] ?? null;
}
