type SupplierCategory =
  | "Banque"
  | "Assurance"
  | "Mutuelle"
  | "Matériaux"
  | "Équipement"
  | "Grossiste"
  | "Paiement"
  | "Téléphonie"
  | "Énergie"
  | "Transport"
  | "Support";

export type SupplierFamily =
  | "Finance & protection"
  | "Équipement & exploitation";

type SupplierCta = "Voir le fournisseur" | "Demander une mise en relation" | "Comparer les options";

export type DemaaSupplier = {
  slug: string;
  name: string;
  family: SupplierFamily;
  category: SupplierCategory;
  shortDescription: string;
  description: string;
  bestFor: string;
  offerHint: string;
  tags: string[];
  icon: string;
  usefulFor: string[];
  href: string;
  cta: SupplierCta;
  partner?: boolean;
};

export const demaaSuppliers: readonly DemaaSupplier[] = [
  {
    slug: "orus",
    name: "Orus",
    family: "Finance & protection",
    category: "Assurance",
    shortDescription: "Assurance professionnelle en ligne pour indépendants et petites entreprises.",
    description:
      "Assurances RC Pro, multirisque, local professionnel, bureaux et décennale, avec un parcours de souscription en ligne.",
    bestFor: "Les indépendants et petites entreprises qui veulent protéger leur activité, leurs locaux ou leurs chantiers.",
    offerHint: "Devis en ligne",
    tags: ["RC Pro", "Multirisque", "Décennale"],
    icon: "Shield",
    usefulFor: ["Protection", "Obligations", "Chantier", "Local"],
    href: "https://www.orus.eu/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "alan",
    name: "Alan",
    family: "Finance & protection",
    category: "Mutuelle",
    shortDescription: "Mutuelle santé et prévention pour les équipes.",
    description:
      "Mutuelle et services santé pour simplifier la couverture des équipes et le suivi RH.",
    bestFor: "Les entreprises avec salariés qui veulent une mutuelle claire et simple à gérer.",
    offerHint: "Offre partenaire à venir",
    tags: ["Mutuelle", "Santé", "RH"],
    icon: "HeartPulse",
    usefulFor: ["Salariés", "Santé", "RH"],
    href: "https://alan.com/fr-fr",
    cta: "Voir le fournisseur",
    partner: true,
  },
  {
    slug: "swile",
    name: "Swile",
    family: "Finance & protection",
    category: "Support",
    shortDescription: "Titres-resto et avantages salariés.",
    description:
      "Solution d'avantages salariés : titres-resto, avantages d'équipe et gestion sociale du quotidien.",
    bestFor: "Les entreprises qui structurent leurs avantages salariés.",
    offerHint: "Offre partenaire à venir",
    tags: ["Avantages", "Titres-resto", "RH"],
    icon: "Gift",
    usefulFor: ["Salariés", "Avantages", "Restauration"],
    href: "https://www.swile.co/",
    cta: "Voir le fournisseur",
    partner: true,
  },
  {
    slug: "plateforme-du-batiment",
    name: "Plateforme du Bâtiment",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Matériaux, outillage et approvisionnement BTP.",
    description:
      "Distributeur professionnel pour artisans et entreprises du bâtiment : matériaux, outillage, retrait et conditions pro.",
    bestFor: "Les artisans et entreprises BTP qui doivent s'approvisionner vite et régulièrement.",
    offerHint: "Conditions pro à vérifier",
    tags: ["BTP", "Matériaux", "Outillage"],
    icon: "Building2",
    usefulFor: ["Bâtiment", "Approvisionnement", "Chantier"],
    href: "https://www.laplateforme.com/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "point-p",
    name: "Point.P",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Matériaux de construction et négoce bâtiment.",
    description:
      "Négoce de matériaux pour construction, rénovation, gros oeuvre, second oeuvre et livraison chantier.",
    bestFor: "Les entreprises BTP avec besoins réguliers en matériaux et livraison.",
    offerHint: "Conditions pro à vérifier",
    tags: ["BTP", "Matériaux", "Livraison"],
    icon: "Boxes",
    usefulFor: ["Bâtiment", "Matériaux", "Livraison"],
    href: "https://www.pointp.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "kiloutou",
    name: "Kiloutou",
    family: "Équipement & exploitation",
    category: "Équipement",
    shortDescription: "Location de matériel professionnel.",
    description:
      "Location de matériel et équipements pour chantier, manutention, événementiel, nettoyage ou travaux ponctuels.",
    bestFor: "Les métiers qui ont besoin de matériel sans l'acheter.",
    offerHint: "Conditions pro à vérifier",
    tags: ["Location", "Matériel", "Chantier"],
    icon: "Wrench",
    usefulFor: ["Location", "Chantier", "Équipement"],
    href: "https://www.kiloutou.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "wurth",
    name: "Würth",
    family: "Équipement & exploitation",
    category: "Équipement",
    shortDescription: "Consommables, visserie, outillage et EPI.",
    description:
      "Fournisseur professionnel pour outillage, visserie, consommables, produits techniques et équipements de protection.",
    bestFor: "Les artisans, ateliers, garages, mainteneurs et entreprises terrain.",
    offerHint: "Conditions pro à vérifier",
    tags: ["Outillage", "Consommables", "EPI"],
    icon: "Hammer",
    usefulFor: ["Artisanat", "Atelier", "Sécurité"],
    href: "https://eshop.wurth.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "rexel",
    name: "Rexel",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Matériel électrique et solutions énergie.",
    description:
      "Distributeur de matériel électrique pour installateurs, maintenance, rénovation, énergie et équipements professionnels.",
    bestFor: "Les électriciens, mainteneurs, entreprises BTP et sites avec besoins électriques.",
    offerHint: "Conditions pro à vérifier",
    tags: ["Électricité", "BTP", "Énergie"],
    icon: "Zap",
    usefulFor: ["Électricité", "Maintenance", "Bâtiment"],
    href: "https://www.rexel.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "cedeo-pro",
    name: "CEDEO",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Sanitaire, chauffage, plomberie et ventilation pour professionnels du bâtiment.",
    description:
      "Négoce spécialisé pour plombiers-chauffagistes avec produits de sanitaire, génie climatique, plomberie et ventilation disponibles en réseau d'agences.",
    bestFor: "Les plombiers-chauffagistes qui veulent centraliser leurs achats techniques et leurs retraits chantier.",
    offerHint: "Compte professionnel",
    tags: ["Plomberie", "Chauffage", "Sanitaire"],
    icon: "Droplets",
    usefulFor: ["Plombier", "Chauffagiste", "Chantier"],
    href: "https://www.cedeo.fr/notre-enseigne",
    cta: "Voir le fournisseur",
  },
  {
    slug: "dispano-bois",
    name: "Dispano",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Bois, panneaux, menuiseries et services de transformation pour professionnels.",
    description:
      "Négoce spécialisé dans les bois, panneaux, menuiseries, quincaillerie et aménagement, avec ateliers de découpe et livraison chantier.",
    bestFor: "Les menuisiers, agenceurs et artisans du bois qui ont besoin de matériaux et de transformations sur mesure.",
    offerHint: "Compte professionnel",
    tags: ["Bois", "Menuiserie", "Panneaux"],
    icon: "Boxes",
    usefulFor: ["Menuisier", "Agenceur", "Matériaux"],
    href: "https://www.dispano.fr/qui-sommes-nous",
    cta: "Voir le fournisseur",
  },
  {
    slug: "asturienne-toiture",
    name: "Asturienne",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Matériaux et services professionnels spécialisés pour la couverture et la toiture.",
    description:
      "Distribution de zinc, tuiles, ardoises, fenêtres de toit, évacuation des eaux pluviales et outillage pour couvreurs et charpentiers.",
    bestFor: "Les couvreurs qui recherchent un distributeur métier avec stock, conseil technique et services de préparation des métaux.",
    offerHint: "Compte professionnel",
    tags: ["Couverture", "Toiture", "Zinc"],
    icon: "Building2",
    usefulFor: ["Couvreur", "Charpentier", "Chantier"],
    href: "https://www.asturienne.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "legallais-quincaillerie",
    name: "Legallais",
    family: "Équipement & exploitation",
    category: "Équipement",
    shortDescription: "Quincaillerie, serrurerie, contrôle d'accès et équipements pour professionnels du bâtiment.",
    description:
      "Catalogue professionnel couvrant serrures, ferme-portes, quincaillerie, automatismes, contrôle d'accès, outillage et consommables de chantier.",
    bestFor: "Les serruriers, menuisiers et entreprises de maintenance qui commandent des références techniques de bâtiment.",
    offerHint: "Compte professionnel",
    tags: ["Serrurerie", "Quincaillerie", "Contrôle d'accès"],
    icon: "Wrench",
    usefulFor: ["Serrurier", "Menuisier", "Maintenance"],
    href: "https://www.legallais.com/offre-sur-commande-a25",
    cta: "Voir le fournisseur",
  },
  {
    slug: "tollens-pro",
    name: "Tollens Pro",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Peintures, revêtements et outillage destinés aux professionnels du bâtiment.",
    description:
      "Gammes professionnelles de peintures intérieures et extérieures, enduits, revêtements, outils et protections avec espace de commande pro.",
    bestFor: "Les peintres en bâtiment qui veulent suivre stock, tarifs et commandes auprès d'un réseau spécialisé.",
    offerHint: "Espace professionnel",
    tags: ["Peinture", "Revêtement", "Bâtiment"],
    icon: "Sparkles",
    usefulFor: ["Peintre", "Rénovation", "Chantier"],
    href: "https://www.tollens.com/services/services-en-ligne/mytollens",
    cta: "Voir le fournisseur",
  },
  {
    slug: "clim-plus",
    name: "Clim+",
    family: "Équipement & exploitation",
    category: "Matériaux",
    shortDescription: "Climatisation, ventilation et chauffage réservés aux professionnels.",
    description:
      "Réseau spécialisé en génie climatique proposant équipements, accessoires, pièces, outillage, conseil technique et livraison chantier.",
    bestFor: "Les installateurs et mainteneurs CVC qui veulent accéder à un catalogue et un support technique spécialisés.",
    offerHint: "Réservé aux professionnels",
    tags: ["Climatisation", "Ventilation", "Chauffage"],
    icon: "Zap",
    usefulFor: ["CVC", "Installation", "Maintenance"],
    href: "https://www.climplus.com/clim-nous-connaitre/clim-notre-enseigne",
    cta: "Voir le fournisseur",
  },
  {
    slug: "transgourmet",
    name: "Transgourmet",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Grossiste food-service pour restaurateurs, boulangers et traiteurs.",
    description:
      "Approvisionnement professionnel en produits frais, surgelés, épicerie, boissons, équipements et produits d'hygiène, avec livraison adaptée aux métiers de bouche.",
    bestFor: "Les restaurants, traiteurs et boulangeries-pâtisseries qui veulent centraliser leurs commandes et leurs livraisons.",
    offerHint: "Livraison professionnelle",
    tags: ["Restauration", "Alimentaire", "Livraison"],
    icon: "Utensils",
    usefulFor: ["Restauration", "Stock", "Frais"],
    href: "https://www.transgourmet.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "france-boissons",
    name: "France Boissons",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Distribution de boissons et services pour cafés, hôtels et restaurants.",
    description:
      "Distributeur professionnel de bières, vins, cafés, eaux, jus, spiritueux et boissons sans alcool, avec un réseau logistique national.",
    bestFor: "Les bars, cafés, restaurants, traiteurs et organisateurs d'événements qui ont besoin d'un approvisionnement régulier.",
    offerHint: "Distribution CHR",
    tags: ["Boissons", "Bar", "Restauration"],
    icon: "CupSoda",
    usefulFor: ["Bar", "Restaurant", "Événementiel"],
    href: "https://www.france-boissons.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "firplast",
    name: "Firplast",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Emballages alimentaires pour restauration, vente à emporter et métiers de bouche.",
    description:
      "Fournisseur d'emballages alimentaires, barquettes, boîtes, sacs et contenants personnalisables pour la livraison et la vente à emporter.",
    bestFor: "Les restaurants, boulangeries et traiteurs qui cherchent des emballages adaptés au contact alimentaire.",
    offerHint: "Livraison professionnelle",
    tags: ["Emballage", "Restauration", "Vente à emporter"],
    icon: "Package",
    usefulFor: ["Restauration", "Livraison", "Emballage"],
    href: "https://www.firplast.com/emballages-alimentaire-81",
    cta: "Voir le fournisseur",
  },
  {
    slug: "raja",
    name: "RAJA",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Emballages, cartons et solutions d'expédition pour les professionnels.",
    description:
      "Fournisseur d'emballages, cartons, enveloppes, protections, adhésifs et équipements pour préparer les commandes et les expéditions.",
    bestFor: "Les commerces, boutiques et entreprises e-commerce qui expédient régulièrement des produits.",
    offerHint: "Commande en ligne",
    tags: ["Emballage", "Expédition", "E-commerce"],
    icon: "Package",
    usefulFor: ["E-commerce", "Boutique", "Expédition"],
    href: "https://www.raja.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "ocp-repartition",
    name: "OCP Répartition",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Grossiste-répartiteur pharmaceutique pour l'approvisionnement des officines.",
    description:
      "Distribution de médicaments, produits de santé et services aux pharmacies, avec une logistique dédiée aux besoins quotidiens des officines.",
    bestFor: "Les pharmacies qui recherchent un répartiteur structuré pour sécuriser leur approvisionnement et leur stock.",
    offerHint: "Compte pharmacien",
    tags: ["Pharmacie", "Officine", "Répartition"],
    icon: "HeartPulse",
    usefulFor: ["Approvisionnement", "Stock", "Officine"],
    href: "https://www.ocp.fr/pharmacien/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "centravet",
    name: "Centravet",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Centrale de distribution et coopérative dédiée aux vétérinaires praticiens.",
    description:
      "Approvisionnement courant, matériel médico-chirurgical, services et solutions digitales pour les cabinets et cliniques vétérinaires.",
    bestFor: "Les vétérinaires qui veulent centraliser leurs achats métier et l'équipement de leur structure.",
    offerHint: "Compte vétérinaire",
    tags: ["Vétérinaire", "Centrale d'achat", "Équipement"],
    icon: "HeartPulse",
    usefulFor: ["Clinique", "Approvisionnement", "Matériel médical"],
    href: "https://www.centravet.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "autodistribution-pro",
    name: "Autodistribution Pro",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Pièces automobiles, peinture, pneumatiques et équipement pour les réparateurs.",
    description:
      "Distribution multimarque de pièces et équipements de garage, avec catalogue professionnel, diagnostic et logistique pour les ateliers.",
    bestFor: "Les garages et carrosseries qui ont besoin de pièces disponibles rapidement et de services d'aide à la réparation.",
    offerHint: "Accès professionnel",
    tags: ["Pièces auto", "Garage", "Atelier"],
    icon: "Car",
    usefulFor: ["Réparation", "Pièces", "Atelier"],
    href: "https://pro.autodistribution.fr/services-aux-professionnels",
    cta: "Voir le fournisseur",
  },
  {
    slug: "gouiran-beaute-pro",
    name: "Gouiran Beauté Pro",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Produits, consommables et matériel professionnel pour coiffure et esthétique.",
    description:
      "Grossiste coiffure et esthétique avec compte professionnel, marques métier, tarifs dédiés et livraison pour salons, instituts et barbiers.",
    bestFor: "Les salons de coiffure et instituts de beauté qui commandent régulièrement produits techniques et consommables.",
    offerHint: "Compte professionnel",
    tags: ["Coiffure", "Esthétique", "Consommables"],
    icon: "Sparkles",
    usefulFor: ["Salon", "Institut", "Stock"],
    href: "https://www.gouiran-beaute.com/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "bbgr-optique",
    name: "BBGR Optique",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Fabricant français de verres optiques et solutions professionnelles pour opticiens.",
    description:
      "Gammes de verres BBGR et Nikon, solutions de prise de mesure, outils d'aide à la vente et accompagnement commercial pour les opticiens.",
    bestFor: "Les magasins d'optique qui recherchent un fournisseur de verres et un accompagnement professionnel structuré.",
    offerHint: "Espace professionnel",
    tags: ["Optique", "Verres", "Magasin"],
    icon: "ScanSearch",
    usefulFor: ["Opticien", "Verres", "Équipement"],
    href: "https://www.bbgr.com/je-suis-opticien/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "scp-france-piscine",
    name: "SCP France",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Distribution d'équipements, pièces et produits pour piscines et spas professionnels.",
    description:
      "Offre destinée aux professionnels de la piscine : filtration, traitement de l'eau, chauffage, revêtements, robots, couvertures et pièces techniques.",
    bestFor: "Les piscinistes qui ont besoin d'un catalogue métier couvrant construction, rénovation et entretien.",
    offerHint: "Compte professionnel",
    tags: ["Piscine", "Spa", "Équipement"],
    icon: "Droplets",
    usefulFor: ["Pisciniste", "Traitement de l'eau", "Pièces"],
    href: "https://www.swimmingpool.eu/fr/nos-sites.html",
    cta: "Voir le fournisseur",
  },
  {
    slug: "france-fleurs-pro",
    name: "France Fleurs",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Fleurs fraîches et séchées en gros, avec livraison adaptée aux commandes professionnelles.",
    description:
      "Grossiste floral proposant fleurs en vrac, bottes, végétaux et solutions pour les commandes professionnelles et événementielles.",
    bestFor: "Les fleuristes et décorateurs événementiels qui veulent commander des fleurs en volume avec livraison.",
    offerHint: "Commande professionnelle",
    tags: ["Fleurs", "Fleuriste", "Événementiel"],
    icon: "Sparkles",
    usefulFor: ["Fleuriste", "Stock", "Événement"],
    href: "https://pros.francefleurs.com/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "papouille-creche",
    name: "Papouille",
    family: "Équipement & exploitation",
    category: "Équipement",
    shortDescription: "Mobilier, puériculture et matériel professionnel pour crèches et structures petite enfance.",
    description:
      "Fournisseur spécialisé en aménagement, mobilier, jeux, sommeil, change, repas et sécurité pour crèches, MAM et micro-crèches.",
    bestFor: "Les crèches qui doivent équiper ou renouveler leurs espaces avec du matériel adapté à la petite enfance.",
    offerHint: "Livraison professionnelle",
    tags: ["Crèche", "Mobilier", "Petite enfance"],
    icon: "Building2",
    usefulFor: ["Aménagement", "Sécurité", "Équipement"],
    href: "https://www.papouillefrance.com/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "henry-schein-dentaire",
    name: "Henry Schein Dentaire",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Fournitures, consommables et équipements destinés aux cabinets dentaires.",
    description:
      "Distributeur spécialisé pour les professionnels dentaires : consommables, instrumentation, équipements de cabinet et solutions d'aménagement.",
    bestFor: "Les chirurgiens-dentistes qui veulent centraliser les achats courants et l'équipement de leur cabinet.",
    offerHint: "Compte professionnel",
    tags: ["Dentaire", "Consommables", "Cabinet"],
    icon: "HeartPulse",
    usefulFor: ["Dentiste", "Équipement", "Approvisionnement"],
    href: "https://www.henryschein.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "distrimed-medical",
    name: "Distrimed",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Matériel médical, consommables de soins et mobilier pour professionnels de santé.",
    description:
      "Catalogue de diagnostic, désinfection, protection, consommables de soins, instrumentation et mobilier pour cabinets médicaux et infirmiers.",
    bestFor: "Les médecins, infirmiers et professionnels paramédicaux qui commandent du matériel médical courant.",
    offerHint: "Commande professionnelle",
    tags: ["Médical", "Soins", "Cabinet"],
    icon: "HeartPulse",
    usefulFor: ["Cabinet médical", "Infirmier", "Consommables"],
    href: "https://www.distrimed.com/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "decathlon-pro",
    name: "Decathlon Pro",
    family: "Équipement & exploitation",
    category: "Équipement",
    shortDescription: "Matériel sportif et aménagement d'espaces destinés aux professionnels.",
    description:
      "Équipement de fitness, musculation et multisports, avec accompagnement pour l'aménagement, la livraison, le montage et la maintenance.",
    bestFor: "Les salles de sport, clubs et coachs qui doivent équiper un espace ou renouveler leur matériel.",
    offerHint: "Compte professionnel",
    tags: ["Sport", "Fitness", "Aménagement"],
    icon: "Dumbbell",
    usefulFor: ["Salle de sport", "Coach", "Équipement"],
    href: "https://www.decathlonpro.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "logista-france",
    name: "Logista France",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Distribution de produits et services pour buralistes et commerces de proximité.",
    description:
      "Distribution de produits du tabac, produits alimentaires, articles pour fumeurs, téléphonie et références de proximité aux points de vente professionnels.",
    bestFor: "Les tabacs-presse et commerces de proximité qui structurent leur assortiment et leur réapprovisionnement.",
    offerHint: "Accès professionnel",
    tags: ["Tabac", "Presse", "Commerce de proximité"],
    icon: "Boxes",
    usefulFor: ["Buraliste", "Stock", "Point de vente"],
    href: "https://www.logistafrance.fr/fr/home/qui-sommes-nous/presentation.html",
    cta: "Voir le fournisseur",
  },
  {
    slug: "dilisco-livres",
    name: "Dilisco",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Diffusion et distribution de livres auprès des réseaux professionnels.",
    description:
      "Distributeur de catalogues d'éditeurs en littérature, jeunesse, pratique, scolaire et sciences humaines pour l'approvisionnement des points de vente.",
    bestFor: "Les librairies qui veulent compléter leur assortiment auprès d'un distributeur professionnel du livre.",
    offerHint: "Accès professionnel",
    tags: ["Livres", "Librairie", "Distribution"],
    icon: "BookOpen",
    usefulFor: ["Librairie", "Stock", "Catalogue"],
    href: "https://www.sne.fr/sne_adherents/dilisco/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "codes-rousseau-pro",
    name: "Codes Rousseau Pro",
    family: "Équipement & exploitation",
    category: "Support",
    shortDescription: "Supports pédagogiques et services professionnels pour les auto-écoles.",
    description:
      "Boutique et espace professionnel proposant supports d'apprentissage, solutions numériques et accompagnement pour les écoles de conduite.",
    bestFor: "Les auto-écoles qui doivent équiper leur pédagogie du code et suivre les apprentissages de leurs élèves.",
    offerHint: "Espace professionnel",
    tags: ["Auto-école", "Pédagogie", "Code"],
    icon: "Car",
    usefulFor: ["Formation", "Élèves", "Conduite"],
    href: "https://pro.codesrousseau.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "metro-france",
    name: "METRO France",
    family: "Équipement & exploitation",
    category: "Grossiste",
    shortDescription: "Produits, équipements et consommables pour l'hôtellerie et la restauration.",
    description:
      "Offre professionnelle couvrant alimentation, hygiène, linge, mobilier, art de la table et équipements pour les établissements CHR.",
    bestFor: "Les hôtels et établissements de restauration qui veulent regrouper une partie de leurs achats d'exploitation.",
    offerHint: "Carte professionnelle",
    tags: ["Hôtellerie", "Restauration", "Équipement"],
    icon: "Building2",
    usefulFor: ["Hôtel", "CHR", "Approvisionnement"],
    href: "https://www.metro.fr/conseil-service/metro/univers-metiers/Hotel-hebergement",
    cta: "Voir le fournisseur",
  },
  {
    slug: "sumup",
    name: "SumUp",
    family: "Finance & protection",
    category: "Paiement",
    shortDescription: "Terminaux de paiement et encaissement mobile pour professionnels.",
    description:
      "Terminaux autonomes ou connectés, Tap to Pay et solutions d'encaissement pour accepter les paiements au comptoir, à table ou en mobilité.",
    bestFor: "Les commerces, restaurants, artisans, professionnels de la beauté et événements qui veulent encaisser simplement.",
    offerHint: "Sans engagement",
    tags: ["Paiement", "TPE", "Caisse"],
    icon: "BadgeEuro",
    usefulFor: ["Encaissement", "Commerce", "Mobilité"],
    href: "https://www.sumup.com/fr-fr/terminal-de-paiement-terminal/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "onoff-business",
    name: "Onoff Business",
    family: "Équipement & exploitation",
    category: "Téléphonie",
    shortDescription: "Numéros professionnels et standard téléphonique cloud pour les équipes.",
    description:
      "Solution de téléphonie professionnelle pour gérer numéros, appels, SMS, standard, équipes mobiles et intégrations CRM depuis le web ou le mobile.",
    bestFor: "Les indépendants et équipes qui veulent séparer appels personnels et professionnels ou structurer leur accueil téléphonique.",
    offerHint: "Compte en ligne",
    tags: ["Téléphonie", "Numéro pro", "Standard"],
    icon: "Phone",
    usefulFor: ["Appels", "Équipe", "Standard"],
    href: "https://welcome.onoffbusiness.com/standard-telephonique-pro",
    cta: "Voir le fournisseur",
  },
  {
    slug: "edf-entreprises",
    name: "EDF Entreprises",
    family: "Équipement & exploitation",
    category: "Énergie",
    shortDescription: "Offres d'électricité et de gaz dédiées aux professionnels et entreprises.",
    description:
      "Contrats d'électricité et de gaz avec estimation en ligne, gestion des consommations et accompagnement selon la taille de l'entreprise.",
    bestFor: "Les commerces, restaurants, ateliers, bureaux et locaux professionnels qui doivent souscrire ou renouveler un contrat d'énergie.",
    offerHint: "Estimation en ligne",
    tags: ["Énergie", "Électricité", "Gaz"],
    icon: "Zap",
    usefulFor: ["Local", "Machines", "Froid"],
    href: "https://www.edf.fr/entreprises/toutes-les-offres-et-solutions/offres-de-marche-electricite-et-gaz/compare",
    cta: "Voir le fournisseur",
  },
  {
    slug: "bernard",
    name: "Bernard",
    family: "Équipement & exploitation",
    category: "Support",
    shortDescription: "Produits d'hygiène, d'entretien et équipements pour les professionnels.",
    description:
      "Catalogue professionnel de produits d'entretien, consommables sanitaires, matériel de nettoyage, collecte des déchets, EPI et équipements des locaux.",
    bestFor: "Les restaurants, commerces, salons, bureaux et entreprises de nettoyage qui commandent régulièrement des consommables d'hygiène.",
    offerHint: "Commande en ligne",
    tags: ["Hygiène", "Nettoyage", "Consommables"],
    icon: "Sparkles",
    usefulFor: ["Hygiène", "Local", "Public"],
    href: "https://www.bernard.fr/",
    cta: "Voir le fournisseur",
  },
  {
    slug: "insify",
    name: "Insify",
    family: "Finance & protection",
    category: "Assurance",
    shortDescription: "Protection juridique professionnelle avec accompagnement en cas de litige.",
    description:
      "Protection juridique pour les litiges professionnels non couverts par la RC, avec l'appui d'un juriste dédié.",
    bestFor: "Les indépendants et entrepreneurs qui veulent sécuriser leurs contrats et leurs litiges professionnels.",
    offerHint: "Devis en ligne",
    tags: ["Juridique", "Litige", "Protection"],
    icon: "Scale",
    usefulFor: ["Contrats", "Litiges", "Bail"],
    href: "https://www.insify.fr/",
    cta: "Voir le fournisseur",
  },
] as const;

export type DemaaSupplierSlug = (typeof demaaSuppliers)[number]["slug"];

export const supplierFamilies = Array.from(
  new Set(demaaSuppliers.map((supplier) => supplier.family)),
) as SupplierFamily[];

const supplierBySlug = Object.fromEntries(
  demaaSuppliers.map((supplier) => [supplier.slug, supplier]),
) as Partial<Record<DemaaSupplierSlug, DemaaSupplier>>;

export function getDemaaSuppliers(): DemaaSupplier[] {
  return [...demaaSuppliers];
}

export function getDemaaSupplierBySlug(slug: string): DemaaSupplier | null {
  return supplierBySlug[slug as DemaaSupplierSlug] ?? null;
}
