const CURATED_TOOL_RECOMMENDATIONS_BY_SYSTEM: Record<
  string,
  readonly string[]
> = {
  "cabinet-comptable": ["pennylane", "tiimora", "silae"],
  "cabinet-davocat": ["secib", "doctrine"],
  "cabinet-de-conseil": ["everwin", "hubspot", "notion"],
  "agence-marketing": ["furious", "boondmanager", "riverside", "kit", "wordpress"],
  freelance: ["malt", "freebe", "calendly"],
  "agence-de-recrutement": ["recruitee", "hubspot", "calendly"],
  "agence-web": ["figma", "webflow", "github"],
  "creation-de-contenu": ["descript", "ghost", "metricool"],
  marketplace: ["sharetribe", "stripe", "zendesk"],
  media: ["ghost", "riverside", "metricool"],
  saas: ["github", "stripe", "sentry"],
  batiment: ["vertuoza", "graneet", "fieldwire", "oryka"],
  "nettoyage-professionnel": ["organilog", "oryka", "kizeo-forms"],
  "agence-immobiliere": ["apimo", "ubiflow", "modelo"],
  syndic: ["lockimmo", "ublo", "modelo"],
  "gestion-locative": ["lockimmo", "zelok", "modelo"],
  "marchand-de-biens": ["apimo", "pipedrive", "modelo"],
  "investissement-locatif": ["rentila"],
  "conciergerie-airbnb": ["guesty", "organilog", "oryka", "booking-com"],
  "investissement-immobilier": ["lockimmo"],
  "investissement-financier": ["harvest-patrimoine", "quantalys", "affinity"],
  "investissement-entreprise": ["affinity", "everwin"],
  demenagement: ["organilog", "oryka", "geotab"],
  "livraison-dernier-kilometre": ["urbantz", "geotab", "oryka"],
  "transport-de-marchandise": ["dashdoc", "geotab", "shippeo", "oryka"],
  "transport-de-personnes": ["geotab", "organilog", "oryka"],
  restaurant: ["lightspeed", "zenchef", "revya", "deliverect"],
  "fast-food": ["zelty", "deliverect", "revya"],
  traiteur: ["lightspeed", "canva", "deliverect"],
  "dark-kitchen": ["zelty", "deliverect", "brevo"],
  boulangerie: ["lightspeed", "revya", "canva"],
  "commerce-de-detail": ["lightspeed", "shopify", "brevo"],
  "e-commerce": ["shopify", "gorgias", "sendcloud"],
  "institut-de-beaute": ["planity", "square", "metricool"],
  "salon-de-coiffure": ["planity", "square", "metricool"],
  esthetique: ["planity", "square", "metricool"],
  "services-a-la-personne": ["ogust", "praxedo", "oryka"],
  "organisme-de-formation": ["digiforma", "360learning", "fillout"],
  cfa: ["ypareo", "fillout", "livestorm"],
  "formation-en-ligne": ["kajabi", "digiforma", "zoom"],
  "production-industrie": ["odoo", "katana"],
  "plomberie-chauffage": ["esabora", "alobees", "oryka", "kizeo-forms"],
  "electricite-generale": ["esabora", "fieldwire", "oryka", "kizeo-forms"],
  "renovation-interieur": ["vertuoza", "graneet", "fieldwire", "oryka"],
  "menuiserie-agencement": ["progbat", "alobees", "oryka", "fieldwire"],
  "maconnerie-gros-oeuvre": ["onaya", "alobees", "oryka", "fieldwire"],
  paysagiste: ["paysagio", "oryka"],
  "garage-automobile": ["autoprogestion", "keralpha"],
  carrosserie: ["repairsoft", "embray"],
  "commerce-alimentaire": ["lightspeed", "hiboutik", "revya"],
  "boutique-specialisee": ["lightspeed", "shopify", "brevo"],
  "tabac-presse-point-relais": ["lightspeed", "hiboutik"],
  "bar-cafe": ["lightspeed", "laddition", "revya"],
  "hotel-hebergement-independant": ["amenitiz", "d-edge", "booking-com"],
  "cabinet-medical": ["weda", "doctolib"],
  "cabinet-paramedical": ["doctolib", "maiia"],
  "infirmier-liberal": ["vega-idel", "doctolib"],
  "aide-a-domicile-menage": ["ogust", "praxedo", "oryka"],
  "reparation-informatique-mobile": ["repairdesk", "sumup-caisse", "kizeo-forms"],
  "architecte-maitre-oeuvre": ["archipad", "graneet"],
  "courtier-credit-assurance": ["kiilt", "lya", "pipedrive"],
  "auto-ecole": ["kopilo", "codes-rousseau"],
  "photographe-videaste": ["studio-ninja", "pixieset", "descript"],
  evenementiel: ["weezevent", "oryka", "trello", "livestorm"],
  "salle-de-sport": ["gesfit", "bsport"],
  dentiste: ["logosw", "doctolib"],
  pharmacie: ["smart-rx", "winpharma"],
  notaire: ["genapi", "quai-des-notaires", "notalia"],
  veterinaire: ["vetup", "dr-veto"],
  "agence-de-voyage": ["orchestra-travel", "canva", "bokun"],
  opticien: ["winoptics", "ivoirnet"],
  pisciniste: ["extrabat", "fieldwire", "oryka", "kizeo-forms"],
  "diagnostiqueur-immobilier": ["liciel", "geofoncier", "oryka"],
  fleuriste: ["fleuracompta", "shopify", "brevo"],
  pressing: ["hangers-pressing", "blanchinet"],
  "food-truck": ["nomad-caisse", "revya", "canva", "uber-eats"],
  "consultant-independant": ["notion", "pipedrive", "freebe"],
  "cabinet-assurance": ["lya", "pipedrive", "oggo-data"],
  vtc: ["vtc-gestion", "geotab", "simplybook"],
  "coach-professionnel": ["cognito-app", "paperbell", "zoom"],
  "coach-sportif": ["maliora", "simplybook"],
  "laverie-automatique": ["washonline"],
  "entreprise-de-securite": [
    "securigest",
    "oryka",
    "praxedo",
    "kizeo-forms",
  ],
  association: ["assoconnect", "helloasso", "mailchimp"],
  couvreur: ["obat", "alobees", "oryka", "fieldwire"],
  "peintre-en-batiment": ["tolteck", "alobees", "oryka", "fieldwire"],
  carreleur: ["tolteck", "alobees", "oryka", "fieldwire"],
  climatisation: ["esabora", "praxedo", "oryka", "kizeo-forms"],
  serrurier: ["esabora", "praxedo", "oryka", "kizeo-forms"],
  librairie: ["booknroll", "brevo", "ecwid"],
  osteopathe: ["theram", "doctolib"],
  psychologue: ["theram", "doctolib"],
  creche: ["meeko", "kidizz"],
  "gestionnaire-de-patrimoine": ["harvest-patrimoine", "affinity", "quantalys"],
  "chasseur-immobilier": ["apimo", "pipedrive", "modelo"],
  geometre: ["covadis", "geofoncier", "kizeo-forms", "oryka"],
  "daf-externalise": ["pennylane", "regate"],
  "office-manager-externalise": ["notion", "google-workspace", "airtable"],
  "assistant-administratif-externalise": ["google-workspace", "pennylane", "notion"],
  "secretariat-externalise": ["google-workspace", "calendly", "airtable"],
  "gestionnaire-paie-independant": ["silae"],
  "cabinet-rh-externalise": ["lucca", "recruitee"],
  "centre-appels-support-client": ["aircall", "zendesk"],
  "societe-recouvrement": ["leanpay"],
  "centre-affaires-coworking": ["nexudus"],
  "cabinet-qhse-conformite": ["bluekango"],
  "bureau-etudes": ["everwin"],
  "cabinet-etudes": ["typeform", "power-bi"],
  "infogerance-informatique": ["ninjaone", "zendesk"],
  "cybersecurite-pme": [
    "tenable-vulnerability-management",
    "microsoft-defender-business",
  ],
  "integrateur-crm-erp": ["odoo"],
  "consultant-data-bi": ["power-bi"],
  "agence-seo": ["semrush", "google-search-console"],
  "agence-acquisition-paid-ads": [
    "google-ads",
    "meta-ads-manager",
    "google-tag-manager",
  ],
  "studio-branding-design": ["figma", "notion"],
};

export function getCuratedToolRecommendationsForSystem(
  systemSlug: string,
): readonly string[] | undefined {
  return CURATED_TOOL_RECOMMENDATIONS_BY_SYSTEM[systemSlug];
}
