export type ToolDirectoryItem = {
  name: string;
  url: string;
  category: string;
  sectors: string[];
  description: string;
  tags: string[];
  bestFor: string;
  pricingHint: string;
};

export const toolDirectorySectors = [
  "Tous",
  "Services & conseil",
  "Commerce local",
  "E-commerce",
  "Restauration",
  "Artisanat & BTP",
  "Santé & bien-être",
  "Immobilier",
  "Éducation & formation",
  "Associations & événements",
];

export const toolDirectoryCategories = [
  "Tous",
  "Gestion & équipe",
  "CRM & ventes",
  "Marketing & visibilité",
  "IA bureautique",
  "IA dev",
  "Création contenu",
  "Formulaires & collecte",
  "Automatisation",
  "Finance & paiement",
  "Caisse & réservation",
  "Site & e-commerce",
  "RH & planning",
  "Formation",
  "Outils métier",
];

const allSectors = toolDirectorySectors.filter((sector) => sector !== "Tous");

export const toolDirectory: ToolDirectoryItem[] = [
  {
    name: "Google Workspace",
    url: "https://workspace.google.com/",
    category: "Gestion & équipe",
    sectors: allSectors,
    description: "Email pro, Drive, Docs, Sheets et agenda partagé pour structurer l'activité.",
    tags: ["Email pro", "Drive", "Agenda", "Collaboration"],
    bestFor: "Centraliser les fichiers, les échanges et les suivis simples.",
    pricingHint: "Payant",
  },
  {
    name: "Microsoft 365",
    url: "https://www.microsoft.com/microsoft-365/business",
    category: "Gestion & équipe",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Immobilier", "Associations & événements"],
    description: "Outlook, Excel, Teams, OneDrive et Word pour les équipes qui travaillent déjà avec Microsoft.",
    tags: ["Excel", "Outlook", "Teams", "Documents"],
    bestFor: "Les entreprises qui veulent garder Excel et Outlook au centre.",
    pricingHint: "Payant",
  },
  {
    name: "Notion",
    url: "https://www.notion.com/",
    category: "Gestion & équipe",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation", "Associations & événements"],
    description: "Espace simple pour documenter les process, suivre les projets et créer une base interne.",
    tags: ["Documentation", "Process", "Base de suivi"],
    bestFor: "Créer un mini système interne sans logiciel métier lourd.",
    pricingHint: "Freemium",
  },
  {
    name: "Airtable",
    url: "https://www.airtable.com/",
    category: "Gestion & équipe",
    sectors: ["Services & conseil", "Commerce local", "E-commerce", "Artisanat & BTP", "Immobilier", "Associations & événements"],
    description: "Base de suivi visuelle pour leads, commandes, contenus, dossiers ou inventaires.",
    tags: ["Base de données", "Suivi", "Tableau"],
    bestFor: "Structurer un suivi plus propre qu'un tableur classique.",
    pricingHint: "Freemium",
  },
  {
    name: "ClickUp",
    url: "https://clickup.com/",
    category: "Gestion & équipe",
    sectors: ["Services & conseil", "E-commerce", "Artisanat & BTP", "Éducation & formation"],
    description: "Gestion de tâches, projets, documents et tableaux de bord dans un espace unique.",
    tags: ["Projet", "Tâches", "Dashboard"],
    bestFor: "Suivre plusieurs clients ou projets avec plus de structure.",
    pricingHint: "Freemium",
  },
  {
    name: "Trello",
    url: "https://trello.com/",
    category: "Gestion & équipe",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Associations & événements"],
    description: "Tableaux Kanban simples pour organiser les tâches et les étapes d'un projet.",
    tags: ["Tâches", "Kanban", "Projet"],
    bestFor: "Visualiser qui fait quoi sans complexifier l'équipe.",
    pricingHint: "Freemium",
  },
  {
    name: "Slack",
    url: "https://slack.com/intl/fr-fr/",
    category: "Gestion & équipe",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation", "Associations & événements"],
    description: "Messagerie d'équipe avec canaux, notifications et intégrations d'outils.",
    tags: ["Messagerie", "Équipe", "Alertes"],
    bestFor: "Regrouper les échanges d'équipe et les alertes automatisées.",
    pricingHint: "Freemium",
  },
  {
    name: "Make",
    url: "https://www.make.com/",
    category: "Automatisation",
    sectors: allSectors,
    description: "Automatise des process entre formulaires, CRM, emails, fichiers et tableaux de suivi.",
    tags: ["No-code", "Scénarios", "Automatisation"],
    bestFor: "Créer des automatisations lisibles et sur mesure pour TPE.",
    pricingHint: "Freemium",
  },
  {
    name: "Zapier",
    url: "https://zapier.com/fr/",
    category: "Automatisation",
    sectors: ["Services & conseil", "E-commerce", "Commerce local", "Éducation & formation"],
    description: "Connecte rapidement des milliers d'applications pour automatiser des tâches répétitives.",
    tags: ["No-code", "Connecteurs", "Automatisation"],
    bestFor: "Automatiser vite quand les outils sont déjà compatibles.",
    pricingHint: "Freemium",
  },
  {
    name: "n8n",
    url: "https://n8n.io/",
    category: "Automatisation",
    sectors: ["Services & conseil", "E-commerce", "Immobilier"],
    description: "Automatisation plus technique et flexible, avec options cloud ou auto-hébergées.",
    tags: ["Workflow", "API", "No-code"],
    bestFor: "Connecter des outils avec plus de contrôle technique.",
    pricingHint: "Freemium",
  },
  {
    name: "Fillout",
    url: "https://www.fillout.com/",
    category: "Formulaires & collecte",
    sectors: ["Services & conseil", "Commerce local", "E-commerce", "Artisanat & BTP", "Santé & bien-être", "Immobilier", "Éducation & formation"],
    description: "Formulaires modernes pour capter une demande, qualifier un lead ou collecter des infos client.",
    tags: ["Formulaire", "Lead", "Qualification"],
    bestFor: "Créer des formulaires propres et faciles à brancher à une automatisation.",
    pricingHint: "Freemium",
  },
  {
    name: "Tally",
    url: "https://tally.so/",
    category: "Formulaires & collecte",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Associations & événements", "Éducation & formation"],
    description: "Formulaires simples, rapides et légers pour demandes, brief client ou inscription.",
    tags: ["Formulaire", "Brief", "Collecte"],
    bestFor: "Remplacer un email libre par un formulaire clair.",
    pricingHint: "Freemium",
  },
  {
    name: "Google Forms",
    url: "https://www.google.com/forms/about/",
    category: "Formulaires & collecte",
    sectors: allSectors,
    description: "Formulaires gratuits et très accessibles, connectés à Google Sheets.",
    tags: ["Formulaire", "Google Sheets", "Gratuit"],
    bestFor: "Démarrer sans budget avec une collecte simple.",
    pricingHint: "Gratuit",
  },
  {
    name: "Typeform",
    url: "https://www.typeform.com/",
    category: "Formulaires & collecte",
    sectors: ["Services & conseil", "E-commerce", "Santé & bien-être", "Éducation & formation"],
    description: "Formulaires conversationnels pour améliorer l'expérience de réponse.",
    tags: ["Formulaire", "Questionnaire", "Qualification"],
    bestFor: "Créer un parcours de qualification plus premium.",
    pricingHint: "Freemium",
  },
  {
    name: "Brevo",
    url: "https://www.brevo.com/fr/",
    category: "CRM & ventes",
    sectors: ["Services & conseil", "Commerce local", "E-commerce", "Restauration", "Associations & événements"],
    description: "Emailing, CRM léger, SMS et scénarios marketing pour suivre prospects et clients.",
    tags: ["Emailing", "CRM", "SMS", "Relance"],
    bestFor: "Relancer et segmenter une base client sans CRM complexe.",
    pricingHint: "Freemium",
  },
  {
    name: "HubSpot",
    url: "https://www.hubspot.fr/",
    category: "CRM & ventes",
    sectors: ["Services & conseil", "E-commerce", "Immobilier", "Éducation & formation"],
    description: "CRM complet pour suivre prospects, pipeline commercial, formulaires et campagnes.",
    tags: ["CRM", "Pipeline", "Marketing"],
    bestFor: "Structurer une vraie démarche commerciale avec plusieurs étapes.",
    pricingHint: "Freemium",
  },
  {
    name: "Pipedrive",
    url: "https://www.pipedrive.com/fr",
    category: "CRM & ventes",
    sectors: ["Services & conseil", "Artisanat & BTP", "Immobilier"],
    description: "CRM centré sur les opportunités commerciales, les relances et le pipeline.",
    tags: ["CRM", "Pipeline", "Relances"],
    bestFor: "Suivre des opportunités et relances commerciales.",
    pricingHint: "Payant",
  },
  {
    name: "Sellsy",
    url: "https://www.sellsy.com/",
    category: "CRM & ventes",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP"],
    description: "CRM, devis, facturation et suivi commercial dans une suite française.",
    tags: ["CRM", "Devis", "Facturation"],
    bestFor: "Regrouper ventes et facturation dans un même outil.",
    pricingHint: "Payant",
  },
  {
    name: "Axonaut",
    url: "https://www.axonaut.com/",
    category: "CRM & ventes",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Associations & événements"],
    description: "Gestion commerciale, devis, factures, trésorerie et CRM pour petites entreprises.",
    tags: ["ERP léger", "CRM", "Devis", "Factures"],
    bestFor: "Remplacer plusieurs fichiers par une solution plus centralisée.",
    pricingHint: "Payant",
  },
  {
    name: "Canva",
    url: "https://www.canva.com/fr_fr/",
    category: "Marketing & visibilité",
    sectors: allSectors,
    description: "Création rapide de visuels, flyers, posts réseaux sociaux, présentations et supports simples.",
    tags: ["Design", "Réseaux sociaux", "Visuels"],
    bestFor: "Produire des supports propres sans designer interne.",
    pricingHint: "Freemium",
  },
  {
    name: "Metricool",
    url: "https://metricool.com/fr/",
    category: "Marketing & visibilité",
    sectors: ["Services & conseil", "Commerce local", "E-commerce", "Restauration", "Santé & bien-être", "Immobilier", "Associations & événements"],
    description: "Planification, analyse et gestion des réseaux sociaux depuis un même espace.",
    tags: ["Réseaux sociaux", "Planning", "Statistiques"],
    bestFor: "Publier régulièrement sans passer d'un réseau à l'autre.",
    pricingHint: "Freemium",
  },
  {
    name: "Buffer",
    url: "https://buffer.com/",
    category: "Marketing & visibilité",
    sectors: ["Services & conseil", "Commerce local", "E-commerce", "Associations & événements"],
    description: "Planification simple de publications sur les réseaux sociaux.",
    tags: ["Réseaux sociaux", "Planning", "Publication"],
    bestFor: "Démarrer avec un planning éditorial léger.",
    pricingHint: "Freemium",
  },
  {
    name: "Partoo",
    url: "https://www.partoo.co/fr/",
    category: "Marketing & visibilité",
    sectors: ["Commerce local", "Restauration", "Santé & bien-être", "Immobilier"],
    description: "Gestion de présence locale, avis clients, Google Business Profile et messages.",
    tags: ["Avis", "Local", "Google"],
    bestFor: "Piloter la visibilité locale de plusieurs points de contact.",
    pricingHint: "Payant",
  },
  {
    name: "Google Business Profile",
    url: "https://www.google.com/business/",
    category: "Marketing & visibilité",
    sectors: ["Commerce local", "Restauration", "Artisanat & BTP", "Santé & bien-être", "Immobilier"],
    description: "Fiche Google pour apparaître sur Maps, récupérer des avis et donner les infos pratiques.",
    tags: ["Local", "Avis", "Google Maps"],
    bestFor: "Être trouvé localement et rassurer avec les avis.",
    pricingHint: "Gratuit",
  },
  {
    name: "WhatsApp Business",
    url: "https://www.whatsapp.com/business/",
    category: "CRM & ventes",
    sectors: ["Commerce local", "Restauration", "Artisanat & BTP", "Santé & bien-être", "Immobilier"],
    description: "Messagerie client simple avec profil entreprise, réponses rapides et catalogue.",
    tags: ["Messagerie", "Client", "WhatsApp"],
    bestFor: "Répondre vite aux demandes entrantes et éviter les oublis.",
    pricingHint: "Gratuit",
  },
  {
    name: "Calendly",
    url: "https://calendly.com/",
    category: "Caisse & réservation",
    sectors: ["Services & conseil", "Santé & bien-être", "Artisanat & BTP", "Immobilier", "Éducation & formation"],
    description: "Prise de rendez-vous automatisée avec synchronisation agenda.",
    tags: ["Rendez-vous", "Agenda", "Réservation"],
    bestFor: "Éviter les allers-retours pour caler un créneau.",
    pricingHint: "Freemium",
  },
  {
    name: "SimplyBook.me",
    url: "https://simplybook.me/fr/",
    category: "Caisse & réservation",
    sectors: ["Santé & bien-être", "Éducation & formation", "Services & conseil", "Associations & événements"],
    description: "Réservation en ligne pour services, cours, consultations et événements.",
    tags: ["Réservation", "Agenda", "Paiement"],
    bestFor: "Créer un agenda de réservation plus complet qu'un simple lien.",
    pricingHint: "Freemium",
  },
  {
    name: "Doctolib",
    url: "https://www.doctolib.fr/",
    category: "Outils métier",
    sectors: ["Santé & bien-être"],
    description: "Prise de rendez-vous et visibilité pour professionnels de santé.",
    tags: ["Rendez-vous", "Santé", "Patients"],
    bestFor: "Gérer les créneaux et simplifier la prise de rendez-vous patient.",
    pricingHint: "Payant",
  },
  {
    name: "Maiia",
    url: "https://www.maiia.com/",
    category: "Outils métier",
    sectors: ["Santé & bien-être"],
    description: "Agenda, téléconsultation et prise de rendez-vous pour professionnels de santé.",
    tags: ["Santé", "Agenda", "Téléconsultation"],
    bestFor: "Gérer rendez-vous et parcours patient en ligne.",
    pricingHint: "Payant",
  },
  {
    name: "Planity",
    url: "https://www.planity.com/",
    category: "Caisse & réservation",
    sectors: ["Santé & bien-être", "Commerce local"],
    description: "Réservation en ligne pour salons de coiffure, beauté, bien-être et établissements locaux.",
    tags: ["Réservation", "Beauté", "Planning"],
    bestFor: "Remplir l'agenda et réduire les appels entrants.",
    pricingHint: "Payant",
  },
  {
    name: "Treatwell",
    url: "https://www.treatwell.fr/partenaires/",
    category: "Caisse & réservation",
    sectors: ["Santé & bien-être", "Commerce local"],
    description: "Marketplace et réservation pour salons de beauté, coiffure et bien-être.",
    tags: ["Beauté", "Réservation", "Visibilité"],
    bestFor: "Trouver de nouveaux clients et gérer les créneaux beauté.",
    pricingHint: "Commission",
  },
  {
    name: "Wavy",
    url: "https://www.wavy.co/",
    category: "Caisse & réservation",
    sectors: ["Santé & bien-être", "Commerce local"],
    description: "Caisse, planning, fichier client et marketing pour salons de coiffure et beauté.",
    tags: ["Caisse", "Planning", "Beauté"],
    bestFor: "Gérer un salon avec caisse, agenda et clients au même endroit.",
    pricingHint: "Payant",
  },
  {
    name: "Zenchef",
    url: "https://www.zenchef.com/fr/",
    category: "Caisse & réservation",
    sectors: ["Restauration"],
    description: "Réservations, fichier client et visibilité en ligne pour restaurants.",
    tags: ["Réservation", "Restaurant", "Clients"],
    bestFor: "Centraliser les réservations et réduire les no-show.",
    pricingHint: "Payant",
  },
  {
    name: "TheFork Manager",
    url: "https://www.theforkmanager.com/fr-fr/",
    category: "Caisse & réservation",
    sectors: ["Restauration"],
    description: "Réservation restaurant, visibilité et gestion de salle via l'écosystème TheFork.",
    tags: ["Restaurant", "Réservation", "Visibilité"],
    bestFor: "Remplir les tables et gérer les réservations entrantes.",
    pricingHint: "Payant",
  },
  {
    name: "Lightspeed Restaurant",
    url: "https://www.lightspeedhq.fr/caisse-enregistreuse/restaurant/",
    category: "Caisse & réservation",
    sectors: ["Restauration"],
    description: "Caisse restaurant, commandes, paiements, reporting et gestion opérationnelle.",
    tags: ["Caisse", "Restaurant", "Commande"],
    bestFor: "Structurer la caisse et le pilotage d'un restaurant.",
    pricingHint: "Payant",
  },
  {
    name: "Zelty",
    url: "https://zelty.fr/",
    category: "Caisse & réservation",
    sectors: ["Restauration"],
    description: "Caisse restaurant, click & collect, livraison et pilotage multi-sites.",
    tags: ["Caisse", "Restaurant", "Livraison"],
    bestFor: "Gérer caisse, commandes et canaux digitaux en restauration.",
    pricingHint: "Payant",
  },
  {
    name: "SumUp",
    url: "https://www.sumup.com/fr-fr/",
    category: "Finance & paiement",
    sectors: ["Commerce local", "Restauration", "Artisanat & BTP", "Santé & bien-être", "Associations & événements"],
    description: "Terminaux de paiement, liens de paiement et outils d'encaissement simples.",
    tags: ["TPE", "Paiement", "Encaissement"],
    bestFor: "Encaisser facilement en mobilité ou en boutique.",
    pricingHint: "Commission",
  },
  {
    name: "Square",
    url: "https://squareup.com/fr/fr",
    category: "Caisse & réservation",
    sectors: ["Commerce local", "Restauration", "Santé & bien-être", "Associations & événements"],
    description: "Caisse, terminaux de paiement, catalogue, rendez-vous et suivi des ventes.",
    tags: ["Caisse", "Paiement", "Vente"],
    bestFor: "Avoir une caisse simple avec paiement et catalogue.",
    pricingHint: "Commission",
  },
  {
    name: "Zettle",
    url: "https://www.zettle.com/fr",
    category: "Finance & paiement",
    sectors: ["Commerce local", "Restauration", "Associations & événements"],
    description: "Terminal de paiement et application de vente pour petites structures.",
    tags: ["TPE", "Paiement", "Caisse"],
    bestFor: "Encaisser simplement sur place avec terminal mobile.",
    pricingHint: "Commission",
  },
  {
    name: "Lightspeed Retail",
    url: "https://www.lightspeedhq.fr/caisse-enregistreuse/retail/",
    category: "Caisse & réservation",
    sectors: ["Commerce local"],
    description: "Caisse retail, gestion de stock, clients, paiements et reporting boutique.",
    tags: ["Caisse", "Stock", "Retail"],
    bestFor: "Piloter une boutique avec stock et caisse connectés.",
    pricingHint: "Payant",
  },
  {
    name: "Shopify",
    url: "https://www.shopify.com/fr",
    category: "Site & e-commerce",
    sectors: ["E-commerce", "Commerce local"],
    description: "Plateforme e-commerce pour vendre en ligne, gérer catalogue, paiements et commandes.",
    tags: ["E-commerce", "Boutique", "Commandes"],
    bestFor: "Lancer ou structurer une boutique en ligne.",
    pricingHint: "Payant",
  },
  {
    name: "WooCommerce",
    url: "https://woocommerce.com/",
    category: "Site & e-commerce",
    sectors: ["E-commerce", "Commerce local"],
    description: "Solution e-commerce pour WordPress, flexible et très répandue.",
    tags: ["WordPress", "E-commerce", "Boutique"],
    bestFor: "Ajouter une boutique à un site WordPress existant.",
    pricingHint: "Freemium",
  },
  {
    name: "PrestaShop",
    url: "https://www.prestashop.com/fr",
    category: "Site & e-commerce",
    sectors: ["E-commerce"],
    description: "Solution e-commerce open source pour boutiques avec catalogue plus complet.",
    tags: ["E-commerce", "Catalogue", "Open source"],
    bestFor: "Créer une boutique flexible avec plus de personnalisation.",
    pricingHint: "Freemium",
  },
  {
    name: "Wix",
    url: "https://fr.wix.com/",
    category: "Site & e-commerce",
    sectors: ["Services & conseil", "Commerce local", "Restauration", "Santé & bien-être", "Éducation & formation"],
    description: "Création de site vitrine, réservation, e-commerce léger et pages marketing.",
    tags: ["Site", "No-code", "Vitrine"],
    bestFor: "Créer vite un site simple sans équipe technique.",
    pricingHint: "Freemium",
  },
  {
    name: "Webflow",
    url: "https://webflow.com/",
    category: "Site & e-commerce",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation"],
    description: "Création de sites plus design et personnalisés sans développement classique.",
    tags: ["Site", "Design", "CMS"],
    bestFor: "Créer un site premium avec un fort contrôle visuel.",
    pricingHint: "Payant",
  },
  {
    name: "Klaviyo",
    url: "https://www.klaviyo.com/",
    category: "Marketing & visibilité",
    sectors: ["E-commerce"],
    description: "Email marketing et automatisations e-commerce orientées segmentation et panier.",
    tags: ["Emailing", "E-commerce", "Automatisation"],
    bestFor: "Relancer paniers, clients et campagnes e-commerce.",
    pricingHint: "Freemium",
  },
  {
    name: "Pennylane",
    url: "https://www.pennylane.com/",
    category: "Finance & paiement",
    sectors: allSectors,
    description: "Facturation, comptabilité et pilotage financier pour entreprises et cabinets comptables.",
    tags: ["Comptabilité", "Factures", "Finance"],
    bestFor: "Centraliser la compta et mieux suivre les finances.",
    pricingHint: "Payant",
  },
  {
    name: "Tiime",
    url: "https://www.tiime.fr/",
    category: "Finance & paiement",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Santé & bien-être"],
    description: "Facturation, compte pro, notes de frais et comptabilité pour entrepreneurs et TPE.",
    tags: ["Facturation", "Compta", "Compte pro"],
    bestFor: "Simplifier l'administratif financier d'une petite structure.",
    pricingHint: "Freemium",
  },
  {
    name: "Indy",
    url: "https://www.indy.fr/",
    category: "Finance & paiement",
    sectors: ["Services & conseil", "Santé & bien-être", "Éducation & formation"],
    description: "Comptabilité et déclarations simplifiées pour indépendants et petites structures.",
    tags: ["Comptabilité", "Indépendants", "Déclarations"],
    bestFor: "Gérer la compta quand on travaille en solo ou petite équipe.",
    pricingHint: "Freemium",
  },
  {
    name: "Qonto",
    url: "https://qonto.com/fr",
    category: "Finance & paiement",
    sectors: allSectors,
    description: "Compte pro, cartes, gestion des justificatifs et suivi des dépenses.",
    tags: ["Compte pro", "Dépenses", "Cartes"],
    bestFor: "Clarifier les dépenses et simplifier l'administratif financier.",
    pricingHint: "Payant",
  },
  {
    name: "Stripe",
    url: "https://stripe.com/fr",
    category: "Finance & paiement",
    sectors: ["Services & conseil", "E-commerce", "Commerce local", "Éducation & formation", "Associations & événements"],
    description: "Paiement en ligne, liens de paiement, abonnements et checkout sécurisé.",
    tags: ["Paiement", "Checkout", "Abonnement"],
    bestFor: "Encaisser en ligne sans construire un tunnel complet.",
    pricingHint: "Commission",
  },
  {
    name: "Henrri",
    url: "https://www.henrri.com/",
    category: "Finance & paiement",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Santé & bien-être"],
    description: "Facturation gratuite pour devis, factures, relances et suivi de règlements.",
    tags: ["Facturation", "Devis", "Relances"],
    bestFor: "Démarrer la facturation sans abonnement.",
    pricingHint: "Gratuit",
  },
  {
    name: "Evoliz",
    url: "https://www.evoliz.com/",
    category: "Finance & paiement",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Associations & événements"],
    description: "Facturation, gestion commerciale, pré-comptabilité et suivi pour TPE/PME.",
    tags: ["Facturation", "Gestion", "Compta"],
    bestFor: "Gérer devis, factures et pilotage dans une boîte à outils française.",
    pricingHint: "Payant",
  },
  {
    name: "Sage 50",
    url: "https://www.sage.com/fr-fr/produits/sage-50cloud/",
    category: "Finance & paiement",
    sectors: ["Commerce local", "Artisanat & BTP", "Services & conseil"],
    description: "Gestion commerciale, comptabilité, facturation et stock pour petites entreprises.",
    tags: ["Comptabilité", "Gestion", "Stock"],
    bestFor: "Centraliser gestion commerciale et comptable dans un outil établi.",
    pricingHint: "Payant",
  },
  {
    name: "Obat",
    url: "https://www.obat.fr/",
    category: "Outils métier",
    sectors: ["Artisanat & BTP"],
    description: "Devis, factures, suivi de chantier et bibliothèque d'ouvrages pour artisans du bâtiment.",
    tags: ["BTP", "Devis", "Factures", "Chantier"],
    bestFor: "Gagner du temps sur les devis et le suivi administratif chantier.",
    pricingHint: "Payant",
  },
  {
    name: "Tolteck",
    url: "https://www.tolteck.com/",
    category: "Outils métier",
    sectors: ["Artisanat & BTP"],
    description: "Logiciel de devis et factures pensé pour les artisans et entreprises du bâtiment.",
    tags: ["BTP", "Devis", "Factures"],
    bestFor: "Créer des devis propres sans tableur maison.",
    pricingHint: "Payant",
  },
  {
    name: "Costructor",
    url: "https://www.costructor.fr/",
    category: "Outils métier",
    sectors: ["Artisanat & BTP"],
    description: "Gestion BTP pour devis, factures, planning, interventions et suivi de rentabilité.",
    tags: ["BTP", "Planning", "Rentabilité"],
    bestFor: "Piloter devis, équipes, interventions et marge chantier.",
    pricingHint: "Freemium",
  },
  {
    name: "Vertuoza",
    url: "https://www.vertuoza.com/fr/",
    category: "Outils métier",
    sectors: ["Artisanat & BTP"],
    description: "Logiciel bâtiment complet pour devis, facturation, planning, suivi chantier et CRM.",
    tags: ["BTP", "CRM", "Chantier"],
    bestFor: "Centraliser le cycle chantier du devis au suivi terrain.",
    pricingHint: "Payant",
  },
  {
    name: "Batappli",
    url: "https://www.batappli.fr/",
    category: "Outils métier",
    sectors: ["Artisanat & BTP"],
    description: "Devis, factures, suivi de chantier, stock et bibliothèques métier pour artisans du bâtiment.",
    tags: ["BTP", "Devis", "Stock"],
    bestFor: "Travailler avec une solution BTP reconnue et spécialisée.",
    pricingHint: "Payant",
  },
  {
    name: "Sage Batigest",
    url: "https://www.sage.com/fr-fr/produits/sage-batigest/",
    category: "Outils métier",
    sectors: ["Artisanat & BTP"],
    description: "Gestion bâtiment pour devis, facturation, suivi de chantier et bibliothèques de prix.",
    tags: ["BTP", "Chiffrage", "Chantier"],
    bestFor: "Gérer des chantiers et devis avec un outil BTP complet.",
    pricingHint: "Payant",
  },
  {
    name: "Extrabat",
    url: "https://www.extrabat.com/",
    category: "Outils métier",
    sectors: ["Artisanat & BTP"],
    description: "CRM et gestion commerciale pour artisans avec devis, planning, interventions et suivi client.",
    tags: ["BTP", "CRM", "Intervention"],
    bestFor: "Suivre les demandes, rendez-vous, devis et interventions terrain.",
    pricingHint: "Payant",
  },
  {
    name: "Hektor",
    url: "https://www.la-boite-immo.com/logiciel-immobilier-hektor/",
    category: "Outils métier",
    sectors: ["Immobilier"],
    description: "Logiciel immobilier pour agences : mandats, annonces, contacts, rapprochements et diffusion.",
    tags: ["Immobilier", "Mandats", "Annonces"],
    bestFor: "Gérer une agence immobilière avec biens, contacts et diffusion.",
    pricingHint: "Payant",
  },
  {
    name: "Apimo",
    url: "https://apimo.pro/",
    category: "Outils métier",
    sectors: ["Immobilier"],
    description: "CRM immobilier pour gestion de biens, contacts, mandats, passerelles et sites d'agence.",
    tags: ["Immobilier", "CRM", "Diffusion"],
    bestFor: "Centraliser les biens et la relation client immobilier.",
    pricingHint: "Payant",
  },
  {
    name: "Netty",
    url: "https://www.netty.fr/",
    category: "Outils métier",
    sectors: ["Immobilier"],
    description: "Logiciel immobilier pour annonces, pige, rapprochement, CRM et site internet.",
    tags: ["Immobilier", "Annonces", "CRM"],
    bestFor: "Gérer les annonces et le suivi commercial d'une agence.",
    pricingHint: "Payant",
  },
  {
    name: "Ubiflow",
    url: "https://www.ubiflow.net/",
    category: "Marketing & visibilité",
    sectors: ["Immobilier", "Commerce local"],
    description: "Diffusion d'annonces et gestion de présence locale sur plusieurs plateformes.",
    tags: ["Diffusion", "Annonces", "Local"],
    bestFor: "Publier automatiquement des annonces sur plusieurs portails.",
    pricingHint: "Payant",
  },
  {
    name: "Teachizy",
    url: "https://www.teachizy.fr/",
    category: "Site & e-commerce",
    sectors: ["Éducation & formation"],
    description: "Plateforme française pour créer, vendre et gérer des formations en ligne.",
    tags: ["Formation", "LMS", "Paiement"],
    bestFor: "Vendre une formation sans développer une plateforme sur mesure.",
    pricingHint: "Freemium",
  },
  {
    name: "Podia",
    url: "https://www.podia.com/",
    category: "Site & e-commerce",
    sectors: ["Éducation & formation", "Services & conseil"],
    description: "Vente de formations, produits digitaux, abonnements et pages simples.",
    tags: ["Formation", "Produits digitaux", "Abonnement"],
    bestFor: "Monétiser du contenu ou une expertise simplement.",
    pricingHint: "Payant",
  },
  {
    name: "LearnyBox",
    url: "https://learnybox.com/",
    category: "Site & e-commerce",
    sectors: ["Éducation & formation"],
    description: "Plateforme de formations en ligne, tunnels, emails et paiement pour infopreneurs.",
    tags: ["Formation", "Tunnel", "Emailing"],
    bestFor: "Regrouper vente, formation et marketing dans un outil unique.",
    pricingHint: "Payant",
  },
  {
    name: "HelloAsso",
    url: "https://www.helloasso.com/",
    category: "Finance & paiement",
    sectors: ["Associations & événements"],
    description: "Collecte de paiements, adhésions, billetterie, dons et crowdfunding pour associations.",
    tags: ["Association", "Billetterie", "Dons"],
    bestFor: "Encaisser et gérer les paiements associatifs sans complexité.",
    pricingHint: "Gratuit",
  },
  {
    name: "Billetweb",
    url: "https://www.billetweb.fr/",
    category: "Caisse & réservation",
    sectors: ["Associations & événements", "Éducation & formation"],
    description: "Billetterie en ligne pour événements, ateliers, formations et inscriptions.",
    tags: ["Billetterie", "Événement", "Inscription"],
    bestFor: "Vendre des places et suivre les inscriptions événementielles.",
    pricingHint: "Commission",
  },
  {
    name: "Yurplan",
    url: "https://yurplan.com/",
    category: "Caisse & réservation",
    sectors: ["Associations & événements"],
    description: "Billetterie, inscription et gestion participants pour événements.",
    tags: ["Événement", "Billetterie", "Participants"],
    bestFor: "Organiser un événement avec inscriptions et paiements.",
    pricingHint: "Commission",
  },
  {
    name: "Combo",
    url: "https://combohr.com/fr/",
    category: "RH & planning",
    sectors: ["Restauration", "Commerce local", "Santé & bien-être"],
    description: "Planning d'équipe, pointage, congés et préparation paie pour équipes terrain.",
    tags: ["Planning", "RH", "Pointage"],
    bestFor: "Gérer les plannings et absences d'une équipe opérationnelle.",
    pricingHint: "Payant",
  },
  {
    name: "Skello",
    url: "https://www.skello.io/",
    category: "RH & planning",
    sectors: ["Restauration", "Commerce local", "Santé & bien-être"],
    description: "Planning, temps de travail, absences, pointage et variables de paie.",
    tags: ["Planning", "RH", "Paie"],
    bestFor: "Structurer les plannings quand les horaires changent souvent.",
    pricingHint: "Payant",
  },
  {
    name: "PayFit",
    url: "https://payfit.com/fr/",
    category: "RH & planning",
    sectors: ["Services & conseil", "Commerce local", "Restauration", "Santé & bien-être"],
    description: "Paie, congés, notes RH et gestion administrative des salariés.",
    tags: ["Paie", "RH", "Congés"],
    bestFor: "Simplifier la paie et l'administratif RH d'une petite équipe.",
    pricingHint: "Payant",
  },
  {
    name: "Factorial",
    url: "https://factorial.fr/",
    category: "RH & planning",
    sectors: ["Services & conseil", "Commerce local", "Restauration", "Éducation & formation"],
    description: "SIRH pour congés, documents, temps, intégration et gestion RH.",
    tags: ["RH", "Congés", "Intégration"],
    bestFor: "Centraliser les demandes RH et documents salariés.",
    pricingHint: "Payant",
  },
  {
    name: "ChatGPT",
    url: "https://chatgpt.com/",
    category: "IA bureautique",
    sectors: allSectors,
    description: "Assistant IA pour rédiger, résumer, structurer des idées et préparer des documents.",
    tags: ["Rédaction", "Synthèse", "Assistant IA"],
    bestFor: "Gagner du temps sur les textes, emails, plans et documents du quotidien.",
    pricingHint: "Freemium",
  },
  {
    name: "Claude",
    url: "https://claude.ai/",
    category: "IA bureautique",
    sectors: allSectors,
    description: "Assistant IA utile pour analyser des contenus longs, clarifier des idées et rédiger avec nuance.",
    tags: ["Analyse", "Rédaction", "Documents"],
    bestFor: "Travailler des textes longs, comptes rendus, contenus et notes de cadrage.",
    pricingHint: "Freemium",
  },
  {
    name: "Gemini",
    url: "https://gemini.google.com/",
    category: "IA bureautique",
    sectors: allSectors,
    description: "Assistant IA de Google pour rechercher, écrire, organiser et travailler avec l'écosystème Google.",
    tags: ["Google", "Assistant IA", "Recherche"],
    bestFor: "Accélérer les tâches bureautiques quand l'équipe utilise déjà Google.",
    pricingHint: "Freemium",
  },
  {
    name: "Microsoft Copilot",
    url: "https://www.microsoft.com/microsoft-copilot",
    category: "IA bureautique",
    sectors: ["Services & conseil", "Commerce local", "Artisanat & BTP", "Immobilier", "Éducation & formation", "Associations & événements"],
    description: "Assistant IA intégré à l'univers Microsoft pour aider sur Word, Excel, Outlook et Teams.",
    tags: ["Microsoft 365", "Excel", "Email"],
    bestFor: "Aider les équipes qui travaillent déjà avec Outlook, Excel et Teams.",
    pricingHint: "Payant",
  },
  {
    name: "Notion AI",
    url: "https://www.notion.com/product/ai",
    category: "IA bureautique",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation", "Associations & événements"],
    description: "IA intégrée à Notion pour résumer, reformuler et organiser les bases de connaissances.",
    tags: ["Notion", "Documentation", "Synthèse"],
    bestFor: "Rendre une base interne plus facile à exploiter et maintenir.",
    pricingHint: "Payant",
  },
  {
    name: "Codex",
    url: "https://openai.com/codex/",
    category: "IA dev",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation"],
    description: "Agent IA pour aider à lire, modifier, tester et faire avancer du code.",
    tags: ["Code", "Agent IA", "Développement"],
    bestFor: "Accélérer les petites évolutions produit, scripts internes et prototypes.",
    pricingHint: "Payant",
  },
  {
    name: "Cursor",
    url: "https://cursor.com/",
    category: "IA dev",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation"],
    description: "Éditeur de code avec IA intégrée pour écrire, comprendre et refactorer plus vite.",
    tags: ["Code", "IDE", "Assistant IA"],
    bestFor: "Développer plus rapidement avec un assistant directement dans l'éditeur.",
    pricingHint: "Freemium",
  },
  {
    name: "GitHub Copilot",
    url: "https://github.com/features/copilot",
    category: "IA dev",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation"],
    description: "Assistant de développement intégré à l'environnement GitHub et aux éditeurs de code.",
    tags: ["Code", "GitHub", "Assistant IA"],
    bestFor: "Aider les développeurs à compléter, expliquer et générer du code.",
    pricingHint: "Payant",
  },
  {
    name: "Gemini Code Assist",
    url: "https://codeassist.google/",
    category: "IA dev",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation"],
    description: "Assistant IA de Google pour aider les équipes à développer et comprendre leur code.",
    tags: ["Code", "Google", "Assistant IA"],
    bestFor: "Accompagner le développement quand l'équipe travaille déjà dans l'écosystème Google.",
    pricingHint: "Freemium",
  },
  {
    name: "Replit",
    url: "https://replit.com/",
    category: "IA dev",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation", "Associations & événements"],
    description: "Environnement de développement en ligne avec aide IA pour prototyper et lancer des projets.",
    tags: ["Prototype", "Code", "Cloud"],
    bestFor: "Créer rapidement un prototype ou un petit outil interne.",
    pricingHint: "Freemium",
  },
  {
    name: "Lovable",
    url: "https://lovable.dev/",
    category: "IA dev",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation"],
    description: "Outil IA pour générer des interfaces et applications web à partir d'un brief.",
    tags: ["Prototype", "No-code", "App web"],
    bestFor: "Tester vite une idée d'application avant un développement plus solide.",
    pricingHint: "Freemium",
  },
  {
    name: "Descript",
    url: "https://www.descript.com/",
    category: "Création contenu",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation", "Associations & événements"],
    description: "Montage audio et vidéo assisté par IA, avec transcription et édition comme un document.",
    tags: ["Vidéo", "Podcast", "Transcription"],
    bestFor: "Transformer des enregistrements en contenus publiables plus rapidement.",
    pricingHint: "Freemium",
  },
  {
    name: "HeyGen",
    url: "https://www.heygen.com/",
    category: "Création contenu",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation"],
    description: "Création de vidéos avec avatars IA, doublage et traduction vidéo.",
    tags: ["Vidéo IA", "Avatar", "Traduction"],
    bestFor: "Produire des vidéos explicatives ou commerciales sans tournage lourd.",
    pricingHint: "Freemium",
  },
  {
    name: "CapCut",
    url: "https://www.capcut.com/",
    category: "Création contenu",
    sectors: ["Services & conseil", "Commerce local", "E-commerce", "Restauration", "Santé & bien-être", "Associations & événements"],
    description: "Montage vidéo simple pour formats courts, réseaux sociaux et contenus rapides.",
    tags: ["Vidéo", "Réseaux sociaux", "Montage"],
    bestFor: "Créer vite des vidéos courtes pour Instagram, TikTok ou LinkedIn.",
    pricingHint: "Freemium",
  },
  {
    name: "ElevenLabs",
    url: "https://elevenlabs.io/",
    category: "Création contenu",
    sectors: ["Services & conseil", "E-commerce", "Éducation & formation", "Associations & événements"],
    description: "Génération de voix IA pour vidéos, formations, podcasts et contenus audio.",
    tags: ["Voix IA", "Audio", "Narration"],
    bestFor: "Ajouter une voix off propre sans enregistrer chaque version à la main.",
    pricingHint: "Freemium",
  },
  {
    name: "Digiforma",
    url: "https://www.digiforma.com/",
    category: "Formation",
    sectors: ["Éducation & formation"],
    description: "Gestion administrative, LMS, documents Qualiopi et suivi des formations.",
    tags: ["Formation", "Qualiopi", "LMS"],
    bestFor: "Structurer l'administratif et le suivi d'un organisme de formation.",
    pricingHint: "Payant",
  },
  {
    name: "Dendreo",
    url: "https://www.dendreo.com/",
    category: "Formation",
    sectors: ["Éducation & formation"],
    description: "ERP pour organismes de formation avec gestion commerciale, administrative et qualité.",
    tags: ["Formation", "ERP", "Qualiopi"],
    bestFor: "Piloter un organisme de formation avec un vrai outil métier.",
    pricingHint: "Payant",
  },
  {
    name: "360Learning",
    url: "https://360learning.com/",
    category: "Formation",
    sectors: ["Éducation & formation", "Services & conseil"],
    description: "Plateforme LMS collaborative pour créer, diffuser et suivre des parcours de formation.",
    tags: ["LMS", "Formation", "Collaboratif"],
    bestFor: "Déployer des parcours de formation pour équipes ou clients.",
    pricingHint: "Payant",
  },
  {
    name: "LearnDash",
    url: "https://www.learndash.com/",
    category: "Formation",
    sectors: ["Éducation & formation"],
    description: "Plugin LMS pour WordPress afin de créer et vendre des formations en ligne.",
    tags: ["WordPress", "LMS", "Cours en ligne"],
    bestFor: "Ajouter une plateforme de cours à un site WordPress existant.",
    pricingHint: "Payant",
  },
  {
    name: "Livestorm",
    url: "https://livestorm.co/",
    category: "Formation",
    sectors: ["Éducation & formation", "Services & conseil", "Associations & événements"],
    description: "Webinaires, classes en ligne et événements vidéo avec inscriptions et relances.",
    tags: ["Webinaire", "Classe en ligne", "Inscription"],
    bestFor: "Organiser des sessions de formation ou ateliers en ligne avec suivi des participants.",
    pricingHint: "Freemium",
  },
];
